# Generated by Django 4.2 on 2026-07-06 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OdooConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('base_empresa', models.CharField(db_index=True, help_text='Nombre de la base MySQL de origen (base_empresa).', max_length=64, verbose_name='Base empresa AdministraNET')),
                ('base_url', models.URLField(max_length=512, verbose_name='URL Odoo')),
                ('database', models.CharField(blank=True, help_text='Header X-Odoo-Database cuando el host sirve varias bases.', max_length=128, verbose_name='Base de datos Odoo')),
                ('api_key_encrypted', models.TextField(blank=True, verbose_name='API key (cifrada)')),
                ('api_key_label', models.CharField(blank=True, max_length=200, verbose_name='Etiqueta API key')),
                ('api_key_expires_at', models.DateField(blank=True, null=True, verbose_name='Vencimiento API key')),
                ('api_mode', models.CharField(choices=[('json2', 'JSON-2'), ('xmlrpc', 'XML-RPC (legacy)')], default='json2', max_length=16, verbose_name='Modo API')),
                ('timeout_seconds', models.PositiveIntegerField(default=60, verbose_name='Timeout (segundos)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_test_ok_at', models.DateTimeField(blank=True, null=True, verbose_name='Última prueba OK')),
                ('last_test_message', models.CharField(blank=True, max_length=500, verbose_name='Último mensaje de prueba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conexión Odoo',
                'verbose_name_plural': 'Conexiones Odoo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(db_index=True, max_length=64, verbose_name='Dominio')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('ok', 'Completado'), ('error', 'Error'), ('cancelado', 'Cancelado')], default='pendiente', max_length=16, verbose_name='Estado')),
                ('offset', models.PositiveIntegerField(default=0, verbose_name='Offset')),
                ('total_procesados', models.PositiveIntegerField(default=0, verbose_name='Procesados')),
                ('total_errores', models.PositiveIntegerField(default=0, verbose_name='Errores')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('iniciado_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado')),
                ('finalizado_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conexion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='odoo_migracion.odooconnection', verbose_name='Conexión')),
            ],
            options={
                'verbose_name': 'Job de migración',
                'verbose_name_plural': 'Jobs de migración',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationEntityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=64, verbose_name='Tipo entidad')),
                ('adminet_id', models.CharField(db_index=True, max_length=64, verbose_name='ID AdministraNET')),
                ('external_id', models.CharField(db_index=True, max_length=128, verbose_name='External ID Odoo')),
                ('odoo_model', models.CharField(max_length=64, verbose_name='Modelo Odoo')),
                ('odoo_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID Odoo')),
                ('last_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash último payload')),
                ('sync_state', models.CharField(choices=[('pendiente', 'Pendiente'), ('ok', 'OK'), ('error', 'Error')], default='pendiente', max_length=16, verbose_name='Estado sync')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conexion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='odoo_migracion.odooconnection')),
            ],
            options={
                'verbose_name': 'Mapeo de entidad',
                'verbose_name_plural': 'Mapeos de entidades',
            },
        ),
        migrations.AddConstraint(
            model_name='migrationentitymapping',
            constraint=models.UniqueConstraint(fields=('conexion', 'entity_type', 'adminet_id'), name='odoo_mig_unique_adminet_entity'),
        ),
        migrations.AddConstraint(
            model_name='migrationentitymapping',
            constraint=models.UniqueConstraint(fields=('conexion', 'external_id'), name='odoo_mig_unique_external_id'),
        ),
    ]
