# Generated by Django 4.2 on 2026-02-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.CharField(max_length=255, verbose_name="Bucket")),
                (
                    "storage_key",
                    models.CharField(max_length=512, verbose_name="Key en storage"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=128, verbose_name="Content-Type"),
                ),
                (
                    "size_bytes",
                    models.PositiveIntegerField(verbose_name="Tamaño bytes"),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Nombre original"),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Hash (opcional)"
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False, verbose_name="Contenido sensible"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cases.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adjunto",
                "verbose_name_plural": "Adjuntos",
                "db_table": "support_attachment",
            },
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["message"], name="support_att_message_5a63c5_idx"
            ),
        ),
    ]
