# Generated by Django 4.2 on 2025-10-24 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_increase_permiso_codigo_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('orchestrator', 'Orquestador'), ('query_interpreter', 'Intérprete de Consulta'), ('data_analyst', 'Analista de Datos'), ('logic_interpreter', 'Intérprete de Lógica'), ('report_generator', 'Generador de Reportes'), ('validator', 'Validador'), ('webhook', 'Webhook')], max_length=50, verbose_name='Agente')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total_invocations', models.IntegerField(default=0, verbose_name='Total Invocaciones')),
                ('successful_invocations', models.IntegerField(default=0, verbose_name='Invocaciones Exitosas')),
                ('failed_invocations', models.IntegerField(default=0, verbose_name='Invocaciones Fallidas')),
                ('avg_processing_time', models.FloatField(default=0.0, verbose_name='Tiempo Promedio (seg)')),
                ('avg_confidence_score', models.FloatField(default=0.0, verbose_name='Score Confianza Promedio')),
                ('total_tokens_used', models.IntegerField(default=0, verbose_name='Total Tokens')),
                ('hallucination_count', models.IntegerField(default=0, help_text='Respuestas bloqueadas por validación', verbose_name='Alucinaciones Detectadas')),
            ],
            options={
                'verbose_name': 'Métrica de Agente',
                'verbose_name_plural': 'Métricas de Agentes',
                'ordering': ['-date', 'agent_name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único de la regla', max_length=100, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre funcional de la regla', max_length=200, verbose_name='Nombre')),
                ('rule_type', models.CharField(choices=[('calculation', 'Cálculo'), ('validation', 'Validación'), ('state', 'Estado'), ('transition', 'Transición'), ('eligibility', 'Elegibilidad')], max_length=20, verbose_name='Tipo de Regla')),
                ('description', models.TextField(help_text='Explicación en términos de negocio, sin código ni SQL', verbose_name='Descripción de Negocio')),
                ('module', models.CharField(help_text='Ej: Ventas, Inventario, Cobranzas', max_length=100, verbose_name='Módulo de Negocio')),
                ('conditions', models.JSONField(blank=True, default=list, help_text='Condiciones de aplicación en lenguaje de negocio', verbose_name='Condiciones')),
                ('exceptions', models.JSONField(blank=True, default=list, help_text='Casos excepcionales', verbose_name='Excepciones')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Vigente Desde')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Vigente Hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('source_info', models.JSONField(blank=True, default=dict, help_text='Metadata interna para trazabilidad (no técnica)', verbose_name='Info de Origen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de Negocio',
                'verbose_name_plural': 'Reglas de Negocio',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Término funcional', max_length=200, unique=True, verbose_name='Término')),
                ('definition', models.TextField(help_text='Definición en lenguaje de negocio', verbose_name='Definición')),
                ('synonyms', models.JSONField(blank=True, default=list, verbose_name='Sinónimos')),
                ('category', models.CharField(help_text='Ej: Ventas, Inventario, Clientes', max_length=100, verbose_name='Categoría')),
                ('examples', models.JSONField(blank=True, default=list, verbose_name='Ejemplos de Uso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Término del Glosario',
                'verbose_name_plural': 'Términos del Glosario',
                'ordering': ['category', 'term'],
            },
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(help_text='Identificador único de la solicitud', max_length=100, unique=True, verbose_name='ID de Solicitud')),
                ('intent', models.CharField(help_text='Intención de negocio del reporte', max_length=200, verbose_name='Intención')),
                ('query_text', models.TextField(help_text='Texto original de la solicitud', verbose_name='Consulta Original')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parámetros estructurados: periodo, filtros, segmentación', verbose_name='Parámetros')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('source', models.CharField(choices=[('web', 'Interfaz Web'), ('webhook', 'Webhook Externo'), ('api', 'API REST'), ('scheduled', 'Programado')], default='web', max_length=20, verbose_name='Origen')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Datos del reporte generado', verbose_name='Respuesta')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de Procesamiento (seg)')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens Utilizados')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Score de Confianza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to='core.empresa', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Reporte',
                'verbose_name_plural': 'Solicitudes de Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='glossaryterm',
            index=models.Index(fields=['term'], name='reports_ai__term_d474bb_idx'),
        ),
        migrations.AddIndex(
            model_name='glossaryterm',
            index=models.Index(fields=['category', 'is_active'], name='reports_ai__categor_1df31e_idx'),
        ),
        migrations.AddIndex(
            model_name='businessrule',
            index=models.Index(fields=['code'], name='reports_ai__code_b3af6a_idx'),
        ),
        migrations.AddIndex(
            model_name='businessrule',
            index=models.Index(fields=['module', 'is_active'], name='reports_ai__module_5e00f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentmetrics',
            unique_together={('agent_name', 'date')},
        ),
        migrations.AddIndex(
            model_name='reportrequest',
            index=models.Index(fields=['request_id'], name='reports_ai__request_3cce78_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrequest',
            index=models.Index(fields=['status', 'created_at'], name='reports_ai__status_15a2df_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrequest',
            index=models.Index(fields=['user', '-created_at'], name='reports_ai__user_id_a207a7_idx'),
        ),
    ]
