# Generated by Django 4.2 on 2025-10-25 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports_ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businessrule',
            name='reports_ai__code_b3af6a_idx',
        ),
        migrations.RemoveField(
            model_name='businessrule',
            name='code',
        ),
        migrations.RemoveField(
            model_name='businessrule',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='businessrule',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='businessrule',
            name='exceptions',
        ),
        migrations.RemoveField(
            model_name='businessrule',
            name='rule_type',
        ),
        migrations.RemoveField(
            model_name='businessrule',
            name='source_info',
        ),
        migrations.AddField(
            model_name='businessrule',
            name='actions',
            field=models.TextField(default='', help_text='Acciones que se ejecutan cuando se cumple la regla', verbose_name='Acciones'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='category',
            field=models.CharField(choices=[('validation', 'Validación'), ('business', 'Lógica de Negocio'), ('calculation', 'Cálculo'), ('workflow', 'Flujo de Trabajo'), ('integration', 'Integración')], default='business', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_rules', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='source_file',
            field=models.CharField(blank=True, help_text='Archivo VB6/PHP donde se encontró la regla', max_length=500, null=True, verbose_name='Archivo de Origen'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='source_line',
            field=models.IntegerField(blank=True, help_text='Número de línea en el archivo fuente', null=True, verbose_name='Línea de Código'),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags separados por comas para categorización', max_length=500, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='businessrule',
            name='conditions',
            field=models.TextField(default='', help_text='Condiciones de aplicación en lenguaje de negocio', verbose_name='Condiciones'),
        ),
        migrations.AddIndex(
            model_name='businessrule',
            index=models.Index(fields=['category', 'is_active'], name='reports_ai__categor_baf04d_idx'),
        ),
        migrations.AddIndex(
            model_name='businessrule',
            index=models.Index(fields=['created_at'], name='reports_ai__created_08b236_idx'),
        ),
    ]
