# Generated by Django 4.2 on 2025-10-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_ai', '0002_remove_businessrule_reports_ai__code_b3af6a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryterm',
            name='context',
            field=models.CharField(blank=True, default='', help_text='Contexto de uso del término', max_length=200, verbose_name='Contexto'),
        ),
    ]
