# Generated by Django 4.2 on 2025-10-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_ai', '0003_glossaryterm_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='context',
            field=models.TextField(blank=True, default='', help_text='Contexto adicional de la solicitud', verbose_name='Contexto'),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridad'),
        ),
    ]
