# Generated by Django 4.2 on 2025-10-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_ai', '0004_reportrequest_context_reportrequest_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequest',
            name='source',
            field=models.CharField(choices=[('web', 'Interfaz Web'), ('webhook', 'Webhook Externo'), ('api', 'API REST'), ('scheduled', 'Programado')], default='web', max_length=50, verbose_name='Origen'),
        ),
    ]
