# Generated by Django 4.2 on 2025-10-25 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports_ai', '0005_alter_reportrequest_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLUFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(verbose_name='Consulta Original')),
                ('system_intent', models.CharField(max_length=100, verbose_name='Intent del Sistema')),
                ('system_slots', models.JSONField(default=dict, verbose_name='Slots del Sistema')),
                ('correct_intent', models.CharField(max_length=100, verbose_name='Intent Correcto')),
                ('correct_slots', models.JSONField(default=dict, verbose_name='Slots Correctos')),
                ('user_comment', models.TextField(blank=True, default='', verbose_name='Comentario del Usuario')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('processed', 'Procesado'), ('ignored', 'Ignorado')], default='pending', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('critical', 'Crítica')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback NLU',
                'verbose_name_plural': 'Feedbacks NLU',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NLUMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(verbose_name='Fecha de Evaluación')),
                ('period_type', models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='weekly', max_length=20, verbose_name='Tipo de Periodo')),
                ('total_queries', models.IntegerField(default=0, verbose_name='Total de Consultas')),
                ('correctly_classified', models.IntegerField(default=0, verbose_name='Clasificadas Correctamente')),
                ('misclassified', models.IntegerField(default=0, verbose_name='Mal Clasificadas')),
                ('ambiguous', models.IntegerField(default=0, verbose_name='Ambiguas')),
                ('out_of_context', models.IntegerField(default=0, verbose_name='Fuera de Contexto')),
                ('coverage_rate', models.FloatField(default=0.0, help_text='% de consultas entendidas sin intervención', verbose_name='Tasa de Cobertura')),
                ('clarification_rate', models.FloatField(default=0.0, help_text='% de veces que pide precisión', verbose_name='Tasa de Aclaración')),
                ('misroute_rate', models.FloatField(default=0.0, help_text='% de enrutamiento a intent equivocado', verbose_name='Tasa de Error de Enrutamiento')),
                ('intent_metrics', models.JSONField(default=dict, help_text='F1, precision, recall por cada intent', verbose_name='Métricas por Intent')),
                ('slot_accuracy', models.FloatField(default=0.0, help_text='% de slots correctamente extraídos', verbose_name='Exactitud de Slots')),
                ('model_version', models.CharField(max_length=50, verbose_name='Versión del Modelo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica NLU',
                'verbose_name_plural': 'Métricas NLU',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='NLUTrainingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='Consulta original del usuario', verbose_name='Texto de Consulta')),
                ('intent', models.CharField(help_text='Intención clasificada (ventas, inventario, clientes, etc.)', max_length=100, verbose_name='Intent')),
                ('slots', models.JSONField(default=dict, help_text='Slots extraídos: categoria, periodo, filtros, segmentaciones, etc.', verbose_name='Slots')),
                ('is_canonical', models.BooleanField(default=False, help_text='Ejemplo congelado para detección de deriva', verbose_name='Ejemplo Canónico')),
                ('source', models.CharField(default='manual', help_text='manual, feedback, webhook, auto-generated', max_length=50, verbose_name='Origen')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('critical', 'Crítica')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nlu_examples_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejemplo de Entrenamiento NLU',
                'verbose_name_plural': 'Ejemplos de Entrenamiento NLU',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NLUModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='ej: v1.0.0, v1.1.0-beta', max_length=50, unique=True, verbose_name='Versión')),
                ('description', models.TextField(help_text='Cambios y mejoras en esta versión', verbose_name='Descripción')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('shadow', 'En Prueba (Shadow)'), ('retired', 'Retirado'), ('rollback', 'Rollback')], default='shadow', max_length=20, verbose_name='Estado')),
                ('f1_global', models.FloatField(default=0.0, verbose_name='F1 Global')),
                ('intent_accuracy', models.FloatField(default=0.0, verbose_name='Accuracy de Intent')),
                ('slot_accuracy', models.FloatField(default=0.0, verbose_name='Accuracy de Slots')),
                ('coverage_rate', models.FloatField(default=0.0, verbose_name='Tasa de Cobertura')),
                ('temperature', models.FloatField(default=0.2, verbose_name='Temperature')),
                ('top_p', models.FloatField(default=0.9, verbose_name='Top P')),
                ('training_examples_count', models.IntegerField(default=0, verbose_name='Cantidad de Ejemplos de Entrenamiento')),
                ('canonical_examples_count', models.IntegerField(default=0, verbose_name='Ejemplos Canónicos')),
                ('trained_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrenamiento')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Activación')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Retiro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo NLU',
                'verbose_name_plural': 'Modelos NLU',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='nlumetrics',
            index=models.Index(fields=['evaluation_date', 'period_type'], name='reports_ai__evaluat_9cff40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nlumetrics',
            unique_together={('evaluation_date', 'period_type')},
        ),
        migrations.AddField(
            model_name='nlufeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nlufeedback',
            name='report_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nlu_feedbacks', to='reports_ai.reportrequest'),
        ),
        migrations.AddIndex(
            model_name='nlutrainingexample',
            index=models.Index(fields=['intent', 'is_active'], name='reports_ai__intent_f5533e_idx'),
        ),
        migrations.AddIndex(
            model_name='nlutrainingexample',
            index=models.Index(fields=['is_canonical'], name='reports_ai__is_cano_e78fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='nlumodel',
            index=models.Index(fields=['status'], name='reports_ai__status_2561d3_idx'),
        ),
        migrations.AddIndex(
            model_name='nlumodel',
            index=models.Index(fields=['version'], name='reports_ai__version_507a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='nlufeedback',
            index=models.Index(fields=['status', 'priority'], name='reports_ai__status_74458e_idx'),
        ),
        migrations.AddIndex(
            model_name='nlufeedback',
            index=models.Index(fields=['created_at'], name='reports_ai__created_6ebf53_idx'),
        ),
    ]
