# Generated by Django 4.2 on 2025-10-25 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports_ai', '0006_nlufeedback_nlumetrics_nlutrainingexample_nlumodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicTrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Identificador único de la sesión de entrenamiento', max_length=100, unique=True, verbose_name='ID de Sesión')),
                ('status', models.CharField(choices=[('running', 'En Ejecución'), ('completed', 'Completado'), ('error', 'Error'), ('cancelled', 'Cancelado')], default='running', max_length=20, verbose_name='Estado')),
                ('categories', models.JSONField(default=list, help_text='Categorías a analizar: inventario, ventas, etc.', verbose_name='Categorías')),
                ('mode', models.CharField(choices=[('full', 'Completo'), ('incremental', 'Incremental')], default='full', max_length=20, verbose_name='Modo')),
                ('total_forms', models.IntegerField(default=0, verbose_name='Total de Formularios')),
                ('analyzed_forms', models.IntegerField(default=0, verbose_name='Formularios Analizados')),
                ('current_phase', models.CharField(default='scan', help_text='scan, analyze, infer, validate, extract, save', max_length=50, verbose_name='Fase Actual')),
                ('current_item', models.CharField(blank=True, default='', help_text='Formulario o tabla siendo procesada', max_length=200, verbose_name='Item Actual')),
                ('progress_percentage', models.FloatField(default=0.0, verbose_name='Porcentaje de Progreso')),
                ('entities_discovered', models.JSONField(default=list, verbose_name='Entidades Descubiertas')),
                ('tables_suggested', models.JSONField(default=list, verbose_name='Tablas Sugeridas')),
                ('fields_validated', models.JSONField(default=dict, verbose_name='Campos Validados')),
                ('relations_found', models.JSONField(default=list, verbose_name='Relaciones Encontradas')),
                ('rules_extracted', models.JSONField(default=list, verbose_name='Reglas Extraídas')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('success_rate', models.FloatField(default=0.0, help_text='% de formularios analizados exitosamente', verbose_name='Tasa de Éxito')),
                ('avg_confidence', models.FloatField(default=0.0, help_text='Promedio de confianza de tablas sugeridas', verbose_name='Confianza Promedio')),
                ('tables_verified', models.IntegerField(default=0, verbose_name='Tablas Verificadas en MySQL')),
                ('fields_match_rate', models.FloatField(default=0.0, help_text='% de campos sugeridos que existen en MySQL', verbose_name='Tasa de Coincidencia de Campos')),
                ('log_entries', models.JSONField(default=list, help_text='Log de eventos durante el entrenamiento', verbose_name='Entradas de Log')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de Error')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logic_training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Sesión de Entrenamiento Logic Interpreter',
                'verbose_name_plural': 'Sesiones de Entrenamiento Logic Interpreter',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='logictrainingsession',
            index=models.Index(fields=['session_id'], name='reports_ai__session_fa4a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='logictrainingsession',
            index=models.Index(fields=['status', '-start_time'], name='reports_ai__status_10f07c_idx'),
        ),
    ]
