# Generated by Django 4.2 on 2025-10-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_ai', '0007_logictrainingsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrule',
            name='source_function',
            field=models.CharField(blank=True, help_text='Nombre de la función, procedimiento o método donde se encontró la regla', max_length=200, null=True, verbose_name='Función/Procedimiento'),
        ),
    ]
