# Generated by Django 4.2 on 2025-10-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_ai', '0008_businessrule_source_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrule',
            name='business_procedure',
            field=models.TextField(blank=True, default='', help_text='Descripción del proceso completo de negocio (ej: Cómo crear una factura, cómo hacer movimiento de stock)', verbose_name='Procedimiento de Negocio'),
        ),
    ]
