# Generated by Django 4.2 on 2025-10-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_ai', '0009_businessrule_business_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='sql_query',
            field=models.TextField(blank=True, default='', help_text='Query SQL generada por el Data Analyst Agent', verbose_name='SQL Query Generada'),
        ),
    ]
