# Generated by Django 4.2 on 2025-10-25 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports_ai', '0010_reportrequest_sql_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=100, verbose_name='Nombre de Tabla')),
                ('column_name', models.CharField(max_length=100, verbose_name='Nombre de Columna')),
                ('total_count', models.IntegerField(default=0, verbose_name='Total de Registros')),
                ('unique_count', models.IntegerField(default=0, verbose_name='Valores Únicos')),
                ('null_count', models.IntegerField(default=0, verbose_name='Valores Nulos')),
                ('is_unique', models.BooleanField(default=False, verbose_name='Es Único')),
                ('is_nullable', models.BooleanField(default=True, verbose_name='Permite Nulos')),
                ('null_percentage', models.FloatField(default=0.0, verbose_name='% Nulos')),
                ('sample_values', models.JSONField(default=list, help_text='Top 20 valores más frecuentes con sus conteos', verbose_name='Valores de Muestra')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculado En')),
                ('is_stale', models.BooleanField(default=False, help_text='True si hace más de 7 días desde la última actualización', verbose_name='Desactualizado')),
            ],
            options={
                'verbose_name': 'Estadística de Columna',
                'verbose_name_plural': 'Estadísticas de Columnas',
            },
        ),
        migrations.CreateModel(
            name='QueryCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_query', models.TextField(verbose_name='Query Original')),
                ('original_sql', models.TextField(verbose_name='SQL Original')),
                ('correction_type', models.CharField(choices=[('wrong_table', 'Tabla Incorrecta'), ('wrong_column', 'Columna Incorrecta'), ('missing_join', 'Join Faltante'), ('wrong_join', 'Join Incorrecto'), ('wrong_filter', 'Filtro Incorrecto'), ('performance', 'Problema de Performance')], max_length=50, verbose_name='Tipo de Corrección')),
                ('corrected_sql', models.TextField(blank=True, verbose_name='SQL Corregida')),
                ('correction_notes', models.TextField(help_text='Explicación de qué se corrigió y por qué', verbose_name='Notas de Corrección')),
                ('applied_to_catalog', models.BooleanField(default=False, verbose_name='Aplicado al Catálogo')),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Corrección de Query',
                'verbose_name_plural': 'Correcciones de Queries',
                'ordering': ['-corrected_at'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(db_index=True, max_length=100, verbose_name='Tabla Origen')),
                ('source_column', models.CharField(max_length=100, verbose_name='Columna Origen')),
                ('target_table', models.CharField(db_index=True, max_length=100, verbose_name='Tabla Destino')),
                ('target_column', models.CharField(max_length=100, verbose_name='Columna Destino')),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0 a 1.0, calculado por múltiples señales', verbose_name='Score de Confianza')),
                ('name_match_score', models.FloatField(default=0.0, verbose_name='Coincidencia de Nombre')),
                ('type_compatibility', models.FloatField(default=0.0, verbose_name='Compatibilidad de Tipo')),
                ('domain_inclusion', models.FloatField(default=0.0, verbose_name='Inclusión de Dominio')),
                ('uniqueness_score', models.FloatField(default=0.0, verbose_name='Score de Unicidad')),
                ('logic_interpreter_hint', models.BooleanField(default=False, verbose_name='Sugerido por Logic Interpreter')),
                ('has_index', models.BooleanField(default=False, verbose_name='Tiene Índice')),
                ('cardinality', models.CharField(choices=[('1:1', 'Uno a Uno'), ('1:N', 'Uno a Muchos'), ('N:1', 'Muchos a Uno'), ('N:M', 'Muchos a Muchos')], default='N:1', max_length=20, verbose_name='Cardinalidad')),
                ('role', models.CharField(default='maestro-detalle', help_text='maestro-detalle, catalogo-transaccional, etc.', max_length=50, verbose_name='Rol Funcional')),
                ('validated_by_human', models.BooleanField(default=False, verbose_name='Validada por Humano')),
                ('times_used_successfully', models.IntegerField(default=0, verbose_name='Veces Usada Exitosamente')),
                ('times_failed', models.IntegerField(default=0, verbose_name='Veces Fallida')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Vez Usada')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Descubrimiento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Relación Candidata',
                'verbose_name_plural': 'Relaciones Candidatas',
                'ordering': ['-confidence_score', '-times_used_successfully'],
            },
        ),
        migrations.CreateModel(
            name='SynonymMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_term', models.CharField(db_index=True, help_text='Ej: provincia, cliente, artículo', max_length=100, verbose_name='Término de Negocio')),
                ('column_pattern', models.CharField(help_text='Ej: CodProvincia, IDProvincia, ProvinciaId', max_length=200, verbose_name='Patrón de Columna')),
                ('confidence', models.FloatField(default=0.5, help_text='Calculado por uso exitoso', verbose_name='Confianza')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('logic_interpreter', 'Logic Interpreter'), ('discovered', 'Descubierto Automáticamente'), ('validated', 'Validado por Usuario')], default='discovered', max_length=50, verbose_name='Fuente')),
                ('times_used', models.IntegerField(default=0, verbose_name='Veces Usado')),
                ('times_successful', models.IntegerField(default=0, verbose_name='Veces Exitoso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapeo de Sinónimo',
                'verbose_name_plural': 'Mapeos de Sinónimos',
                'ordering': ['-confidence', '-times_successful'],
                'unique_together': {('business_term', 'column_pattern')},
            },
        ),
        migrations.AddIndex(
            model_name='relationshipcandidate',
            index=models.Index(fields=['source_table', 'target_table'], name='reports_ai__source__86298c_idx'),
        ),
        migrations.AddIndex(
            model_name='relationshipcandidate',
            index=models.Index(fields=['confidence_score'], name='reports_ai__confide_dacee0_idx'),
        ),
        migrations.AddIndex(
            model_name='relationshipcandidate',
            index=models.Index(fields=['-times_used_successfully'], name='reports_ai__times_u_5fb588_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relationshipcandidate',
            unique_together={('source_table', 'source_column', 'target_table', 'target_column')},
        ),
        migrations.AddField(
            model_name='querycorrection',
            name='corrected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Corregido Por'),
        ),
        migrations.AddField(
            model_name='querycorrection',
            name='report_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='reports_ai.reportrequest', verbose_name='Solicitud de Reporte'),
        ),
        migrations.AddIndex(
            model_name='columnstatistics',
            index=models.Index(fields=['table_name'], name='reports_ai__table_n_0c5b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='columnstatistics',
            index=models.Index(fields=['is_unique'], name='reports_ai__is_uniq_548f50_idx'),
        ),
        migrations.AddIndex(
            model_name='columnstatistics',
            index=models.Index(fields=['calculated_at'], name='reports_ai__calcula_a8c064_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='columnstatistics',
            unique_together={('table_name', 'column_name')},
        ),
    ]
