# Generated by Django 4.2 on 2025-10-27 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports_ai', '0011_columnstatistics_querycorrection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Auto-generado del primer mensaje', max_length=200, verbose_name='Título')),
                ('is_active', models.BooleanField(default=True, help_text='Conversación activa o archivada', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conversación de Chat',
                'verbose_name_plural': 'Conversaciones de Chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('message_type', models.CharField(choices=[('text', 'Texto Simple'), ('procedure', 'Procedimiento'), ('report_data', 'Datos de Reporte'), ('report_chart', 'Gráfico'), ('download_offer', 'Oferta de Descarga'), ('clarification', 'Solicitud de Aclaración'), ('error', 'Error')], default='text', max_length=50, verbose_name='Tipo de Mensaje')),
                ('intent', models.CharField(blank=True, max_length=100, verbose_name='Intención Detectada')),
                ('entities', models.JSONField(blank=True, default=dict, verbose_name='Entidades Extraídas')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos extra como formato de tabla, opciones de gráfico, etc.', verbose_name='Metadata Adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reports_ai.chatconversation', verbose_name='Conversación')),
                ('report_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='reports_ai.reportrequest', verbose_name='Solicitud de Reporte')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('export_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV')], max_length=10, verbose_name='Formato')),
                ('file', models.FileField(max_length=500, upload_to='reports_ai/exports/%Y/%m/', verbose_name='Archivo')),
                ('filename', models.CharField(max_length=255, verbose_name='Nombre de Archivo')),
                ('file_size', models.IntegerField(verbose_name='Tamaño de Archivo (bytes)')),
                ('template_used', models.CharField(default='default', help_text='Nombre del template usado para la exportación', max_length=100, verbose_name='Template Usado')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Primera Descarga')),
                ('download_count', models.IntegerField(default=0, verbose_name='Número de Descargas')),
                ('export_options', models.JSONField(blank=True, default=dict, help_text='Opciones como incluir logo, colores, etc.', verbose_name='Opciones de Exportación')),
                ('chat_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='reports_ai.chatmessage', verbose_name='Mensaje de Chat')),
                ('report_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports_ai.reportrequest', verbose_name='Solicitud de Reporte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Exportación de Reporte',
                'verbose_name_plural': 'Exportaciones de Reportes',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['user', '-generated_at'], name='reports_ai__user_id_c83aed_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['format'], name='reports_ai__format_ee12f0_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['report_request'], name='reports_ai__report__f00649_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='reports_ai__convers_9aea05_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='reports_ai__role_3ca12e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type'], name='reports_ai__message_13ffdb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', '-updated_at'], name='reports_ai__user_id_2d347a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['is_active'], name='reports_ai__is_acti_964f56_idx'),
        ),
    ]
