# Generated by Django 4.2 on 2025-10-27 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports_ai', '0012_chatconversation_chatmessage_reportexport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, help_text='Ej: Ventas, Stock, Clientes, Facturación', max_length=100, verbose_name='Módulo Funcional')),
                ('procedure', models.CharField(db_index=True, help_text='Ej: Crear pedido, Guardar factura, Movimiento de stock', max_length=200, verbose_name='Procedimiento')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del procedimiento', verbose_name='Descripción')),
                ('vb6_forms', models.TextField(help_text='Nombres de formularios VB6 separados por coma. Ej: Pedido.frm, Pedido_Avanzado.frm', verbose_name='Formularios VB6')),
                ('vb6_modules', models.TextField(blank=True, help_text='Módulos .bas o .cls separados por coma', verbose_name='Módulos VB6')),
                ('php_scripts', models.TextField(blank=True, help_text='Scripts PHP separados por coma', verbose_name='Scripts PHP')),
                ('entities', models.TextField(help_text='Entidades de negocio separadas por coma. Ej: Pedido, Cliente, Articulo, Sucursal', verbose_name='Entidades Involucradas')),
                ('candidate_tables', models.TextField(help_text='Tablas de BD separadas por coma. Ej: comp_ped, cuerpostockpe, cliente', verbose_name='Tablas Candidatas')),
                ('master_table', models.CharField(blank=True, help_text='Tabla principal del procedimiento. Ej: comp_ped', max_length=100, verbose_name='Tabla Maestra')),
                ('detail_table', models.CharField(blank=True, help_text='Tabla de detalle/líneas. Ej: cuerpostockpe', max_length=100, verbose_name='Tabla Detalle')),
                ('key_fields', models.TextField(help_text='Campos importantes separados por coma. Ej: CodigoMovimiento, Codigo, IDArt, Total', verbose_name='Campos Clave')),
                ('relevant_events', models.TextField(blank=True, help_text='Eventos VB6 que disparan el proceso. Ej: Guardar(), cmdGuardar_Click()', verbose_name='Eventos Relevantes')),
                ('business_rules', models.TextField(help_text='Descripción de reglas de negocio aplicables', verbose_name='Reglas Funcionales')),
                ('validations', models.TextField(blank=True, help_text='Validaciones que se ejecutan. Ej: Cliente activo, Stock suficiente', verbose_name='Validaciones')),
                ('dependencies', models.TextField(blank=True, help_text='Otros módulos o procesos relacionados. Ej: Presupuesto, Numeración', verbose_name='Dependencias')),
                ('table_relationships', models.JSONField(blank=True, default=dict, help_text='JSON con relaciones. Ej: {"comp_ped.CodigoMovimiento": "cuerpostockpe.CodigoMovimiento"}', verbose_name='Relaciones entre Tablas')),
                ('insert_tables', models.TextField(blank=True, help_text='Tablas donde se insertan registros', verbose_name='Tablas con INSERT')),
                ('update_tables', models.TextField(blank=True, help_text='Tablas donde se actualizan registros', verbose_name='Tablas con UPDATE')),
                ('confidence', models.FloatField(default=0.9, help_text='Nivel de certeza de 0.0 a 1.0', verbose_name='Confianza Inicial')),
                ('priority', models.IntegerField(default=5, help_text='1-10, donde 10 es máxima prioridad', verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('last_revision', models.DateField(auto_now=True, verbose_name='Última Revisión')),
                ('notes', models.TextField(blank=True, help_text='Observaciones o comentarios adicionales', verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functional_catalogs_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Entrada de Catálogo Funcional',
                'verbose_name_plural': 'Catálogo Funcional',
                'ordering': ['-priority', 'module', 'procedure'],
            },
        ),
        migrations.AddIndex(
            model_name='functionalcatalog',
            index=models.Index(fields=['module'], name='reports_ai__module_6b806a_idx'),
        ),
        migrations.AddIndex(
            model_name='functionalcatalog',
            index=models.Index(fields=['is_active', '-priority'], name='reports_ai__is_acti_cee984_idx'),
        ),
        migrations.AddIndex(
            model_name='functionalcatalog',
            index=models.Index(fields=['-confidence'], name='reports_ai__confide_dfa3a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='functionalcatalog',
            unique_together={('module', 'procedure')},
        ),
    ]
