# Generated by Django 4.2 on 2025-10-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_ai', '0013_functionalcatalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionalcatalog',
            name='last_trained',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último entrenamiento exitoso', null=True, verbose_name='Último Entrenamiento'),
        ),
    ]
