# Generated by Django 4.2 on 2025-07-23 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_api_key', models.CharField(blank=True, help_text='API key for OpenWeatherMap or other weather provider', max_length=128, null=True, verbose_name='Weather API Key')),
                ('weather_provider', models.CharField(default='openweathermap', help_text='Weather API provider', max_length=64, verbose_name='Weather Provider')),
                ('traccar_api_url', models.URLField(blank=True, null=True, verbose_name='Traccar API URL')),
                ('traccar_api_token', models.CharField(blank=True, max_length=128, null=True, verbose_name='Traccar API Token')),
                ('use_traccar', models.BooleanField(default=False, verbose_name='Enable Traccar Integration')),
                ('use_smartphone_tracking', models.BooleanField(default=True, verbose_name='Enable Smartphone Tracking')),
                ('google_maps_api_key', models.CharField(blank=True, max_length=128, null=True, verbose_name='Google Maps API Key')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logistics Configuration',
                'verbose_name_plural': 'Logistics Configurations',
            },
        ),
        migrations.CreateModel(
            name='TrackingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_traccar', models.BooleanField(default=False, help_text='Enable real-time tracking using Traccar platform', verbose_name='Enable Traccar Integration')),
                ('traccar_api_url', models.URLField(blank=True, help_text='Base URL for Traccar API (e.g., http://traccar-server:8082/api)', null=True, verbose_name='Traccar API URL')),
                ('traccar_api_token', models.CharField(blank=True, help_text='API token for authenticating with Traccar', max_length=128, null=True, verbose_name='Traccar API Token')),
                ('use_smartphone_tracking', models.BooleanField(default=True, help_text='Enable real-time tracking using smartphone GPS and Google Maps', verbose_name='Enable Smartphone Tracking')),
                ('google_maps_api_key', models.CharField(blank=True, help_text='API key for Google Maps JavaScript and Geolocation', max_length=128, null=True, verbose_name='Google Maps API Key')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tracking Configuration',
                'verbose_name_plural': 'Tracking Configurations',
            },
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=64, null=True, verbose_name='Role')),
                ('receive_push', models.BooleanField(default=True, verbose_name='Push Notifications')),
                ('receive_email', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('events', models.JSONField(default=list, help_text='List of event types to notify (e.g. delayed, out_geofence, incident, completed)', verbose_name='Event Types')),
                ('channels', models.JSONField(default=list, help_text='List of preferred channels (push, email, sms, etc.)', verbose_name='Preferred Channels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_notification_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logistics Notification Config',
                'verbose_name_plural': 'Logistics Notification Configs',
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('polygon', models.JSONField(blank=True, help_text='GeoJSON coordinates for polygon geofence', null=True, verbose_name='Polygon')),
                ('center_lat', models.FloatField(blank=True, null=True, verbose_name='Center Latitude')),
                ('center_lng', models.FloatField(blank=True, null=True, verbose_name='Center Longitude')),
                ('radius_m', models.FloatField(blank=True, null=True, verbose_name='Radius (meters)')),
                ('client_id', models.IntegerField(blank=True, null=True, verbose_name='Client ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofences', to='logistics.deliveryroute')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofences', to='logistics.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='smartphone', max_length=32)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='logistics.driver')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='smartphone', max_length=32)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_location', to='logistics.driver')),
            ],
        ),
    ]
