# Generated by Django 4.2 on 2025-07-15 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministraNETConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Host o IP del servidor MySQL de administraNET', max_length=255, verbose_name='Host')),
                ('port', models.IntegerField(default=3306, help_text='Puerto de conexión MySQL', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Puerto')),
                ('database_name', models.CharField(help_text='Nombre de la base de datos de administraNET', max_length=255, verbose_name='Nombre de Base de Datos')),
                ('username', models.CharField(help_text='Usuario de MySQL', max_length=255, verbose_name='Usuario')),
                ('password', models.CharField(help_text='Contraseña de MySQL', max_length=255, verbose_name='Contraseña')),
                ('is_active', models.BooleanField(default=False, help_text='Activar o desactivar la integración', verbose_name='Activa')),
                ('sync_interval', models.IntegerField(default=30, help_text='Intervalo en minutos para sincronización automática', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Intervalo de Sincronización (minutos)')),
                ('enable_logging', models.BooleanField(default=True, help_text='Registrar todas las operaciones de sincronización', verbose_name='Habilitar Logs')),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', help_text='Nivel de detalle para los logs', max_length=20, verbose_name='Nivel de Log')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Fecha y hora de la última sincronización exitosa', null=True, verbose_name='Última Sincronización')),
            ],
            options={
                'verbose_name': 'Configuración administraNET',
                'verbose_name_plural': 'Configuraciones administraNET',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('PRODUCTS', 'Productos'), ('STOCK', 'Stock'), ('CUSTOMERS', 'Clientes'), ('ORDERS', 'Pedidos'), ('FULL', 'Sincronización Completa')], max_length=20, verbose_name='Tipo de Sincronización')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando'), ('SUCCESS', 'Exitoso'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_deleted', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Log de Sincronización',
                'verbose_name_plural': 'Logs de Sincronización',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(choices=[('PRODUCTS', 'Productos'), ('STOCK', 'Stock'), ('CUSTOMERS', 'Clientes'), ('ORDERS', 'Pedidos'), ('SUPPLIERS', 'Proveedores'), ('CATEGORIES', 'Categorías')], max_length=20, verbose_name='Tipo de Mapeo')),
                ('administraNET_table', models.CharField(help_text='Nombre de la tabla en administraNET', max_length=255, verbose_name='Tabla administraNET')),
                ('synap_model', models.CharField(help_text='Nombre del modelo en Synap (app.model)', max_length=255, verbose_name='Modelo Synap')),
                ('is_active', models.BooleanField(default=True, help_text='Activar o desactivar este mapeo', verbose_name='Activo')),
                ('sync_direction', models.CharField(choices=[('TO_SYNAP', 'Hacia Synap'), ('FROM_SYNAP', 'Desde Synap'), ('BIDIRECTIONAL', 'Bidireccional')], default='TO_SYNAP', max_length=15, verbose_name='Dirección de Sincronización')),
                ('field_mappings', models.JSONField(blank=True, default=dict, help_text='Diccionario de mapeo de campos: {"campo_admin": "campo_synap"}', verbose_name='Mapeo de Campos')),
                ('sync_frequency', models.IntegerField(default=30, help_text='Frecuencia específica para este mapeo (0 = usar configuración global)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Frecuencia de Sincronización (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapeo de Tabla',
                'verbose_name_plural': 'Mapeos de Tablas',
                'ordering': ['mapping_type', 'administraNET_table'],
                'unique_together': {('mapping_type', 'administraNET_table')},
            },
        ),
    ]
