# Generated by Django 4.2 on 2025-07-16 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_empresa_state'),
        ('administraNET_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synclog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='records_deleted',
        ),
        migrations.AddField(
            model_name='synclog',
            name='error_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalles del Error'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por'),
        ),
        migrations.AddField(
            model_name='tablemapping',
            name='use_preset_mapping',
            field=models.BooleanField(default=True, help_text='Usar mapeo predefinido para este tipo', verbose_name='Usar Mapeo Predefinido'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completado'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Error'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='records_created',
            field=models.IntegerField(default=0, verbose_name='Registros Creados'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='records_failed',
            field=models.IntegerField(default=0, verbose_name='Registros Fallidos'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='records_processed',
            field=models.IntegerField(default=0, verbose_name='Registros Procesados'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='records_updated',
            field=models.IntegerField(default=0, verbose_name='Registros Actualizados'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Iniciado'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('FAILED', 'Falló'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('PRODUCTS', 'Productos'), ('STOCK', 'Stock'), ('CUSTOMERS', 'Clientes'), ('ORDERS', 'Pedidos'), ('SUPPLIERS', 'Proveedores'), ('CATEGORIES', 'Categorías'), ('BRANDS', 'Marcas'), ('FULL', 'Sincronización Completa')], max_length=20, verbose_name='Tipo de Sincronización'),
        ),
        migrations.AlterField(
            model_name='tablemapping',
            name='mapping_type',
            field=models.CharField(choices=[('PRODUCTS', 'Productos'), ('STOCK', 'Stock'), ('CUSTOMERS', 'Clientes'), ('ORDERS', 'Pedidos'), ('SUPPLIERS', 'Proveedores'), ('CATEGORIES', 'Categorías'), ('BRANDS', 'Marcas'), ('SUBCATEGORIES', 'Subcategorías')], max_length=20, verbose_name='Tipo de Mapeo'),
        ),
        migrations.CreateModel(
            name='ValidationRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(help_text='Identificador único de la regla de validación', max_length=100, verbose_name='Código de Regla')),
                ('is_active', models.BooleanField(default=True, help_text='Si la regla está activa para esta empresa', verbose_name='Activa')),
                ('description', models.CharField(blank=True, help_text='Descripción corta de la regla (opcional, para mostrar en UI)', max_length=255, verbose_name='Descripción')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminet_validation_configs', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Regla de Validación',
                'verbose_name_plural': 'Configuraciones de Reglas de Validación',
                'ordering': ['empresa', 'rule_code'],
                'unique_together': {('empresa', 'rule_code')},
            },
        ),
    ]
