# Generated by Django 4.2 on 2025-07-17 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administraNET_integration', '0002_add_use_preset_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationruleconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validationruleconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validationruleconfig',
            name='updated_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.SET_NULL, to='core.usuarioextendido'),
        ),
    ]
