# Generated by Django 4.2 on 2025-07-17 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administraNET_integration', '0003_add_validationruleconfig_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validationruleconfig',
            options={'verbose_name': 'Validation Rule Config', 'verbose_name_plural': 'Validation Rule Configs'},
        ),
        migrations.RemoveField(
            model_name='validationruleconfig',
            name='description',
        ),
        migrations.AlterField(
            model_name='validationruleconfig',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_configs', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='validationruleconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='validationruleconfig',
            name='rule_code',
            field=models.CharField(max_length=100, verbose_name='Validation Rule'),
        ),
        migrations.AlterField(
            model_name='validationruleconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
