# Generated by Django 4.2 on 2025-07-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administraNET_integration', '0005_add_timestamp_sync_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validationruleconfig',
            options={'ordering': ['-created_at'], 'verbose_name': 'Validation Rule Config', 'verbose_name_plural': 'Validation Rule Configs'},
        ),
        migrations.RenameIndex(
            model_name='synctimestamplog',
            new_name='administraN_sync_lo_ce6216_idx',
            old_name='administraNE_sync_lo_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='synctimestamplog',
            new_name='administraN_winner_9e80ea_idx',
            old_name='administraNE_winner_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='synctimestamplog',
            new_name='administraN_created_6c647e_idx',
            old_name='administraNE_created_123456_idx',
        ),
    ]
