# Generated by Django 4.2 on 2025-07-15 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioExtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('idioma', models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('pt', 'Portuguese')], default='es', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extended User',
                'verbose_name_plural': 'Extended Users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Branch Name')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Internal Code')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=64, null=True, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['empresa', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('person', 'Person'), ('company', 'Company'), ('employee', 'Employee')], default='person', max_length=16, verbose_name='Contact Type')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position/Job Title')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=32, verbose_name='Mobile')),
                ('fax', models.CharField(blank=True, max_length=32, verbose_name='Fax')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, default='Argentina', max_length=100, null=True, verbose_name='Country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255, verbose_name='Tags')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contacts/photos/', verbose_name='Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('relationship_type', models.CharField(choices=[('primary', 'Primary Contact'), ('secondary', 'Secondary Contact'), ('billing', 'Billing Contact'), ('technical', 'Technical Contact'), ('decision_maker', 'Decision Maker'), ('employee', 'Employee'), ('representative', 'Representative'), ('other', 'Other')], default='secondary', max_length=20, verbose_name='Relationship Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Contact Relationship',
                'verbose_name_plural': 'Contact Relationships',
                'ordering': ['contact', 'relationship_type'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name_es', models.CharField(blank=True, max_length=100, verbose_name='Name (Spanish)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (English)')),
                ('name_pt', models.CharField(blank=True, max_length=100, verbose_name='Name (Portuguese)')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-3 code', max_length=3, unique=True, verbose_name='ISO Code')),
                ('code_2', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 code', max_length=2, verbose_name='ISO Code (2 letters)')),
                ('phone_code', models.CharField(blank=True, help_text='International calling code', max_length=10, verbose_name='Phone Code')),
                ('currency_code', models.CharField(blank=True, help_text='ISO 4217 currency code', max_length=3, verbose_name='Currency Code')),
                ('timezone', models.CharField(blank=True, help_text='Primary timezone', max_length=50, verbose_name='Timezone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('address', models.TextField(blank=True, verbose_name='Full Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Contact Person')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Location')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Delivery Location',
                'verbose_name_plural': 'Delivery Locations',
                'ordering': ['empresa', 'branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la empresa')),
                ('identificador_fiscal', models.CharField(max_length=32, unique=True, verbose_name='CUIT/RFC/NIF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=32, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('pais', models.CharField(blank=True, max_length=64, null=True, verbose_name='País')),
                ('ciudad', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ciudad')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo')),
                ('activa', models.BooleanField(default=True, verbose_name='Empresa activa')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
            },
        ),
        migrations.CreateModel(
            name='FiscalResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre oficial de la responsabilidad fiscal', max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código oficial de la responsabilidad fiscal', max_length=10, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Código')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la responsabilidad fiscal', null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta responsabilidad fiscal está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Responsabilidad Fiscal',
                'verbose_name_plural': 'Responsabilidades Fiscales',
                'db_table': 'core_fiscal_responsibility',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal module identifier', max_length=50, unique=True, verbose_name='Module Name')),
                ('display_name', models.CharField(help_text='Human-readable module name', max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Module description', verbose_name='Description')),
                ('version', models.CharField(default='1.0.0', help_text='Module version', max_length=20, verbose_name='Version')),
                ('author', models.CharField(blank=True, help_text='Module author or development team', max_length=100, verbose_name='Author')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the module is currently active', verbose_name='Active')),
                ('is_required', models.BooleanField(default=False, help_text='Whether the module is required for system operation', verbose_name='Required')),
                ('is_core', models.BooleanField(default=False, help_text='Whether this is a core system module', verbose_name='Core Module')),
                ('dependencies', models.JSONField(default=list, help_text='List of required module dependencies', verbose_name='Dependencies')),
                ('optional_dependencies', models.JSONField(default=list, help_text='List of optional module dependencies', verbose_name='Optional Dependencies')),
                ('settings', models.JSONField(default=dict, help_text='Module-specific configuration settings', verbose_name='Settings')),
                ('permissions', models.JSONField(default=list, help_text='List of permissions provided by this module', verbose_name='Permissions')),
                ('hooks', models.JSONField(default=list, help_text='List of hooks provided by this module', verbose_name='Hooks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('last_activated', models.DateTimeField(blank=True, null=True, verbose_name='Last Activated')),
                ('last_deactivated', models.DateTimeField(blank=True, null=True, verbose_name='Last Deactivated')),
            ],
            options={
                'verbose_name': 'Module Configuration',
                'verbose_name_plural': 'Module Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Detailed description of the permission')),
                ('modulo', models.CharField(blank=True, help_text='Module to which it belongs', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['modulo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="The unique key for the configuration (e.g. 'main.site.name').", max_length=255, unique=True)),
                ('value', models.TextField(blank=True, help_text='The value of the configuration.')),
                ('description', models.CharField(blank=True, help_text='Description of what this configuration does.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this configuration is active and in use.')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(help_text='E.g. quantity, weight, volume, length, etc.', max_length=50)),
                ('ratio', models.DecimalField(decimal_places=6, help_text='Multiplicative factor with respect to the reference unit of the category.', max_digits=18)),
                ('is_reference', models.BooleanField(default=False, help_text='Marks if this is the base unit of its category.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_es', models.CharField(blank=True, max_length=100, verbose_name='Name (Spanish)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (English)')),
                ('name_pt', models.CharField(blank=True, max_length=100, verbose_name='Name (Portuguese)')),
                ('code', models.CharField(blank=True, help_text='State/province code', max_length=10, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'State/Province',
                'verbose_name_plural': 'States/Provinces',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('permisos', models.ManyToManyField(blank=True, to='core.permiso')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='moduleconfig',
            index=models.Index(fields=['is_active'], name='core_module_is_acti_6aa602_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleconfig',
            index=models.Index(fields=['is_core'], name='core_module_is_core_d3bc43_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleconfig',
            index=models.Index(fields=['is_required'], name='core_module_is_requ_8a1903_idx'),
        ),
        migrations.AddField(
            model_name='fiscalresponsibility',
            name='country',
            field=models.ForeignKey(help_text='País al que pertenece esta responsabilidad fiscal', on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_rates', to='core.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_rates', to='core.currency'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fiscal_responsibility',
            field=models.ForeignKey(blank=True, help_text='Tipo de responsabilidad fiscal de la empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fiscalresponsibility', verbose_name='Responsabilidad Fiscal'),
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_locations', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_locations', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['code'], name='core_countr_code_0b5501_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_active'], name='core_countr_is_acti_9adcd3_idx'),
        ),
        migrations.AddField(
            model_name='contactrelationship',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='contactrelationship',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='contact',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='branch',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.branch', verbose_name='Branches assigned'),
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='default_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_default', to='core.branch', verbose_name='Default branch'),
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='permisos_extra',
            field=models.ManyToManyField(blank=True, related_name='usuarios_con_permiso_directo', to='core.permiso'),
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='roles',
            field=models.ManyToManyField(blank=True, to='core.rol'),
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country'], name='core_state_country_d7dc37_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['is_active'], name='core_state_is_acti_288f98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='fiscalresponsibility',
            unique_together={('code', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency', 'date')},
        ),
        migrations.AddIndex(
            model_name='deliverylocation',
            index=models.Index(fields=['empresa', 'branch'], name='core_delive_empresa_64106a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylocation',
            index=models.Index(fields=['is_active'], name='core_delive_is_acti_924dab_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylocation',
            index=models.Index(fields=['is_default'], name='core_delive_is_defa_55e87b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrelationship',
            index=models.Index(fields=['content_type', 'object_id'], name='core_contac_content_cc02d6_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrelationship',
            index=models.Index(fields=['relationship_type'], name='core_contac_relatio_bca639_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrelationship',
            index=models.Index(fields=['is_active'], name='core_contac_is_acti_74e9bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactrelationship',
            unique_together={('contact', 'content_type', 'object_id', 'relationship_type')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['type'], name='core_contac_type_73952d_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_active'], name='core_contac_is_acti_ba050b_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='core_contac_email_800caf_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company_name'], name='core_contac_company_49bda3_idx'),
        ),
    ]
