# Generated by Django 4.2 on 2025-04-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioextendido',
            name='permisos_extra',
            field=models.ManyToManyField(blank=True, related_name='usuarios_con_permiso_directo', to='core.permiso'),
        ),
        migrations.AlterField(
            model_name='usuarioextendido',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
