# Generated by Django 4.2 on 2025-07-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Provincia o estado fiscal de la empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state', verbose_name='Provincia/Estado'),
        ),
    ]
