# Generated by Django 4.2 on 2025-07-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social'),
        ),
    ]
