# Generated by Django 4.2 on 2025-07-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=255, verbose_name='Razón Social', null=False, blank=False),
        ),
    ]
