# Generated by Django 4.2 on 2025-07-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_set_razon_social_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Official currency for all branches and products of this company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='Currency'),
        ),
    ]
