# Generated by Django 4.2 on 2025-07-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='country',
            field=models.ForeignKey(blank=True, help_text='País donde opera la empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.FileField(blank=True, help_text='Logo de la empresa (PNG, JPG, SVG, etc.)', null=True, upload_to='empresas/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='País (legacy)'),
        ),
    ]
