# Generated by Django 4.2 on 2025-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresa_country_alter_empresa_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='codigo',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
