# Generated by Django 4.2 on 2025-05-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_usuarioextendido_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioextendido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
