# Generated by Django 4.2 on 2025-06-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_activo_usuarioextendido_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioextendido',
            name='password',
            field=models.CharField(blank=True, default='!UnaNtqPljAZPjbzROke1JU6bnyCNimJwt6RJLCoJ', max_length=128),
        ),
    ]
