# Generated by Django 4.2 on 2025-06-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_usuarioextendido_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioextendido',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarioextendido',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
