# Generated by Django 4.2 on 2026-03-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_navbar_menu_global_granular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarmenuglobal',
            name='items_menu_ocultos',
            field=models.JSONField(default=dict, help_text='Diccionario app_id → lista de menu_item_id de hojas ocultas.', verbose_name='Ítems de menú ocultos por módulo'),
        ),
        migrations.AlterField(
            model_name='navbarmenuglobal',
            name='modulos_ocultos',
            field=models.JSONField(default=list, help_text='Lista de app_id (menú Synap) cuyo módulo completo no se muestra en la barra superior.', verbose_name='Módulos ocultos en navbar'),
        ),
    ]
