# Generated by Django 4.2 on 2025-06-22 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_unitofmeasure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['modulo', 'codigo'], 'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['nombre'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='usuarioextendido',
            options={'ordering': ['email'], 'verbose_name': 'Usuario Extendido', 'verbose_name_plural': 'Usuarios Extendidos'},
        ),
        migrations.AddField(
            model_name='permiso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del permiso'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='modulo',
            field=models.CharField(blank=True, help_text='Módulo al que pertenece', max_length=50),
        ),
        migrations.AddField(
            model_name='rol',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rol',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarioextendido',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarioextendido',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='usuarioextendido',
            name='uid',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
