# Generated by Django 4.2 on 2025-06-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_asignar_permisos_almacen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfiguration',
            options={'verbose_name': 'Configuración del Sistema', 'verbose_name_plural': 'Configuraciones del Sistema'},
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='country',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='default_language',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='instance_name',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='timezone',
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción de lo que hace esta configuración.', max_length=255),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si esta configuración está activa y en uso.'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='key',
            field=models.CharField(default='default.key.temp', help_text="La clave única para la configuración (ej: 'main.site.name').", max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='value',
            field=models.TextField(blank=True, help_text='El valor de la configuración.'),
        ),
    ]
