# Generated by Django 4.2 on 2025-06-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_common_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='key',
            field=models.CharField(help_text="La clave única para la configuración (ej: 'main.site.name').", max_length=255, unique=True),
        ),
    ]
