# Generated by Django 4.x on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_backupsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupsettings",
            name="bootstrap_passphrase_encrypted",
            field=models.TextField(
                blank=True,
                default="",
                help_text=(
                    "Se usa para cifrar .env en cada full. Guarde una copia fuera de Synap "
                    "(gestor de contraseñas). Sin ella el restore no puede descifrar env.enc."
                ),
                verbose_name="Frase de cifrado del paquete .env (bootstrap)",
            ),
        ),
    ]
