# Generated by Django 4.x on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_backupsettings_bootstrap_passphrase"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupsettings",
            name="notify_email_enabled",
            field=models.BooleanField(
                default=False,
                verbose_name="Notificar por correo el resultado del backup",
            ),
        ),
        migrations.AddField(
            model_name="backupsettings",
            name="notify_email_to",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Uno o más emails separados por coma, punto y coma o salto de línea.",
                verbose_name="Destinatarios de notificación",
            ),
        ),
        migrations.AddField(
            model_name="backupsettings",
            name="notify_on_failure",
            field=models.BooleanField(
                default=True,
                verbose_name="Avisar cuando el backup falla",
            ),
        ),
        migrations.AddField(
            model_name="backupsettings",
            name="notify_on_partial",
            field=models.BooleanField(
                default=True,
                verbose_name="Avisar en fallo parcial o SFTP fallido",
            ),
        ),
        migrations.AddField(
            model_name="backupsettings",
            name="notify_on_success",
            field=models.BooleanField(
                default=False,
                verbose_name="Avisar también cuando el backup termina OK",
            ),
        ),
    ]
