# Generated by Django 4.2 on 2025-06-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_site_url_system_config'),
        ('core', '0018_add_tiendanube_permissions'),
    ]

    operations = [
    ]
