# Generated by Django 4.2 on 2025-07-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20250624_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'Exchange Rate', 'verbose_name_plural': 'Exchange Rates'},
        ),
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['modulo', 'codigo'], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['nombre'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='systemconfiguration',
            options={'verbose_name': 'System Configuration', 'verbose_name_plural': 'System Configurations'},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'verbose_name': 'Unit of Measure', 'verbose_name_plural': 'Units of Measure'},
        ),
        migrations.AlterModelOptions(
            name='usuarioextendido',
            options={'ordering': ['email'], 'verbose_name': 'Extended User', 'verbose_name_plural': 'Extended Users'},
        ),
        migrations.AlterField(
            model_name='permiso',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detailed description of the permission'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='modulo',
            field=models.CharField(blank=True, help_text='Module to which it belongs', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='description',
            field=models.CharField(blank=True, help_text='Description of what this configuration does.', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if this configuration is active and in use.'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='key',
            field=models.CharField(help_text="The unique key for the configuration (e.g. 'main.site.name').", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='value',
            field=models.TextField(blank=True, help_text='The value of the configuration.'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='category',
            field=models.CharField(help_text='E.g. quantity, weight, volume, length, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='is_reference',
            field=models.BooleanField(default=False, help_text='Marks if this is the base unit of its category.'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='ratio',
            field=models.DecimalField(decimal_places=6, help_text='Multiplicative factor with respect to the reference unit of the category.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='usuarioextendido',
            name='idioma',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('pt', 'Portuguese')], default='es', max_length=10),
        ),
    ]
