# Generated by Django 4.2 on 2025-07-02 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_currency_options_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la empresa')),
                ('identificador_fiscal', models.CharField(max_length=32, unique=True, verbose_name='CUIT/RFC/NIF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=32, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('pais', models.CharField(blank=True, max_length=64, null=True, verbose_name='País')),
                ('ciudad', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ciudad')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo')),
                ('activa', models.BooleanField(default=True, verbose_name='Empresa activa')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
    ]
