# Generated by Django 4.2 on 2025-07-06 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('address', models.TextField(blank=True, verbose_name='Full Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Contact Person')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Location')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_locations', to='core.branch', verbose_name='Branch')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_locations', to='core.empresa', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Delivery Location',
                'verbose_name_plural': 'Delivery Locations',
                'ordering': ['empresa', 'branch', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverylocation',
            index=models.Index(fields=['empresa', 'branch'], name='core_delive_empresa_64106a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylocation',
            index=models.Index(fields=['is_active'], name='core_delive_is_acti_924dab_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylocation',
            index=models.Index(fields=['is_default'], name='core_delive_is_defa_55e87b_idx'),
        ),
    ]
