# Generated by Django 4.2 on 2025-07-07 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0023_add_delivery_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('person', 'Person'), ('company', 'Company'), ('employee', 'Employee')], default='person', max_length=16, verbose_name='Contact Type')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position/Job Title')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=32, verbose_name='Mobile')),
                ('fax', models.CharField(blank=True, max_length=32, verbose_name='Fax')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255, verbose_name='Tags')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contacts/photos/', verbose_name='Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('relationship_type', models.CharField(choices=[('primary', 'Primary Contact'), ('secondary', 'Secondary Contact'), ('billing', 'Billing Contact'), ('technical', 'Technical Contact'), ('decision_maker', 'Decision Maker'), ('employee', 'Employee'), ('representative', 'Representative'), ('other', 'Other')], default='secondary', max_length=20, verbose_name='Relationship Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.contact', verbose_name='Contact')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Contact Relationship',
                'verbose_name_plural': 'Contact Relationships',
                'ordering': ['contact', 'relationship_type'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['type'], name='core_contac_type_73952d_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_active'], name='core_contac_is_acti_ba050b_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='core_contac_email_800caf_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company_name'], name='core_contac_company_49bda3_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrelationship',
            index=models.Index(fields=['content_type', 'object_id'], name='core_contac_content_cc02d6_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrelationship',
            index=models.Index(fields=['relationship_type'], name='core_contac_relatio_bca639_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrelationship',
            index=models.Index(fields=['is_active'], name='core_contac_is_acti_74e9bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactrelationship',
            unique_together={('contact', 'content_type', 'object_id', 'relationship_type')},
        ),
    ]
