# Generated by Django 4.2 on 2025-07-07 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_contact_address_alter_contact_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name_es', models.CharField(blank=True, max_length=100, verbose_name='Name (Spanish)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (English)')),
                ('name_pt', models.CharField(blank=True, max_length=100, verbose_name='Name (Portuguese)')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-3 code', max_length=3, unique=True, verbose_name='ISO Code')),
                ('code_2', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 code', max_length=2, verbose_name='ISO Code (2 letters)')),
                ('phone_code', models.CharField(blank=True, help_text='International calling code', max_length=10, verbose_name='Phone Code')),
                ('currency_code', models.CharField(blank=True, help_text='ISO 4217 currency code', max_length=3, verbose_name='Currency Code')),
                ('timezone', models.CharField(blank=True, help_text='Primary timezone', max_length=50, verbose_name='Timezone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_es', models.CharField(blank=True, max_length=100, verbose_name='Name (Spanish)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (English)')),
                ('name_pt', models.CharField(blank=True, max_length=100, verbose_name='Name (Portuguese)')),
                ('code', models.CharField(blank=True, help_text='State/province code', max_length=10, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'State/Province',
                'verbose_name_plural': 'States/Provinces',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['code'], name='core_countr_code_0b5501_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_active'], name='core_countr_is_acti_9adcd3_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country'], name='core_state_country_d7dc37_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['is_active'], name='core_state_is_acti_288f98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'name')},
        ),
    ]
