# Generated by Django 4.2 on 2025-07-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_country_state_country_core_countr_code_0b5501_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal module identifier', max_length=50, unique=True, verbose_name='Module Name')),
                ('display_name', models.CharField(help_text='Human-readable module name', max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Module description', verbose_name='Description')),
                ('version', models.CharField(default='1.0.0', help_text='Module version', max_length=20, verbose_name='Version')),
                ('author', models.CharField(blank=True, help_text='Module author or development team', max_length=100, verbose_name='Author')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the module is currently active', verbose_name='Active')),
                ('is_required', models.BooleanField(default=False, help_text='Whether the module is required for system operation', verbose_name='Required')),
                ('is_core', models.BooleanField(default=False, help_text='Whether this is a core system module', verbose_name='Core Module')),
                ('dependencies', models.JSONField(default=list, help_text='List of required module dependencies', verbose_name='Dependencies')),
                ('optional_dependencies', models.JSONField(default=list, help_text='List of optional module dependencies', verbose_name='Optional Dependencies')),
                ('settings', models.JSONField(default=dict, help_text='Module-specific configuration settings', verbose_name='Settings')),
                ('permissions', models.JSONField(default=list, help_text='List of permissions provided by this module', verbose_name='Permissions')),
                ('hooks', models.JSONField(default=list, help_text='List of hooks provided by this module', verbose_name='Hooks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('last_activated', models.DateTimeField(blank=True, null=True, verbose_name='Last Activated')),
                ('last_deactivated', models.DateTimeField(blank=True, null=True, verbose_name='Last Deactivated')),
            ],
            options={
                'verbose_name': 'Module Configuration',
                'verbose_name_plural': 'Module Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='moduleconfig',
            index=models.Index(fields=['is_active'], name='core_module_is_acti_6aa602_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleconfig',
            index=models.Index(fields=['is_core'], name='core_module_is_core_d3bc43_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleconfig',
            index=models.Index(fields=['is_required'], name='core_module_is_requ_8a1903_idx'),
        ),
    ]
