# Generated by Django 4.2 on 2025-07-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_module_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.empresa', verbose_name='Company'),
        ),
    ]
