# Generated by Django 4.2 on 2025-07-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_contact_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioextendido',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.branch', verbose_name='Branches assigned'),
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='default_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_default', to='core.branch', verbose_name='Default branch'),
        ),
    ]
