# Generated by Django 4.2 on 2025-07-31 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_empresa_country_alter_empresa_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('agent_type', models.CharField(choices=[('supervisor', 'Supervisor General'), ('facturacion', 'Facturación'), ('configuracion', 'Configuración'), ('ventas', 'Ventas'), ('inventario', 'Inventario'), ('multimodal', 'Multimodal'), ('voz', 'Voz')], max_length=20, verbose_name='Tipo de Agente')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('priority', models.IntegerField(default=1, verbose_name='Prioridad')),
                ('model_name', models.CharField(default='gpt-4o', max_length=100, verbose_name='Modelo IA')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperatura')),
                ('max_tokens', models.IntegerField(default=1000, verbose_name='Máximo Tokens')),
                ('system_prompt', models.TextField(verbose_name='Prompt del Sistema')),
                ('context_rules', models.JSONField(blank=True, default=dict, verbose_name='Reglas de Contexto')),
                ('total_conversations', models.IntegerField(default=0, verbose_name='Total Conversaciones')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='Tasa de Éxito')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name='Tiempo Respuesta Promedio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Agente IA',
                'verbose_name_plural': 'Agentes IA',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Usuario'), ('ai', 'IA'), ('agent', 'Agente'), ('system', 'Sistema')], max_length=10, verbose_name='Tipo de Mensaje')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('content_processed', models.TextField(blank=True, verbose_name='Contenido Procesado')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Adjuntos')),
                ('ai_agent_used', models.CharField(blank=True, max_length=50, verbose_name='Agente IA Utilizado')),
                ('ai_confidence', models.FloatField(default=0.0, verbose_name='Confianza IA')),
                ('ai_processing_time', models.FloatField(default=0.0, verbose_name='Tiempo Procesamiento IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Lectura')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En Progreso'), ('waiting_customer', 'Esperando Cliente'), ('waiting_agent', 'Esperando Agente'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=20, verbose_name='Estado')),
                ('channel', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('voice', 'Voz')], default='web', max_length=10, verbose_name='Canal')),
                ('ai_confidence', models.FloatField(default=0.0, verbose_name='Confianza IA')),
                ('ai_resolved', models.BooleanField(default=False, verbose_name='Resuelto por IA')),
                ('escalation_reason', models.TextField(blank=True, verbose_name='Razón de Escalamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Resolución')),
                ('sla_hours', models.IntegerField(default=24, verbose_name='SLA Horas')),
                ('sla_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline SLA')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Agente Asignado')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='Sucursal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_assign_tickets', models.BooleanField(default=True, verbose_name='Asignación Automática')),
                ('enable_ai_responses', models.BooleanField(default=True, verbose_name='Respuestas IA Habilitadas')),
                ('enable_voice_input', models.BooleanField(default=True, verbose_name='Entrada de Voz Habilitada')),
                ('enable_file_upload', models.BooleanField(default=True, verbose_name='Subida de Archivos Habilitada')),
                ('ai_confidence_threshold', models.FloatField(default=0.7, verbose_name='Umbral Confianza IA')),
                ('max_ai_conversations', models.IntegerField(default=5, verbose_name='Máximo Conversaciones IA')),
                ('escalation_keywords', models.JSONField(blank=True, default=list, verbose_name='Palabras Clave Escalamiento')),
                ('web_enabled', models.BooleanField(default=True, verbose_name='Web Habilitado')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email Habilitado')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='WhatsApp Habilitado')),
                ('voice_enabled', models.BooleanField(default=True, verbose_name='Voz Habilitado')),
                ('max_file_size', models.IntegerField(default=10, verbose_name='Tamaño Máximo Archivo (MB)')),
                ('allowed_file_types', models.JSONField(blank=True, default=list, verbose_name='Tipos de Archivo Permitidos')),
                ('default_sla_hours', models.IntegerField(default=24, verbose_name='SLA Horas por Defecto')),
                ('business_hours', models.JSONField(blank=True, default=dict, verbose_name='Horarios de Negocio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Soporte',
                'verbose_name_plural': 'Configuraciones de Soporte',
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('file_path', models.CharField(max_length=500, verbose_name='Ruta del Archivo')),
                ('file_size', models.IntegerField(verbose_name='Tamaño del Archivo')),
                ('file_type', models.CharField(max_length=100, verbose_name='Tipo de Archivo')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('ocr_text', models.TextField(blank=True, verbose_name='Texto OCR')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, verbose_name='Análisis IA')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Subida')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_attachments', to='support_ai.conversation', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Adjunto de Soporte',
                'verbose_name_plural': 'Adjuntos de Soporte',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='support_ai.supportticket', verbose_name='Ticket'),
        ),
        migrations.CreateModel(
            name='SupportMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('total_tickets', models.IntegerField(default=0, verbose_name='Total Tickets')),
                ('resolved_tickets', models.IntegerField(default=0, verbose_name='Tickets Resueltos')),
                ('ai_resolved_tickets', models.IntegerField(default=0, verbose_name='Tickets Resueltos por IA')),
                ('escalated_tickets', models.IntegerField(default=0, verbose_name='Tickets Escalados')),
                ('avg_resolution_time', models.FloatField(default=0.0, verbose_name='Tiempo Resolución Promedio')),
                ('avg_first_response_time', models.FloatField(default=0.0, verbose_name='Tiempo Primera Respuesta Promedio')),
                ('customer_satisfaction', models.FloatField(default=0.0, verbose_name='Satisfacción del Cliente')),
                ('total_ratings', models.IntegerField(default=0, verbose_name='Total Calificaciones')),
                ('ai_accuracy', models.FloatField(default=0.0, verbose_name='Precisión IA')),
                ('ai_usage_rate', models.FloatField(default=0.0, verbose_name='Tasa de Uso IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Métrica de Soporte',
                'verbose_name_plural': 'Métricas de Soporte',
                'ordering': ['-date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
