# Generated by Django 4.2 on 2025-07-31 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support_ai', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('frustration_pattern', 'Patrón de Frustración'), ('feature_request', 'Solicitud de Funcionalidad'), ('usage_trend', 'Tendencia de Uso'), ('support_optimization', 'Optimización de Soporte'), ('product_improvement', 'Mejora de Producto')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_evidence', models.JSONField()),
                ('impact_score', models.FloatField(default=0.0)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20)),
                ('is_actioned', models.BooleanField(default=False)),
                ('action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insight de Negocio',
                'verbose_name_plural': 'Insights de Negocio',
            },
        ),
        migrations.CreateModel(
            name='ContinuousLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('conversation', 'Conversación'), ('ticket', 'Ticket'), ('feedback', 'Feedback'), ('correction', 'Corrección')], max_length=50)),
                ('source_id', models.CharField(max_length=100)),
                ('learning_data', models.JSONField()),
                ('agent_used', models.CharField(max_length=100)),
                ('confidence_before', models.FloatField(default=0.0)),
                ('confidence_after', models.FloatField(default=0.0)),
                ('improvement_score', models.FloatField(default=0.0)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aprendizaje Continuo',
                'verbose_name_plural': 'Aprendizaje Continuo',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('facturacion', 'Facturación'), ('configuracion', 'Configuración'), ('ventas', 'Ventas'), ('inventario', 'Inventario'), ('general', 'General')], max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ai_generated', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Base de Conocimientos',
                'verbose_name_plural': 'Bases de Conocimientos',
            },
        ),
        migrations.CreateModel(
            name='OnboardingFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user_type', models.CharField(choices=[('new_customer', 'Cliente Nuevo'), ('advanced_customer', 'Cliente Avanzado'), ('new_agent', 'Agente Nuevo'), ('experienced_agent', 'Agente Experimentado')], max_length=50)),
                ('steps', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Flujo de Onboarding',
                'verbose_name_plural': 'Flujos de Onboarding',
            },
        ),
        migrations.CreateModel(
            name='ProactiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('license_expiry', 'Expiración de Licencia'), ('usage_drop', 'Caída de Uso'), ('error_pattern', 'Patrón de Errores'), ('feature_adoption', 'Adopción de Funcionalidad'), ('support_needed', 'Soporte Necesario')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta Proactiva',
                'verbose_name_plural': 'Alertas Proactivas',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('expert', 'Experto')], default='beginner', max_length=50)),
                ('preferred_channel', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('voice', 'Voz')], default='web', max_length=50)),
                ('communication_style', models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('technical', 'Técnico'), ('friendly', 'Amigable')], default='friendly', max_length=50)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfiles de Clientes',
            },
        ),
        migrations.CreateModel(
            name='AgentCoaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('conversation_id', models.CharField(max_length=100)),
                ('feedback_type', models.CharField(choices=[('tone', 'Tono de Voz'), ('speed', 'Velocidad'), ('empathy', 'Empatía'), ('technical', 'Conocimiento Técnico'), ('resolution', 'Resolución')], max_length=50)),
                ('feedback_message', models.TextField()),
                ('suggested_improvement', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_implemented', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coaching de Agente',
                'verbose_name_plural': 'Coaching de Agentes',
            },
        ),
    ]
