# Generated by Django 4.2 on 2025-08-04 18:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support_ai', '0003_businessinsight_continuouslearning_knowledgebase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('trigger_type', models.CharField(choices=[('ticket_created', 'Ticket Creado'), ('priority_changed', 'Prioridad Cambiada'), ('status_changed', 'Estado Cambiado'), ('time_elapsed', 'Tiempo Transcurrido'), ('ai_confidence_low', 'Confianza IA Baja'), ('sentiment_negative', 'Sentimiento Negativo')], max_length=20, verbose_name='Tipo de Trigger')),
                ('trigger_conditions', models.JSONField(default=dict, verbose_name='Condiciones de Trigger')),
                ('actions', models.JSONField(default=list, verbose_name='Acciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('execution_order', models.PositiveIntegerField(default=1, verbose_name='Orden de Ejecución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Flujo de Trabajo Automatizado',
                'verbose_name_plural': 'Flujos de Trabajo Automatizados',
                'ordering': ['execution_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('priority_threshold', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], max_length=10, verbose_name='Umbral de Prioridad')),
                ('ai_confidence_threshold', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Umbral Confianza IA')),
                ('sentiment_threshold', models.FloatField(default=-0.3, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)], verbose_name='Umbral Sentimiento')),
                ('response_time_threshold', models.PositiveIntegerField(default=60, verbose_name='Umbral Tiempo Respuesta (minutos)')),
                ('escalation_type', models.CharField(choices=[('human_agent', 'Agente Humano'), ('supervisor', 'Supervisor'), ('specialist', 'Especialista'), ('emergency', 'Emergencia')], max_length=20, verbose_name='Tipo de Escalamiento')),
                ('target_department', models.CharField(blank=True, max_length=100, verbose_name='Departamento Objetivo')),
                ('notification_channels', models.JSONField(default=list, verbose_name='Canales de Notificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('auto_trigger', models.BooleanField(default=True, verbose_name='Activación Automática')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Regla de Escalamiento',
                'verbose_name_plural': 'Reglas de Escalamiento',
            },
        ),
        migrations.CreateModel(
            name='IntegrationWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('url', models.URLField(verbose_name='URL del Webhook')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], default='POST', max_length=10, verbose_name='Método HTTP')),
                ('headers', models.JSONField(default=dict, verbose_name='Headers')),
                ('payload_template', models.TextField(verbose_name='Plantilla de Payload')),
                ('events', models.JSONField(default=list, verbose_name='Eventos')),
                ('secret_key', models.CharField(blank=True, max_length=255, verbose_name='Clave Secreta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Éxitos')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='Fallos')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='Último Activado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Webhook de Integración',
                'verbose_name_plural': 'Webhooks de Integración',
            },
        ),
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('tags', models.JSONField(default=list, verbose_name='Etiquetas')),
                ('subject_template', models.CharField(max_length=200, verbose_name='Plantilla de Asunto')),
                ('description_template', models.TextField(verbose_name='Plantilla de Descripción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad por Defecto')),
                ('sla_hours', models.PositiveIntegerField(default=24, verbose_name='SLA Horas')),
                ('available_variables', models.JSONField(default=list, verbose_name='Variables Disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Uso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de Ticket',
                'verbose_name_plural': 'Plantillas de Tickets',
            },
        ),
        migrations.RemoveField(
            model_name='supportconfiguration',
            name='company',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='supportmetrics',
            unique_together={('date',)},
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('ticket_updates', models.BooleanField(default=True)),
                ('new_messages', models.BooleanField(default=True)),
                ('system_alerts', models.BooleanField(default=True)),
                ('reminders', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Inmediata'), ('hourly', 'Cada hora'), ('daily', 'Diaria'), ('weekly', 'Semanal')], default='immediate', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Usuario',
                'verbose_name_plural': 'Preferencias de Usuario',
            },
        ),
        migrations.CreateModel(
            name='PredictiveAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('predicted_ticket_volume', models.PositiveIntegerField(verbose_name='Volumen Predicho de Tickets')),
                ('predicted_escalation_rate', models.FloatField(verbose_name='Tasa Predicha de Escalamiento')),
                ('predicted_resolution_time', models.FloatField(verbose_name='Tiempo Predicho de Resolución')),
                ('seasonal_factor', models.FloatField(default=1.0, verbose_name='Factor Estacional')),
                ('trend_factor', models.FloatField(default=1.0, verbose_name='Factor de Tendencia')),
                ('external_factors', models.JSONField(default=dict, verbose_name='Factores Externos')),
                ('accuracy_score', models.FloatField(default=0.0, verbose_name='Puntuación de Precisión')),
                ('confidence_interval', models.FloatField(default=0.0, verbose_name='Intervalo de Confianza')),
                ('model_version', models.CharField(max_length=20, verbose_name='Versión del Modelo')),
                ('features_used', models.JSONField(default=list, verbose_name='Características Utilizadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
            ],
            options={
                'verbose_name': 'Analytics Predictivo',
                'verbose_name_plural': 'Analytics Predictivos',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ticket_created', 'Ticket Creado'), ('ticket_updated', 'Ticket Actualizado'), ('ticket_assigned', 'Ticket Asignado'), ('message_received', 'Mensaje Recibido'), ('ticket_resolved', 'Ticket Resuelto'), ('system_alert', 'Alerta del Sistema'), ('reminder', 'Recordatorio')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('first_contact', 'Primer Contacto'), ('ticket_created', 'Ticket Creado'), ('ai_interaction', 'Interacción IA'), ('human_escalation', 'Escalamiento Humano'), ('resolution', 'Resolución'), ('feedback', 'Feedback'), ('follow_up', 'Seguimiento')], max_length=50, verbose_name='Tipo de Evento')),
                ('event_data', models.JSONField(default=dict, verbose_name='Datos del Evento')),
                ('ai_insights', models.JSONField(blank=True, default=dict, verbose_name='Insights IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journey_events', to='support_ai.conversation', verbose_name='Conversación')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_events', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journey_events', to='support_ai.supportticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Evento del Journey del Cliente',
                'verbose_name_plural': 'Eventos del Journey del Cliente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='supportmetrics',
            name='company',
        ),
        migrations.CreateModel(
            name='CustomerSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación General')),
                ('response_time_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Tiempo de Respuesta')),
                ('solution_quality_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Calidad de Solución')),
                ('agent_helpfulness_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Utilidad del Agente')),
                ('sentiment_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)], verbose_name='Puntuación de Sentimiento')),
                ('sentiment_label', models.CharField(choices=[('very_negative', 'Muy Negativo'), ('negative', 'Negativo'), ('neutral', 'Neutral'), ('positive', 'Positivo'), ('very_positive', 'Muy Positivo')], max_length=20, verbose_name='Etiqueta de Sentimiento')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, verbose_name='Análisis IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_ratings', to='support_ai.supportticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Satisfacción del Cliente',
                'verbose_name_plural': 'Satisfacciones de Clientes',
                'unique_together': {('ticket', 'customer')},
            },
        ),
    ]
