# Generated by Django 4.2 on 2025-08-04 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support_ai', '0004_automatedworkflow_escalationrule_integrationwebhook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('claude-3-haiku', 'Claude 3 Haiku'), ('claude-3-sonnet', 'Claude 3 Sonnet')], default='gpt-4o-mini', max_length=50, verbose_name='Modelo de IA')),
                ('daily_cost_limit', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Límite de Costo Diario')),
                ('auto_assignment', models.BooleanField(default=True, verbose_name='Asignación Automática de Tickets')),
                ('max_response_time', models.PositiveIntegerField(default=24, verbose_name='Tiempo Máximo de Respuesta (horas)')),
                ('enable_cache', models.BooleanField(default=True, verbose_name='Caché Habilitado')),
                ('cache_ttl', models.PositiveIntegerField(default=3600, verbose_name='TTL de Caché (segundos)')),
                ('enable_metrics', models.BooleanField(default=True, verbose_name='Métricas Habilitadas')),
                ('metrics_retention_days', models.PositiveIntegerField(default=90, verbose_name='Retención de Métricas (días)')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, verbose_name='Máximo Intentos de Login')),
                ('session_timeout', models.PositiveIntegerField(default=480, verbose_name='Timeout de Sesión (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('fr', 'Français')], default='es', max_length=10, verbose_name='Idioma')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='light', max_length=10, verbose_name='Tema')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notificaciones Habilitadas')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Notificaciones Push')),
                ('data_collection', models.BooleanField(default=True, verbose_name='Recolección de Datos')),
                ('analytics_tracking', models.BooleanField(default=True, verbose_name='Seguimiento Analítico')),
                ('font_size', models.CharField(choices=[('small', 'Pequeña'), ('medium', 'Mediana'), ('large', 'Grande')], default='medium', max_length=10, verbose_name='Tamaño de Fuente')),
                ('high_contrast', models.BooleanField(default=False, verbose_name='Alto Contraste')),
                ('screen_reader', models.BooleanField(default=False, verbose_name='Lector de Pantalla')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuario',
            },
        ),
    ]
