# Generated by Django 4.2 on 2025-08-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_ai', '0005_systemsettings_usersettings'),
    ]

    operations = [
    ]
