# Generated by Django 4.2 on 2025-07-22 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0012_remove_client_last_synced_with_adminet_clienttag_and_more'),
        ('core', '0006_empresa_country_alter_empresa_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('report_type', models.CharField(choices=[('aging', 'Aging'), ('balance', 'Balance'), ('sales', 'Sales'), ('collections', 'Collections'), ('custom', 'Custom')], max_length=32)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='financial_reports/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to='core.empresa')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_limit_logs', to='sales.client')),
            ],
        ),
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('payment', 'Payment'), ('advance', 'Advance'), ('adjustment', 'Adjustment')], max_length=32)),
                ('document_number', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_receivable', to='sales.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to='core.empresa')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.invoice')),
            ],
        ),
    ]
