# Generated by Django 4.2 on 2025-09-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('source_table', models.CharField(max_length=64)),
                ('entry_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], max_length=10)),
                ('date', models.DateField()),
                ('currency', models.CharField(default='ARS', max_length=8)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_center', models.CharField(blank=True, max_length=64, null=True)),
                ('counterparty_id', models.CharField(blank=True, max_length=64, null=True)),
                ('source_id', models.CharField(max_length=64)),
                ('source_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Financial Entry',
                'verbose_name_plural': 'Financial Entries',
            },
        ),
        migrations.AddIndex(
            model_name='financialentry',
            index=models.Index(fields=['date'], name='finance_fin_date_7e2f18_idx'),
        ),
        migrations.AddIndex(
            model_name='financialentry',
            index=models.Index(fields=['entry_type', 'date'], name='finance_fin_entry_t_eca922_idx'),
        ),
        migrations.AddIndex(
            model_name='financialentry',
            index=models.Index(fields=['source_updated_at'], name='finance_fin_source__7bada8_idx'),
        ),
    ]
