# Generated by Django 4.2 on 2025-05-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuarioextendido_permisos_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioextendido',
            name='idioma',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('pt', 'Portugués')], default='es', max_length=10),
        ),
    ]
