# Generated by Django 4.2 on 2026-08-27 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MtrixConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_empresa', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Base empresa')),
                ('fecha_personalizada', models.BooleanField(default=False, verbose_name='Fecha personalizada')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('dias_a_procesar', models.PositiveIntegerField(default=5, verbose_name='Días a procesar')),
                ('codigo_proveedor_principal', models.CharField(blank=True, help_text='Vacío = todos. Lista separada por comas, ej. 23,29,31', max_length=255, verbose_name='Códigos de proveedor')),
                ('cnpj_fornecedor', models.CharField(blank=True, max_length=20, verbose_name='CNPJ fornecedor')),
                ('pvnf', models.BooleanField(default=False, help_text='Si está inactivo, solo punto_venta.cont = Si (VD).', verbose_name='Incluir todos los puntos de venta')),
                ('multiplicador_cantidad', models.IntegerField(default=1, verbose_name='Multiplicador cantidad')),
                ('multiplicador_precio', models.IntegerField(default=1, verbose_name='Multiplicador precio')),
                ('version_layout', models.PositiveIntegerField(default=19, verbose_name='Versión layout')),
                ('sftp_host', models.CharField(blank=True, max_length=255, verbose_name='Host SFTP')),
                ('sftp_port', models.PositiveIntegerField(default=22, verbose_name='Puerto SFTP')),
                ('sftp_user', models.CharField(blank=True, max_length=128, verbose_name='Usuario SFTP')),
                ('sftp_remote_path', models.CharField(blank=True, max_length=512, verbose_name='Path remoto SFTP')),
                ('sftp_password_encrypted', models.TextField(blank=True, verbose_name='Contraseña SFTP cifrada')),
                ('sftp_key_path', models.CharField(blank=True, max_length=512, verbose_name='Ruta clave SFTP')),
                ('sftp_enviar_automatico', models.BooleanField(default=False, verbose_name='Enviar por SFTP en cron')),
                ('programador_activo', models.BooleanField(default=False, verbose_name='Programador activo')),
                ('schedule_json', models.JSONField(blank=True, default=list, verbose_name='Programación')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Mtrix',
                'verbose_name_plural': 'Configuraciones Mtrix',
            },
        ),
        migrations.CreateModel(
            name='MtrixJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_empresa', models.CharField(db_index=True, max_length=64, verbose_name='Base empresa')),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('running', 'En curso'), ('completed', 'Completado'), ('failed', 'Fallido')], db_index=True, default='queued', max_length=16, verbose_name='Estado')),
                ('origen', models.CharField(choices=[('ui', 'Interfaz'), ('cron', 'Programado')], default='ui', max_length=8, verbose_name='Origen')),
                ('fecha_desde', models.DateField(blank=True, null=True, verbose_name='Desde')),
                ('fecha_hasta', models.DateField(blank=True, null=True, verbose_name='Hasta')),
                ('triggered_by', models.CharField(blank=True, max_length=64, verbose_name='Disparado por')),
                ('progreso', models.CharField(blank=True, max_length=200, verbose_name='Progreso')),
                ('error_summary', models.TextField(blank=True, verbose_name='Error')),
                ('log_text', models.TextField(blank=True, verbose_name='Log')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Mtrix',
                'verbose_name_plural': 'Jobs Mtrix',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MtrixArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CI', 'CI'), ('PD', 'PD'), ('ES', 'ES'), ('VD', 'VD'), ('FV', 'FV')], max_length=4, verbose_name='Tipo')),
                ('codigo_proveedor', models.CharField(blank=True, max_length=32, verbose_name='Proveedor')),
                ('filename', models.CharField(max_length=255, verbose_name='Nombre archivo')),
                ('relative_path', models.CharField(max_length=512, verbose_name='Ruta relativa')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='Tamaño')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Filas')),
                ('sftp_status', models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Enviado'), ('failed', 'Fallido'), ('skipped', 'Omitido')], default='pending', max_length=16, verbose_name='Estado SFTP')),
                ('sftp_message', models.CharField(blank=True, max_length=500, verbose_name='Mensaje SFTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='mtrix.mtrixjob', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Artefacto Mtrix',
                'verbose_name_plural': 'Artefactos Mtrix',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mtrixjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('base_empresa',), name='mtrix_job_un_activo_por_empresa'),
        ),
    ]
