# Generated by Django 4.2 on 2026-02-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_type",
                    models.CharField(
                        default="caso", max_length=32, verbose_name="Tipo (caso|codigo)"
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="ID fuente (caso, artefacto)",
                    ),
                ),
                ("text", models.TextField(verbose_name="Texto del chunk")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_chunks",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunk conocimiento",
                "verbose_name_plural": "Chunks conocimiento",
                "db_table": "support_knowledge_chunk",
            },
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["company", "chunk_type"], name="support_kno_company_f435ca_idx"
            ),
        ),
    ]
