# Generated by Django 4.2 on 2026-02-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_rag_embedding_and_metadata"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="knowledgechunk",
            name="support_kno_company_f435ca_idx",
        ),
        migrations.AlterField(
            model_name="knowledgechunk",
            name="source_type",
            field=models.CharField(
                default="caso",
                max_length=32,
                verbose_name="Tipo fuente (caso, codigo, human_note, resolved_case)",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["company", "source_type"], name="support_kno_company_1acfdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["content_hash"], name="support_kno_content_2f1db2_idx"
            ),
        ),
    ]
