# Generated by Django 4.2 on 2026-07-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.BinaryField(unique=True)),
                ('public_key', models.BinaryField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('base_empresa', models.CharField(db_index=True, max_length=128)),
                ('id_usuario', models.PositiveIntegerField()),
                ('device_label', models.CharField(default='', max_length=128)),
                ('password_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Credencial WebAuthn',
                'verbose_name_plural': 'Credenciales WebAuthn',
                'db_table': 'login_webauthn_credential',
            },
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['base_empresa', 'id_usuario'], name='login_webau_base_em_9fd254_idx'),
        ),
    ]
