# Generated by Django 4.2 on 2025-07-06 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_delivery_location'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='delivery_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deliverylocation', verbose_name='Delivery Location'),
        ),
    ]
