# Generated by Django 4.2 on 2025-07-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_use_core_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approval_workflow',
            field=models.ForeignKey(blank=True, help_text='Approval workflow assigned to this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='purchases.approvalworkflow', verbose_name='Approval Workflow'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='current_approval_level',
            field=models.IntegerField(blank=True, help_text='Current approval level number', null=True, verbose_name='Current Approval Level'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Total amount of the request (auto-calculated)', max_digits=15, null=True, verbose_name='Total Amount'),
        ),
    ]
