# Generated by Django 4.2 on 2025-07-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_delivery_location'),
        ('purchases', '0003_purchaserequest_approval_workflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approvals_received',
            field=models.IntegerField(default=0, help_text='Number of approvals received so far', verbose_name='Approvals Received'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deliverylocation', verbose_name='Delivery Location'),
        ),
    ]
