# Generated by Django 4.2 on 2025-07-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchaserequest_approvals_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Inspection'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned to Supplier')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
