# Generated by Django 4.2 on 2025-07-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchasereceipt_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='supplier',
            name='purchases_s_name_df4648_idx',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, help_text='Internal business entity code', max_length=20, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, default='Argentina', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_type'], name='purchases_s_supplie_bd15ed_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_approved'], name='purchases_s_is_appr_8c54f4_idx'),
        ),
    ]
