# Generated by Django 4.2 on 2025-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_remove_supplier_purchases_s_name_df4648_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='document_number',
            field=models.CharField(blank=True, help_text='DNI, CUIT, or other identification document', max_length=50, verbose_name='Document Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='company', max_length=16, verbose_name='Supplier Type'),
        ),
    ]
