# Generated by Django 4.2 on 2026-07-03 02:51

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_update_checkpoint_informes_vn'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_empresa', models.CharField(db_index=True, max_length=64, verbose_name='base empresa')),
                ('id_usuario', models.IntegerField(db_index=True, verbose_name='usuario (vendedor)')),
                ('idcliente', models.IntegerField(blank=True, null=True, verbose_name='cliente')),
                ('lista_id', models.IntegerField(default=1, verbose_name='lista de precio')),
                ('id_deposito', models.IntegerField(default=1, verbose_name='depósito')),
                ('iva_incluido', models.BooleanField(default=True, verbose_name='IVA incluido')),
                ('tipo_comprobante', models.CharField(choices=[('PED', 'Pedido'), ('PRE', 'Presupuesto')], default='PED', max_length=3, verbose_name='tipo comprobante')),
                ('estado', models.CharField(choices=[('borrador', 'borrador'), ('confirmado', 'confirmado')], db_index=True, default='borrador', max_length=16, verbose_name='estado')),
                ('descuento_pie_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='descuento al pie %')),
                ('neto_gravado_21', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('neto_gravado_105', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('iva_21', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('iva_105', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('exento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('impuesto_interno_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('subtotal_neto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'carrito mayorista',
                'verbose_name_plural': 'carritos mayorista',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EcomCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_articulo', models.IntegerField(db_index=True, verbose_name='artículo')),
                ('codigo', models.CharField(blank=True, default='', max_length=64, verbose_name='código')),
                ('id_manual', models.CharField(blank=True, default='', max_length=64, verbose_name='código manual')),
                ('descripcion', models.CharField(blank=True, default='', max_length=255, verbose_name='descripción')),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('precio_unitario_neto', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('alicuota_iva', models.DecimalField(decimal_places=2, default=Decimal('21'), max_digits=6)),
                ('impuesto_interno_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('lista_id', models.IntegerField(default=1)),
                ('promocion', models.CharField(blank=True, default='', max_length=8)),
                ('promocion_tipo', models.CharField(blank=True, default='', max_length=64)),
                ('promocion_por', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('promocion_cant', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('neto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecom.ecomcart')),
            ],
            options={
                'verbose_name': 'renglón carrito mayorista',
                'verbose_name_plural': 'renglones carrito mayorista',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ecomcart',
            index=models.Index(fields=['base_empresa', 'id_usuario', 'estado'], name='ecom_ecomca_base_em_2ac24b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ecomcartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'id_articulo'), name='uniq_ecomcartitem_cart_articulo'),
        ),
    ]
