# Generated by Django 4.2 on 2026-07-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_checkpoint_mayoristapp_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomcart',
            name='autorizacion',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='autorización'),
        ),
        migrations.AddField(
            model_name='ecomcart',
            name='codigo_movimiento',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='CodigoMovimiento'),
        ),
        migrations.AddField(
            model_name='ecomcart',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmado el'),
        ),
        migrations.AddField(
            model_name='ecomcart',
            name='nro_comprobante',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='nro comprobante'),
        ),
    ]
