# Generated by Django 4.2 on 2026-07-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_checkpoint_mayoristapp_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomcart',
            name='tipo_comprobante',
            field=models.CharField(choices=[('PED', 'Pedido'), ('PRE', 'Presupuesto'), ('DEV', 'Devolución')], default='PED', max_length=3, verbose_name='tipo comprobante'),
        ),
    ]
