# Generated by Django 4.2 on 2026-07-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_checkpoint_mayoristapp_lista_precios_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomCatalogoRestriccionPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_empresa', models.CharField(db_index=True, max_length=64, verbose_name='base empresa')),
                ('id_punto_venta', models.IntegerField(db_index=True, verbose_name='punto de venta')),
                ('tipo', models.CharField(choices=[('articulo', 'Artículo'), ('rubro', 'Rubro'), ('subrubro', 'Sub rubro'), ('categoria', 'Categoría')], default='articulo', max_length=16, verbose_name='tipo')),
                ('valor_id', models.IntegerField(verbose_name='id excluido')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nota', models.CharField(blank=True, default='', max_length=255, verbose_name='nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'restricción de catálogo por PV',
                'verbose_name_plural': 'restricciones de catálogo por PV',
            },
        ),
        migrations.AddIndex(
            model_name='ecomcatalogorestriccionpv',
            index=models.Index(fields=['base_empresa', 'id_punto_venta', 'activo'], name='ecom_ecomca_base_em_b10d43_idx'),
        ),
        migrations.AddConstraint(
            model_name='ecomcatalogorestriccionpv',
            constraint=models.UniqueConstraint(fields=('base_empresa', 'id_punto_venta', 'tipo', 'valor_id'), name='uniq_ecom_restriccion_pv'),
        ),
    ]
