"""
Registro de módulos del sistema Synap
Define la configuración de todos los módulos disponibles
"""

MODULE_CONFIGS = {
    'core': {
        'name': 'core',
        'display_name': 'Core System',
        'description': 'Sistema base con entidades fundamentales, autenticación y gestión de usuarios',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': True,
        'is_core': True,
        'dependencies': [],
        'optional_dependencies': [],
        'settings': {
            'enable_multi_company': True,
            'enable_multi_branch': True,
            'default_language': 'es',
            'default_timezone': 'America/Argentina/Buenos_Aires',
        },
        'permissions': [
            'core.view_empresa',
            'core.add_empresa',
            'core.change_empresa',
            'core.delete_empresa',
            'core.view_usuario',
            'core.add_usuario',
            'core.change_usuario',
            'core.delete_usuario',
            'core.view_rol',
            'core.add_rol',
            'core.change_rol',
            'core.delete_rol',
            'core.view_permiso',
            'core.add_permiso',
            'core.change_permiso',
            'core.delete_permiso',
        ],
        'hooks': [
            'core.user_created',
            'core.user_updated',
            'core.empresa_created',
            'core.empresa_updated',
        ]
    },
    
    'login': {
        'name': 'login',
        'display_name': 'Authentication System',
        'description': 'Sistema de autenticación y gestión de sesiones',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': True,
        'is_core': True,
        'dependencies': ['core'],
        'optional_dependencies': [],
        'settings': {
            'enable_firebase_auth': True,
            'enable_google_oauth': True,
            'session_timeout': 3600,
            'max_login_attempts': 5,
        },
        'permissions': [
            'login.view_session',
            'login.manage_sessions',
        ],
        'hooks': [
            'login.user_login',
            'login.user_logout',
            'login.login_failed',
        ]
    },
    
    'dashboard': {
        'name': 'dashboard',
        'display_name': 'Dashboard System',
        'description': 'Panel principal y gestión de widgets',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': True,
        'is_core': True,
        'dependencies': ['core', 'login'],
        'optional_dependencies': [],
        'settings': {
            'default_dashboard_layout': 'grid',
            'enable_custom_widgets': True,
            'max_widgets_per_dashboard': 12,
        },
        'permissions': [
            'dashboard.view_dashboard',
            'dashboard.customize_dashboard',
            'dashboard.manage_widgets',
        ],
        'hooks': [
            'dashboard.widget_created',
            'dashboard.widget_updated',
        ]
    },
    
    'sales': {
        'name': 'sales',
        'display_name': 'Sales Management',
        'description': 'Sistema completo de gestión de ventas, clientes y facturación',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core'],
        'optional_dependencies': ['inventory', 'accounting'],
        'settings': {
            'enable_quotes': True,
            'enable_discounts': True,
            'tax_calculation': 'automatic',
            'credit_limit_validation': True,
            'auto_generate_invoices': False,
            'default_payment_terms': 30,
        },
        'permissions': [
            'sales.view_client',
            'sales.add_client',
            'sales.change_client',
            'sales.delete_client',
            'sales.view_order',
            'sales.add_order',
            'sales.change_order',
            'sales.delete_order',
            'sales.view_invoice',
            'sales.add_invoice',
            'sales.change_invoice',
            'sales.delete_invoice',
            'sales.view_payment',
            'sales.add_payment',
            'sales.change_payment',
            'sales.delete_payment',
            'sales.view_report',
            'sales.export_data',
        ],
        'hooks': [
            'sales.pre_order_create',
            'sales.post_order_create',
            'sales.pre_invoice_create',
            'sales.post_invoice_create',
            'sales.pre_payment_create',
            'sales.post_payment_create',
            'sales.client_created',
            'sales.client_updated',
        ]
    },
    
    'purchases': {
        'name': 'purchases',
        'display_name': 'Purchase Management',
        'description': 'Sistema completo de gestión de compras, proveedores y recepción',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core'],
        'optional_dependencies': ['inventory', 'accounting'],
        'settings': {
            'enable_approvals': True,
            'enable_ratings': True,
            'auto_approve_orders': False,
            'default_approval_workflow': 'simple',
            'enable_supplier_rating': True,
            'auto_generate_receipts': False,
        },
        'permissions': [
            'purchases.view_supplier',
            'purchases.add_supplier',
            'purchases.change_supplier',
            'purchases.delete_supplier',
            'purchases.view_order',
            'purchases.add_order',
            'purchases.change_order',
            'purchases.delete_order',
            'purchases.view_receipt',
            'purchases.add_receipt',
            'purchases.change_receipt',
            'purchases.delete_receipt',
            'purchases.approve_order',
            'purchases.view_report',
            'purchases.export_data',
        ],
        'hooks': [
            'purchases.pre_order_create',
            'purchases.post_order_create',
            'purchases.pre_receipt_create',
            'purchases.post_receipt_create',
            'purchases.supplier_created',
            'purchases.supplier_updated',
            'purchases.order_approved',
            'purchases.order_rejected',
        ]
    },
    
    'inventory': {
        'name': 'inventory',
        'display_name': 'Inventory Management',
        'description': 'Sistema completo de gestión de inventario, productos y stock',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core'],
        'optional_dependencies': ['sales', 'purchases'],
        'settings': {
            'enable_barcodes': True,
            'enable_lots': True,
            'enable_serial_numbers': True,
            'stock_valuation': 'fifo',
            'enable_warehouses': True,
            'enable_locations': True,
            'auto_adjust_stock': True,
            'low_stock_alerts': True,
        },
        'permissions': [
            'inventory.view_product',
            'inventory.add_product',
            'inventory.change_product',
            'inventory.delete_product',
            'inventory.view_category',
            'inventory.add_category',
            'inventory.change_category',
            'inventory.delete_category',
            'inventory.view_stock',
            'inventory.adjust_stock',
            'inventory.view_movement',
            'inventory.add_movement',
            'inventory.view_warehouse',
            'inventory.add_warehouse',
            'inventory.change_warehouse',
            'inventory.delete_warehouse',
            'inventory.view_report',
            'inventory.export_data',
        ],
        'hooks': [
            'inventory.pre_product_create',
            'inventory.post_product_create',
            'inventory.pre_stock_adjustment',
            'inventory.post_stock_adjustment',
            'inventory.low_stock_alert',
            'inventory.stock_movement_created',
        ]
    },
    
    'accounting': {
        'name': 'accounting',
        'display_name': 'Accounting System',
        'description': 'Sistema contable completo con plan de cuentas y asientos',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core'],
        'optional_dependencies': ['sales', 'purchases'],
        'settings': {
            'currency': 'ARS',
            'fiscal_year_start': '01-01',
            'enable_tax_management': True,
            'auto_create_entries': True,
            'enable_budgeting': False,
            'enable_cost_centers': False,
        },
        'permissions': [
            'accounting.view_account',
            'accounting.add_account',
            'accounting.change_account',
            'accounting.delete_account',
            'accounting.view_entry',
            'accounting.add_entry',
            'accounting.change_entry',
            'accounting.delete_entry',
            'accounting.view_tax',
            'accounting.add_tax',
            'accounting.change_tax',
            'accounting.delete_tax',
            'accounting.view_report',
            'accounting.export_data',
            'accounting.close_period',
        ],
        'hooks': [
            'accounting.pre_entry_create',
            'accounting.post_entry_create',
            'accounting.pre_period_close',
            'accounting.post_period_close',
            'accounting.tax_calculation',
        ]
    },
    
    'tiendanube': {
        'name': 'tiendanube',
        'display_name': 'TiendaNube Integration',
        'description': 'Integración con plataforma de e-commerce TiendaNube',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core', 'inventory', 'sales'],
        'optional_dependencies': [],
        'settings': {
            'sync_products': True,
            'sync_orders': True,
            'sync_inventory': True,
            'sync_customers': True,
            'auto_sync': True,
            'sync_interval': 300,  # 5 minutos
        },
        'permissions': [
            'tiendanube.view_integration',
            'tiendanube.configure_integration',
            'tiendanube.sync_products',
            'tiendanube.sync_orders',
            'tiendanube.sync_inventory',
            'tiendanube.view_sync_log',
            'tiendanube.manual_sync',
        ],
        'hooks': [
            'tiendanube.pre_product_sync',
            'tiendanube.post_product_sync',
            'tiendanube.pre_order_sync',
            'tiendanube.post_order_sync',
            'tiendanube.sync_error',
            'tiendanube.sync_completed',
        ]
    },
    
    
    'mercadopago': {
        'name': 'mercadopago',
        'display_name': 'MercadoPago Integration',
        'description': 'Integración completa con MercadoPago para procesamiento de pagos y dispositivos SmartPOS',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core', 'sales'],
        'optional_dependencies': ['accounting'],
        'settings': {
            'enable_smartpos': True,
            'enable_device_management': True,
            'enable_transaction_logging': True,
            'enable_webhooks': True,
            'auto_sync_devices': True,
            'default_currency': 'ARS',
            'enable_installments': True,
            'max_installments': 12,
            'enable_receipt_printing': True,
            'enable_offline_mode': False,
        },
        'permissions': [
            'mercadopago.view_mercadopagoconfig',
            'mercadopago.add_mercadopagoconfig',
            'mercadopago.change_mercadopagoconfig',
            'mercadopago.delete_mercadopagoconfig',
            'mercadopago.view_mercadopagodevice',
            'mercadopago.add_mercadopagodevice',
            'mercadopago.change_mercadopagodevice',
            'mercadopago.delete_mercadopagodevice',
            'mercadopago.view_mercadopagotransaction',
            'mercadopago.add_mercadopagotransaction',
            'mercadopago.change_mercadopagotransaction',
            'mercadopago.delete_mercadopagotransaction',
            'mercadopago.process_payment',
            'mercadopago.view_reports',
            'mercadopago.export_data',
            'mercadopago.manage_devices',
        ],
        'hooks': [
            'mercadopago.device_registered',
            'mercadopago.device_activated',
            'mercadopago.device_deactivated',
            'mercadopago.transaction_created',
            'mercadopago.transaction_completed',
            'mercadopago.transaction_failed',
            'mercadopago.payment_processed',
            'mercadopago.webhook_received',
            'mercadopago.device_sync_completed',
            'mercadopago.offline_transaction_synced',
        ]
    },
    
    'clover': {
        'name': 'clover',
        'display_name': 'Clover Payment Integration',
        'description': 'Integración completa con dispositivos Clover para procesamiento de pagos en punto de venta',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core', 'sales'],
        'optional_dependencies': ['accounting'],
        'settings': {
            'enable_device_management': True,
            'enable_transaction_logging': True,
            'enable_webhooks': True,
            'auto_sync_devices': True,
            'default_currency': 'ARS',
            'enable_installments': True,
            'max_installments': 12,
            'enable_receipt_printing': True,
            'enable_offline_mode': False,
        },
        'permissions': [
            'clover.view_cloverdevice',
            'clover.add_cloverdevice',
            'clover.change_cloverdevice',
            'clover.delete_cloverdevice',
            'clover.view_clovertransaction',
            'clover.add_clovertransaction',
            'clover.change_clovertransaction',
            'clover.delete_clovertransaction',
            'clover.view_cloverwebhook',
            'clover.add_cloverwebhook',
            'clover.change_cloverwebhook',
            'clover.delete_cloverwebhook',
            'clover.view_cloverconfig',
            'clover.add_cloverconfig',
            'clover.change_cloverconfig',
            'clover.delete_cloverconfig',
            'clover.process_payment',
            'clover.view_reports',
            'clover.export_data',
            'clover.manage_devices',
        ],
        'hooks': [
            'clover.device_registered',
            'clover.device_activated',
            'clover.device_deactivated',
            'clover.transaction_created',
            'clover.transaction_completed',
            'clover.transaction_failed',
            'clover.payment_processed',
            'clover.webhook_received',
            'clover.device_sync_completed',
            'clover.offline_transaction_synced',
        ]
    },
    
    'administraNET_integration': {
        'name': 'administraNET_integration',
        'display_name': 'administraNET Integration',
        'description': 'Integración bidireccional con administraNET: sincronización de productos, stock, clientes, pedidos y más.',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core', 'inventory', 'sales', 'purchases'],
        'optional_dependencies': ['accounting'],
        'settings': {
            'enable_bidirectional_sync': True,
            'default_sync_interval': 30,
            'enable_logging': True,
            'log_level': 'INFO',
        },
        'permissions': [
            'administraNET_integration.view_administranetconfig',
            'administraNET_integration.add_administranetconfig',
            'administraNET_integration.change_administranetconfig',
            'administraNET_integration.delete_administranetconfig',
            'administraNET_integration.view_synclog',
            'administraNET_integration.add_synclog',
            'administraNET_integration.change_synclog',
            'administraNET_integration.delete_synclog',
            'administraNET_integration.view_tablemapping',
            'administraNET_integration.add_tablemapping',
            'administraNET_integration.change_tablemapping',
            'administraNET_integration.delete_tablemapping',
            'administraNET_integration.run_sync',
            'administraNET_integration.configure_mapping',
        ],
        'hooks': [
            'administraNET_integration.pre_sync',
            'administraNET_integration.post_sync',
            'administraNET_integration.sync_error',
            'administraNET_integration.sync_completed',
        ]
    },
    'logistics': {
        'name': 'logistics',
        'display_name': 'Logistics',
        'description': 'Logistics and transport management: routes, drivers, deliveries, tracking.',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core', 'sales', 'inventory'],
        'optional_dependencies': [],
        'settings': {
            'enable_route_planning': True,
            'enable_delivery_tracking': True,
            'enable_driver_management': True,
        },
        'permissions': [
            'logistics.view_deliveryroute',
            'logistics.add_deliveryroute',
            'logistics.change_deliveryroute',
            'logistics.delete_deliveryroute',
            'logistics.view_driver',
            'logistics.add_driver',
            'logistics.change_driver',
            'logistics.delete_driver',
            'logistics.view_deliverystop',
            'logistics.add_deliverystop',
            'logistics.change_deliverystop',
            'logistics.delete_deliverystop',
            'logistics.view_deliveryevent',
            'logistics.add_deliveryevent',
            'logistics.change_deliveryevent',
            'logistics.delete_deliveryevent',
        ],
        'hooks': [
            'logistics.route_created',
            'logistics.route_completed',
            'logistics.delivery_started',
            'logistics.delivery_completed',
        ]
    },
    'finance': {
        'name': 'finance',
        'display_name': 'Finance',
        'description': 'Financial management: credit limits, financial reports, accounts receivable.',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core', 'sales'],
        'optional_dependencies': ['accounting'],
        'settings': {
            'enable_credit_limit': True,
            'enable_financial_reports': True,
        },
        'permissions': [
            'finance.view_creditlimitlog',
            'finance.add_creditlimitlog',
            'finance.change_creditlimitlog',
            'finance.delete_creditlimitlog',
            'finance.view_financialreport',
            'finance.add_financialreport',
            'finance.change_financialreport',
            'finance.delete_financialreport',
        ],
        'hooks': [
            'finance.credit_limit_changed',
            'finance.report_generated',
        ]
    },
    'reports': {
        'name': 'reports',
        'display_name': 'Reports & Dashboards',
        'description': 'Operational and managerial analytics with interactive dashboards, caching and exports.',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core', 'dashboard'],
        'optional_dependencies': ['sales', 'inventory', 'finance', 'purchases', 'logistics'],
        'settings': {
            'catalog_refresh_minutes': 60,
            'default_cache_ttl': 900,
            'max_rows': 20000,
            'schedule_daily_refresh': '05:30',
            'schedule_weekly_refresh': 'mon-06:00',
        },
        'permissions': [
            'reports.ver',
            'reports.view_operational',
            'reports.view_managerial',
            'reports.exportar',
            'reports.dashboard',
            'reports.builder',
            'reports.programar',
        ],
        'hooks': [
            'reports.catalog_updated',
            'reports.dashboard_shared',
            'reports.export_created',
        ]
    },
    
    'tiendanube_administranet': {
        'name': 'tiendanube_administranet',
        'display_name': 'Tiendanube-AdministraNET Integration',
        'description': 'Integración completa entre Tiendanube y AdministraNET: sincronización de clientes, productos, órdenes y más.',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core'],
        'optional_dependencies': [],
        'settings': {
            'enable_customer_sync': True,
            'enable_product_sync': True,
            'enable_order_sync': True,
            'sync_interval': 300,
            'enable_logging': True,
            'log_level': 'INFO',
        },
        'permissions': [
            'tiendanube_administranet.view_tiendanubeconfig',
            'tiendanube_administranet.add_tiendanubeconfig',
            'tiendanube_administranet.change_tiendanubeconfig',
            'tiendanube_administranet.delete_tiendanubeconfig',
            'tiendanube_administranet.view_administranetconfig',
            'tiendanube_administranet.add_administranetconfig',
            'tiendanube_administranet.change_administranetconfig',
            'tiendanube_administranet.delete_administranetconfig',
            'tiendanube_administranet.view_customermapping',
            'tiendanube_administranet.add_customermapping',
            'tiendanube_administranet.change_customermapping',
            'tiendanube_administranet.delete_customermapping',
            'tiendanube_administranet.view_productmapping',
            'tiendanube_administranet.add_productmapping',
            'tiendanube_administranet.change_productmapping',
            'tiendanube_administranet.delete_productmapping',
            'tiendanube_administranet.view_ordermapping',
            'tiendanube_administranet.add_ordermapping',
            'tiendanube_administranet.change_ordermapping',
            'tiendanube_administranet.delete_ordermapping',
            'tiendanube_administranet.view_synclog',
            'tiendanube_administranet.run_sync',
            'tiendanube_administranet.configure_mapping',
        ],
        'hooks': [
            'tiendanube_administranet.pre_customer_sync',
            'tiendanube_administranet.post_customer_sync',
            'tiendanube_administranet.pre_product_sync',
            'tiendanube_administranet.post_product_sync',
            'tiendanube_administranet.pre_order_sync',
            'tiendanube_administranet.post_order_sync',
            'tiendanube_administranet.sync_error',
            'tiendanube_administranet.sync_completed',
        ]
    },
    
    'reports_ai': {
        'name': 'reports_ai',
        'display_name': 'Reports AI (CrewAI)',
        'description': 'Sistema multiagente de reportes para Administranet Gestión basado en CrewAI y OpenAI GPT-4. Genera reportes verídicos sin exponer detalles técnicos.',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core'],
        'optional_dependencies': ['administraNET_integration'],
        'settings': {
            'enable_webhooks': True,
            'enable_dashboard': True,
            'default_temperature': 0.3,
            'max_tokens_per_request': 10000,
            'enable_vb6_analysis': True,
            'enable_glossary_training': True,
            'cache_reports': True,
            'cache_timeout': 3600,
        },
        'permissions': [
            'reports_ai.view_reports',
            'reports_ai.generate_reports',
            'reports_ai.configure_reports_ai',
            'reports_ai.view_agent_metrics',
            'reports_ai.manage_business_rules',
            'reports_ai.access_webhooks',
            'reports_ai.view_reportrequest',
            'reports_ai.add_reportrequest',
            'reports_ai.change_reportrequest',
            'reports_ai.delete_reportrequest',
            'reports_ai.view_businessrule',
            'reports_ai.add_businessrule',
            'reports_ai.change_businessrule',
            'reports_ai.delete_businessrule',
            'reports_ai.view_glossaryterm',
            'reports_ai.add_glossaryterm',
            'reports_ai.change_glossaryterm',
            'reports_ai.delete_glossaryterm',
            'reports_ai.view_agentmetrics',
        ],
        'hooks': [
            'reports_ai.pre_report_generate',
            'reports_ai.post_report_generate',
            'reports_ai.report_error',
            'reports_ai.agent_invoked',
            'reports_ai.validation_failed',
            'reports_ai.hallucination_detected',
        ]
    }
} 