"""
Registro de módulos del sistema Synap
Define la configuración de todos los módulos disponibles
"""

MODULE_CONFIGS = {
    'core': {
        'name': 'core',
        'display_name': 'Core System',
        'description': 'Sistema base con entidades fundamentales, autenticación y gestión de usuarios',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': True,
        'is_core': True,
        'dependencies': [],
        'optional_dependencies': [],
        'settings': {
            'enable_multi_company': True,
            'enable_multi_branch': True,
            'default_language': 'es',
            'default_timezone': 'America/Argentina/Buenos_Aires',
        },
        'permissions': [
            'core.view_empresa',
            'core.add_empresa',
            'core.change_empresa',
            'core.delete_empresa',
            'core.view_usuario',
            'core.add_usuario',
            'core.change_usuario',
            'core.delete_usuario',
            'core.view_rol',
            'core.add_rol',
            'core.change_rol',
            'core.delete_rol',
            'core.view_permiso',
            'core.add_permiso',
            'core.change_permiso',
            'core.delete_permiso',
        ],
        'hooks': [
            'core.user_created',
            'core.user_updated',
            'core.empresa_created',
            'core.empresa_updated',
        ]
    },
    
    'login': {
        'name': 'login',
        'display_name': 'Authentication System',
        'description': 'Sistema de autenticación y gestión de sesiones',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': True,
        'is_core': True,
        'dependencies': ['core'],
        'optional_dependencies': [],
        'settings': {
            'enable_firebase_auth': True,
            'enable_google_oauth': True,
            'session_timeout': 3600,
            'max_login_attempts': 5,
        },
        'permissions': [
            'login.view_session',
            'login.manage_sessions',
        ],
        'hooks': [
            'login.user_login',
            'login.user_logout',
            'login.login_failed',
        ]
    },
    
    'dashboard': {
        'name': 'dashboard',
        'display_name': 'Dashboard System',
        'description': 'Panel principal y gestión de widgets',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': True,
        'is_core': True,
        'dependencies': ['core', 'login'],
        'optional_dependencies': [],
        'settings': {
            'default_dashboard_layout': 'grid',
            'enable_custom_widgets': True,
            'max_widgets_per_dashboard': 12,
        },
        'permissions': [
            'dashboard.view_dashboard',
            'dashboard.customize_dashboard',
            'dashboard.manage_widgets',
        ],
        'hooks': [
            'dashboard.widget_created',
            'dashboard.widget_updated',
        ]
    },
    
    'mercadopago': {
        'name': 'mercadopago',
        'display_name': 'MercadoPago Integration',
        'description': 'Integración completa con MercadoPago para procesamiento de pagos y dispositivos SmartPOS',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core'],
        'optional_dependencies': [],
        'settings': {
            'enable_smartpos': True,
            'enable_device_management': True,
            'enable_transaction_logging': True,
            'enable_webhooks': True,
            'auto_sync_devices': True,
            'default_currency': 'ARS',
            'enable_installments': True,
            'max_installments': 12,
            'enable_receipt_printing': True,
            'enable_offline_mode': False,
        },
        'permissions': [
            'mercadopago.view_mercadopagoconfig',
            'mercadopago.add_mercadopagoconfig',
            'mercadopago.change_mercadopagoconfig',
            'mercadopago.delete_mercadopagoconfig',
            'mercadopago.view_mercadopagodevice',
            'mercadopago.add_mercadopagodevice',
            'mercadopago.change_mercadopagodevice',
            'mercadopago.delete_mercadopagodevice',
            'mercadopago.view_mercadopagotransaction',
            'mercadopago.add_mercadopagotransaction',
            'mercadopago.change_mercadopagotransaction',
            'mercadopago.delete_mercadopagotransaction',
            'mercadopago.process_payment',
            'mercadopago.view_reports',
            'mercadopago.export_data',
            'mercadopago.manage_devices',
        ],
        'hooks': [
            'mercadopago.device_registered',
            'mercadopago.device_activated',
            'mercadopago.device_deactivated',
            'mercadopago.transaction_created',
            'mercadopago.transaction_completed',
            'mercadopago.transaction_failed',
            'mercadopago.payment_processed',
            'mercadopago.webhook_received',
            'mercadopago.device_sync_completed',
            'mercadopago.offline_transaction_synced',
        ]
    },
    
    'clover': {
        'name': 'clover',
        'display_name': 'Clover Payment Integration',
        'description': 'Integración completa con dispositivos Clover para procesamiento de pagos en punto de venta',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core'],
        'optional_dependencies': [],
        'settings': {
            'enable_device_management': True,
            'enable_transaction_logging': True,
            'enable_webhooks': True,
            'auto_sync_devices': True,
            'default_currency': 'ARS',
            'enable_installments': True,
            'max_installments': 12,
            'enable_receipt_printing': True,
            'enable_offline_mode': False,
        },
        'permissions': [
            'clover.view_cloverdevice',
            'clover.add_cloverdevice',
            'clover.change_cloverdevice',
            'clover.delete_cloverdevice',
            'clover.view_clovertransaction',
            'clover.add_clovertransaction',
            'clover.change_clovertransaction',
            'clover.delete_clovertransaction',
            'clover.view_cloverwebhook',
            'clover.add_cloverwebhook',
            'clover.change_cloverwebhook',
            'clover.delete_cloverwebhook',
            'clover.view_cloverconfig',
            'clover.add_cloverconfig',
            'clover.change_cloverconfig',
            'clover.delete_cloverconfig',
            'clover.process_payment',
            'clover.view_reports',
            'clover.export_data',
            'clover.manage_devices',
        ],
        'hooks': [
            'clover.device_registered',
            'clover.device_activated',
            'clover.device_deactivated',
            'clover.transaction_created',
            'clover.transaction_completed',
            'clover.transaction_failed',
            'clover.payment_processed',
            'clover.webhook_received',
            'clover.device_sync_completed',
            'clover.offline_transaction_synced',
        ]
    },
    
    'reports': {
        'name': 'reports',
        'display_name': 'Reports & Dashboards',
        'description': 'Operational and managerial analytics with interactive dashboards, caching and exports.',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core', 'dashboard'],
        'optional_dependencies': [],
        'settings': {
            'catalog_refresh_minutes': 60,
            'default_cache_ttl': 900,
            'max_rows': 20000,
            'schedule_daily_refresh': '05:30',
            'schedule_weekly_refresh': 'mon-06:00',
        },
        'permissions': [
            'reports.ver',
            'reports.view_operational',
            'reports.view_managerial',
            'reports.exportar',
            'reports.dashboard',
            'reports.builder',
            'reports.programar',
        ],
        'hooks': [
            'reports.catalog_updated',
            'reports.dashboard_shared',
            'reports.export_created',
        ]
    },

    'ia': {
        'name': 'ia',
        'display_name': 'IA y Asistentes',
        'description': (
            'Plataforma de asistentes personales persistentes con memoria, orquestación multiagente '
            'y configuración de proveedores/modelos por UI.'
        ),
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core', 'dashboard', 'reports'],
        'optional_dependencies': ['stock', 'ventas', 'compras', 'mpr', 'logistica', 'self_checkout'],
        'settings': {
            'memory_enabled': True,
            'provider_ui_enabled': True,
            'conversation_surface': 'pwa-mobile-first',
            'default_agent_slug': 'asistente-reportes',
        },
        'permissions': [
            'ia.ver',
            'ia.agentes',
            'ia.reportes',
            'ia.memoria',
            'ia.recomendaciones',
            'ia.predicciones',
            'ia.automatizacion',
            'ia.admin',
        ],
        'hooks': [
            'ia.conversation_created',
            'ia.execution_completed',
            'ia.memory_written',
        ]
    },
    
    'tiendanube_administranet': {
        'name': 'tiendanube_administranet',
        'display_name': 'Tiendanube-AdministraNET Integration',
        'description': 'Integración completa entre Tiendanube y AdministraNET: sincronización de clientes, productos, órdenes y más.',
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core'],
        'optional_dependencies': [],
        'settings': {
            'enable_customer_sync': True,
            'enable_product_sync': True,
            'enable_order_sync': True,
            'sync_interval': 300,
            'enable_logging': True,
            'log_level': 'INFO',
        },
        'permissions': [
            'tiendanube_administranet.view_tiendanubeconfig',
            'tiendanube_administranet.add_tiendanubeconfig',
            'tiendanube_administranet.change_tiendanubeconfig',
            'tiendanube_administranet.delete_tiendanubeconfig',
            'tiendanube_administranet.view_administranetconfig',
            'tiendanube_administranet.add_administranetconfig',
            'tiendanube_administranet.change_administranetconfig',
            'tiendanube_administranet.delete_administranetconfig',
            'tiendanube_administranet.view_customermapping',
            'tiendanube_administranet.add_customermapping',
            'tiendanube_administranet.change_customermapping',
            'tiendanube_administranet.delete_customermapping',
            'tiendanube_administranet.view_productmapping',
            'tiendanube_administranet.add_productmapping',
            'tiendanube_administranet.change_productmapping',
            'tiendanube_administranet.delete_productmapping',
            'tiendanube_administranet.view_ordermapping',
            'tiendanube_administranet.add_ordermapping',
            'tiendanube_administranet.change_ordermapping',
            'tiendanube_administranet.delete_ordermapping',
            'tiendanube_administranet.view_synclog',
            'tiendanube_administranet.run_sync',
            'tiendanube_administranet.configure_mapping',
        ],
        'hooks': [
            'tiendanube_administranet.pre_customer_sync',
            'tiendanube_administranet.post_customer_sync',
            'tiendanube_administranet.pre_product_sync',
            'tiendanube_administranet.post_product_sync',
            'tiendanube_administranet.pre_order_sync',
            'tiendanube_administranet.post_order_sync',
            'tiendanube_administranet.sync_error',
            'tiendanube_administranet.sync_completed',
        ]
    },

    'logistica': {
        'name': 'logistica',
        'display_name': 'Logística',
        'description': (
            'Operación de entregas en ruta: listados por chofer, registro de entrega y APIs '
            'sobre datos AdministraNET (MySQL).'
        ),
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core', 'dashboard'],
        'optional_dependencies': ['reports'],
        'settings': {
            'max_list_rows': 2000,
        },
        'permissions': [
            'logistica_editar_entregas',
            'logistica.*',
        ],
        'hooks': [],
    },

    'fe_afip': {
        'name': 'fe_afip',
        'display_name': 'Facturación AFIP (FE)',
        'description': (
            'Configuración de certificados ARCA/AFIP, homologación o producción y CAEA; '
            'requerido para factura electrónica en TPV / self-checkout.'
        ),
        'version': '1.0.0',
        'author': 'Synap Team',
        'is_required': False,
        'is_core': False,
        'dependencies': ['core', 'dashboard'],
        'optional_dependencies': ['self_checkout'],
        'settings': {},
        'permissions': [
            'fe_afip.view_afipconfig',
            'fe_afip.add_afipconfig',
            'fe_afip.change_afipconfig',
            'fe_afip.delete_afipconfig',
        ],
        'hooks': [],
    },
    # self_checkout: app core (siempre instalada), URLs en django_project/urls.py, permisos en PERMISOS_POR_MODULO + sync.
} 