# Generated by Django 4.2 on 2025-07-15 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('adminet_id', models.IntegerField(blank=True, help_text='ID original de administraNET para sincronización', null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('adminet_id', models.IntegerField(blank=True, help_text='ID original de administraNET para sincronización', null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InitialStockDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('es_carga_masiva', models.BooleanField(default=False)),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='stock_initial_excels/')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('referencia_externa', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Borrador de Stock Inicial',
                'verbose_name_plural': 'Borradores de Stock Inicial',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('location_type', models.CharField(choices=[('internal', 'Internal'), ('supplier', 'Supplier'), ('customer', 'Customer'), ('transit', 'In Transit'), ('scrap', 'Scrap')], default='internal', max_length=20, verbose_name='Location Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('allow_operations', models.BooleanField(default=True, verbose_name='Allow Operations')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.branch', verbose_name='Branch')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.empresa', verbose_name='Company')),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='Parent Location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('consumable', 'Consumable'), ('stockable', 'Stockable'), ('service', 'Service'), ('combo', 'Combo')], default='stockable', max_length=20, verbose_name='Product Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('handle', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Handle (URL)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('tracking', models.CharField(choices=[('none', 'None'), ('lot', 'By Lot'), ('serial', 'By Serial Number')], default='none', max_length=10, verbose_name='Tracking')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Weight (kg)')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Volume (m³)')),
                ('is_dangerous', models.BooleanField(default=False, verbose_name='Is Dangerous Good')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='Barcode')),
                ('tiendanube_id', models.BigIntegerField(blank=True, null=True)),
                ('tiendanube_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Width (cm)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Height (cm)')),
                ('depth_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Depth (cm)')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL (YouTube/Vimeo)')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Price')),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Profit Margin (%)')),
                ('product_kind', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital/Service')], default='physical', max_length=10, verbose_name='Product Kind')),
                ('tax_category', models.CharField(blank=True, help_text='Category for tax calculation (e.g., standard, reduced, zero)', max_length=50, verbose_name='Tax Category')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for categorization and sync control', max_length=255, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.branch', verbose_name='Branch')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='Category')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.empresa', verbose_name='Company')),
                ('fiscal_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.fiscalposition', verbose_name='Fiscal Position')),
                ('price_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='Price Currency')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inventory.productattribute')),
            ],
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100, verbose_name='Lot/Serial Number')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocklots', to='core.branch', verbose_name='Branch')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocklots', to='core.empresa', verbose_name='Company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock Lot',
                'verbose_name_plural': 'Stock Lots',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.branch', verbose_name='Branch')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.empresa', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('adminet_id', models.IntegerField(blank=True, help_text='ID original de administraNET para sincronización', null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('reserved_for', models.CharField(max_length=255, verbose_name='Reserved For')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockreservations', to='core.branch', verbose_name='Branch')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockreservations', to='core.empresa', verbose_name='Company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('move_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('internal', 'Internal Transfer'), ('adjustment', 'Adjustment')], max_length=20, verbose_name='Move Type')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Reference')),
                ('origin', models.CharField(blank=True, max_length=255, verbose_name='Origin')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='State')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validated At')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockmoves', to='core.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockmoves', to='core.empresa', verbose_name='Company')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_out', to='inventory.location', verbose_name='From Location')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklot', verbose_name='Lot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_in', to='inventory.location', verbose_name='To Location')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validated By')),
            ],
            options={
                'verbose_name': 'Stock Move',
                'verbose_name_plural': 'Stock Moves',
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Quantity')),
                ('max_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Quantity')),
                ('method', models.CharField(default='manual', max_length=20, verbose_name='Method')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishmentrules', to='core.branch', verbose_name='Branch')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishmentrules', to='core.empresa', verbose_name='Company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Replenishment Rule',
                'verbose_name_plural': 'Replenishment Rules',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('attributes', models.ManyToManyField(blank=True, related_name='variants', to='inventory.productattributevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.subcategory', verbose_name='Subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='products', to='accounting.tax', verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expected Quantity')),
                ('real_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Real Quantity')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryadjustments', to='core.branch', verbose_name='Branch')),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Counted By')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryadjustments', to='core.empresa', verbose_name='Company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Inventory Adjustment',
                'verbose_name_plural': 'Inventory Adjustments',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InitialStockDraftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('borrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.initialstockdraft')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initialstockdraftitems', to='core.branch', verbose_name='Branch')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initialstockdraftitems', to='core.empresa', verbose_name='Company')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('ubicacion_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockdraft_items', to='inventory.location')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Detalle de Borrador de Stock Inicial',
                'verbose_name_plural': 'Detalles de Borrador de Stock Inicial',
            },
        ),
        migrations.CreateModel(
            name='InitialStockDraftDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='stock_initial_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('borrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_respaldo', to='inventory.initialstockdraft')),
            ],
        ),
        migrations.AddField(
            model_name='initialstockdraft',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='initialstockdraft',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initialstockdrafts', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='initialstockdraft',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockdrafts_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='initialstockdraft',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initialstockdrafts', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='initialstockdraft',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location'),
        ),
        migrations.CreateModel(
            name='StockQuant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Reserved Quantity')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockquants', to='core.branch', verbose_name='Branch')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockquants', to='core.empresa', verbose_name='Company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklot', verbose_name='Lot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock Quant',
                'verbose_name_plural': 'Stock Quants',
                'unique_together': {('product', 'location', 'lot')},
            },
        ),
        migrations.CreateModel(
            name='ProductComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combo', models.ForeignKey(limit_choices_to={'type': 'combo'}, on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='inventory.product')),
                ('component', models.ForeignKey(limit_choices_to={'type__in': ['consumable', 'stockable']}, on_delete=django.db.models.deletion.CASCADE, related_name='as_component', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Combo Component',
                'verbose_name_plural': 'Combo Components',
                'unique_together': {('combo', 'component')},
            },
        ),
    ]
