# Generated by Django 4.2 on 2025-06-23 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_alter_systemconfiguration_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('location_type', models.CharField(choices=[('internal', 'Internal'), ('supplier', 'Supplier'), ('customer', 'Customer'), ('transit', 'In Transit'), ('scrap', 'Scrap')], default='internal', max_length=20, verbose_name='Location Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('allow_operations', models.BooleanField(default=True, verbose_name='Allow Operations')),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='Parent Location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('handle', models.SlugField(max_length=255, unique=True, verbose_name='Handle (URL)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('tracking', models.CharField(choices=[('none', 'None'), ('lot', 'By Lot'), ('serial', 'By Serial Number')], default='none', max_length=10, verbose_name='Tracking')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Weight (kg)')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Volume (m³)')),
                ('is_dangerous', models.BooleanField(default=False, verbose_name='Is Dangerous Good')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='Barcode')),
                ('tiendanube_id', models.BigIntegerField(blank=True, null=True)),
                ('tiendanube_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand', verbose_name='Brand')),
                ('price_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='Price Currency')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100, verbose_name='Lot/Serial Number')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock Lot',
                'verbose_name_plural': 'Stock Lots',
            },
        ),
        migrations.CreateModel(
            name='TiendaNubeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=50, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('api_url', models.URLField(default='https://api.tiendanube.com/v1')),
                ('auto_sync', models.BooleanField(default=True, verbose_name='Auto Sync')),
                ('sync_interval', models.IntegerField(default=30, help_text='Interval in minutes for auto-sync.', verbose_name='Sync Interval')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('sync_products', models.BooleanField(default=True, verbose_name='Sync Products')),
                ('sync_stock', models.BooleanField(default=True, verbose_name='Sync Stock')),
                ('sync_variants', models.BooleanField(default=True, verbose_name='Sync Variants')),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_active', models.BooleanField(default=True, verbose_name='Webhook Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TiendaNube Configuration',
                'verbose_name_plural': 'TiendaNube Configurations',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='TiendaNubeSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('product', 'Product'), ('stock', 'Stock'), ('variant', 'Variant'), ('webhook', 'Webhook'), ('full', 'Full Sync')], max_length=20, verbose_name='Sync Type')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial')], max_length=20, verbose_name='Status')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_success', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tiendanubeconfig')),
            ],
            options={
                'verbose_name': 'TiendaNube Sync Log',
                'verbose_name_plural': 'TiendaNube Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TiendaNubeProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiendanube_id', models.BigIntegerField(unique=True)),
                ('tiendanube_variant_id', models.BigIntegerField(blank=True, null=True)),
                ('tiendanube_handle', models.CharField(blank=True, max_length=255)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error'), ('conflict', 'Conflict')], default='pending', max_length=20, verbose_name='Sync Status')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sync Enabled')),
                ('sync_price', models.BooleanField(default=True, verbose_name='Sync Price')),
                ('sync_stock', models.BooleanField(default=True, verbose_name='Sync Stock')),
                ('sync_description', models.BooleanField(default=True, verbose_name='Sync Description')),
                ('error_message', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name': 'TiendaNube Product Mapping',
                'verbose_name_plural': 'TiendaNube Product Mappings',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('reserved_for', models.CharField(max_length=255, verbose_name='Reserved For')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('move_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('internal', 'Internal Transfer'), ('adjustment', 'Adjustment')], max_length=20, verbose_name='Move Type')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Reference')),
                ('origin', models.CharField(blank=True, max_length=255, verbose_name='Origin')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='State')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validated At')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_out', to='inventory.location', verbose_name='From Location')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklot', verbose_name='Lot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_in', to='inventory.location', verbose_name='To Location')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validated By')),
            ],
            options={
                'verbose_name': 'Stock Move',
                'verbose_name_plural': 'Stock Moves',
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min Quantity')),
                ('max_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max Quantity')),
                ('method', models.CharField(default='manual', max_length=20, verbose_name='Method')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Replenishment Rule',
                'verbose_name_plural': 'Replenishment Rules',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('tiendanube_id', models.BigIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.subcategory', verbose_name='Subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unitofmeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expected Quantity')),
                ('real_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Real Quantity')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Counted By')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Inventory Adjustment',
                'verbose_name_plural': 'Inventory Adjustments',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockQuant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Reserved Quantity')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklot', verbose_name='Lot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock Quant',
                'verbose_name_plural': 'Stock Quants',
                'unique_together': {('product', 'location', 'lot')},
            },
        ),
    ]
