# Generated by Django 4.2 on 2025-07-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_set_razon_social_required'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='category',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.empresa', verbose_name='Company'),
        ),
    ]
