# Generated by Django 4.2 on 2025-06-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendanubeproductmapping',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tiendanubesynclog',
            name='config',
        ),
        migrations.DeleteModel(
            name='TiendaNubeConfig',
        ),
        migrations.DeleteModel(
            name='TiendaNubeProductMapping',
        ),
        migrations.DeleteModel(
            name='TiendaNubeSyncLog',
        ),
    ]
