# Generated by Django 4.2 on 2025-06-25 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_merge_20250624_1842'),
        ('inventory', '0002_remove_tiendanubeproductmapping_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialStockDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('es_carga_masiva', models.BooleanField(default=False)),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='stock_initial_excels/')),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('referencia_externa', models.CharField(blank=True, max_length=255)),
                ('adjuntos', models.FileField(blank=True, null=True, upload_to='stock_initial_attachments/')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockdrafts_creados', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Ubicación principal')),
            ],
            options={
                'verbose_name': 'Borrador de Stock Inicial',
                'verbose_name_plural': 'Borradores de Stock Inicial',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unitofmeasure'),
        ),
        migrations.CreateModel(
            name='InitialStockDraftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('borrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.initialstockdraft')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('ubicacion_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockdraft_items', to='inventory.location')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Detalle de Borrador de Stock Inicial',
                'verbose_name_plural': 'Detalles de Borrador de Stock Inicial',
            },
        ),
    ]
