# Generated by Django 4.2 on 2025-06-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_initialstockdraft_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialstockdraft',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='initialstockdraftdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
