# Generated by Django 4.2 on 2025-06-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_initialstockdraft_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('consumable', 'Consumable'), ('stockable', 'Stockable'), ('service', 'Service'), ('combo', 'Combo')], default='stockable', max_length=20, verbose_name='Product Type'),
        ),
        migrations.CreateModel(
            name='ProductComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combo', models.ForeignKey(limit_choices_to={'type': 'combo'}, on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='inventory.product')),
                ('component', models.ForeignKey(limit_choices_to={'type__in': ['consumable', 'stockable']}, on_delete=django.db.models.deletion.CASCADE, related_name='as_component', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Combo Component',
                'verbose_name_plural': 'Combo Components',
                'unique_together': {('combo', 'component')},
            },
        ),
    ]
