# Generated by Django 4.2 on 2025-07-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='depth_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Depth (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_kind',
            field=models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital/Service')], default='physical', max_length=10, verbose_name='Product Kind'),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Profit Margin (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video URL (YouTube/Vimeo)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Width (cm)'),
        ),
    ]
