# Generated by Django 4.2 on 2025-07-02 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_branch'),
        ('inventory', '0010_alter_product_handle_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialstockdraft',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initialstockdrafts', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='initialstockdraft',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initialstockdrafts', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='initialstockdraftitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initialstockdraftitems', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='initialstockdraftitem',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initialstockdraftitems', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryadjustments', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryadjustments', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='location',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='location',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='replenishmentrule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replenishmentrules', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='replenishmentrule',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replenishmentrules', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocklots', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocklots', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockmoves', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockmoves', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='stockquant',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockquants', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='stockquant',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockquants', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockreservations', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockreservations', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.empresa', verbose_name='Company'),
        ),
    ]
