# Generated by Django 4.2 on 2025-07-02 21:27

from django.db import migrations

def fill_empresa_branch(apps, schema_editor):
    Empresa = apps.get_model('core', 'Empresa')
    Branch = apps.get_model('core', 'Branch')
    empresa = Empresa.objects.first()
    branch = Branch.objects.filter(empresa=empresa).first()
    for model_name in [
        'Warehouse', 'Location', 'Product', 'StockLot', 'StockQuant', 'StockMove',
        'InventoryAdjustment', 'StockReservation', 'ReplenishmentRule',
        'InitialStockDraft', 'InitialStockDraftItem']:
        Model = apps.get_model('inventory', model_name)
        Model.objects.filter(empresa__isnull=True).update(empresa=empresa)
        Model.objects.filter(branch__isnull=True).update(branch=branch)

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_initialstockdraft_branch_initialstockdraft_empresa_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_empresa_branch, reverse_code=migrations.RunPython.noop),
    ]
