# Generated by Django 4.2 on 2025-07-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0014_productattribute_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fiscal_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.fiscalposition', verbose_name='Fiscal Position'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_category',
            field=models.CharField(blank=True, help_text='Category for tax calculation (e.g., standard, reduced, zero)', max_length=50, verbose_name='Tax Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='products', to='accounting.tax', verbose_name='Taxes'),
        ),
    ]
