# Generated by Django 4.2 on 2025-07-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_product_fiscal_position_product_tax_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for categorization and sync control', max_length=255, verbose_name='Tags'),
        ),
    ]
