# Generated by Django 4.2 on 2025-06-23 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_remove_tiendanubeproductmapping_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaNubeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=50, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('api_url', models.URLField(default='https://api.tiendanube.com/v1')),
                ('auto_sync', models.BooleanField(default=True, verbose_name='Auto Sync')),
                ('sync_interval', models.IntegerField(default=30, help_text='Interval in minutes for auto-sync.', verbose_name='Sync Interval')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('sync_products', models.BooleanField(default=True, verbose_name='Sync Products')),
                ('sync_stock', models.BooleanField(default=True, verbose_name='Sync Stock')),
                ('sync_variants', models.BooleanField(default=True, verbose_name='Sync Variants')),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_active', models.BooleanField(default=True, verbose_name='Webhook Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TiendaNube Configuration',
                'verbose_name_plural': 'TiendaNube Configurations',
            },
        ),
        migrations.CreateModel(
            name='TiendaNubeSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('product', 'Product'), ('stock', 'Stock'), ('variant', 'Variant'), ('webhook', 'Webhook'), ('full', 'Full Sync')], max_length=20, verbose_name='Sync Type')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial')], max_length=20, verbose_name='Status')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_success', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendanube.tiendanubeconfig')),
            ],
            options={
                'verbose_name': 'TiendaNube Sync Log',
                'verbose_name_plural': 'TiendaNube Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TiendaNubeProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiendanube_id', models.BigIntegerField(unique=True)),
                ('tiendanube_variant_id', models.BigIntegerField(blank=True, null=True)),
                ('tiendanube_handle', models.CharField(blank=True, max_length=255)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error'), ('conflict', 'Conflict')], default='pending', max_length=20, verbose_name='Sync Status')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sync Enabled')),
                ('sync_price', models.BooleanField(default=True, verbose_name='Sync Price')),
                ('sync_stock', models.BooleanField(default=True, verbose_name='Sync Stock')),
                ('sync_description', models.BooleanField(default=True, verbose_name='Sync Description')),
                ('error_message', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name': 'TiendaNube Product Mapping',
                'verbose_name_plural': 'TiendaNube Product Mappings',
            },
        ),
    ]
