# Generated by Django 4.2 on 2025-07-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaNubeCondVentaMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100, unique=True, verbose_name='Método de pago Tiendanube')),
                ('adminet_codigo', models.IntegerField(verbose_name='Código condición de venta administraNET')),
                ('adminet_descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción administraNET')),
                ('activo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapeo condición de venta Tiendanube',
                'verbose_name_plural': 'Mapeos condiciones de venta Tiendanube',
                'ordering': ['payment_method'],
            },
        ),
    ]
