# Generated by Django 4.2 on 2025-07-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube', '0002_tiendanubecondventamap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TiendaNubeCondVentaMap',
        ),
        migrations.RemoveField(
            model_name='tiendanubecustomermapping',
            name='client',
        ),
        migrations.RemoveField(
            model_name='tiendanubeordermapping',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='tiendanubeproductmapping',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tiendanubeproductrestockpolicy',
            name='destination_warehouse',
        ),
        migrations.RemoveField(
            model_name='tiendanubeproductrestockpolicy',
            name='notify_users',
        ),
        migrations.RemoveField(
            model_name='tiendanubeproductrestockpolicy',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tiendanubeproductrestockpolicy',
            name='source_warehouse',
        ),
        migrations.RemoveField(
            model_name='tiendanuberestocklog',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tiendanuberestocklog',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='tiendanuberestocklog',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='tiendanuberestocklog',
            name='stock_move',
        ),
        migrations.RemoveField(
            model_name='tiendanuberestockrule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tiendanuberestockrule',
            name='destination_warehouse',
        ),
        migrations.RemoveField(
            model_name='tiendanuberestockrule',
            name='notify_users',
        ),
        migrations.RemoveField(
            model_name='tiendanuberestockrule',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tiendanuberestockrule',
            name='source_warehouse',
        ),
        migrations.RemoveField(
            model_name='tiendanubesynclog',
            name='config',
        ),
        migrations.DeleteModel(
            name='TiendaNubeConfig',
        ),
        migrations.DeleteModel(
            name='TiendaNubeCustomerMapping',
        ),
        migrations.DeleteModel(
            name='TiendaNubeOrderMapping',
        ),
        migrations.DeleteModel(
            name='TiendaNubeProductMapping',
        ),
        migrations.DeleteModel(
            name='TiendaNubeProductRestockPolicy',
        ),
        migrations.DeleteModel(
            name='TiendaNubeRestockLog',
        ),
        migrations.DeleteModel(
            name='TiendaNubeRestockRule',
        ),
        migrations.DeleteModel(
            name='TiendaNubeSyncLog',
        ),
    ]
