# Generated by Django 4.2 on 2025-07-10 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0016_add_tags_to_product'),
        ('tiendanube', '0002_tiendanube_integration_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaNubeProductRestockPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('policy_type', models.CharField(choices=[('manual', 'Manual Configuration'), ('rule_based', 'Rule Based'), ('intelligent', 'Intelligent (AI)')], default='manual', max_length=20, verbose_name='Policy Type')),
                ('action_type', models.CharField(choices=[('transfer', 'Internal Transfer'), ('purchase', 'Purchase Order'), ('notification', 'Notification Only'), ('combined', 'Combined Actions')], default='transfer', max_length=20, verbose_name='Action Type')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Minimum stock level to trigger restock', max_digits=10, verbose_name='Restock Threshold')),
                ('restock_quantity', models.DecimalField(decimal_places=2, help_text='Quantity to restock when threshold is reached', max_digits=10, verbose_name='Restock Quantity')),
                ('max_stock_level', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum stock level to maintain (optional)', max_digits=10, null=True, verbose_name='Maximum Stock Level')),
                ('safety_stock', models.DecimalField(blank=True, decimal_places=2, help_text='Safety stock level (optional)', max_digits=10, null=True, verbose_name='Safety Stock')),
                ('notify_on_restock', models.BooleanField(default=True, verbose_name='Notify on Restock')),
                ('notify_email', models.EmailField(blank=True, max_length=254, verbose_name='Notification Email')),
                ('lead_time_days', models.IntegerField(default=1, help_text='Expected lead time for restock', verbose_name='Lead Time (Days)')),
                ('demand_forecast_days', models.IntegerField(default=7, help_text='Days to forecast demand', verbose_name='Demand Forecast (Days)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_restock_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Restock Date')),
                ('restock_count', models.IntegerField(default=0, verbose_name='Restock Count')),
                ('destination_warehouse', models.ForeignKey(blank=True, help_text='Warehouse to transfer stock to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_policy_destination', to='inventory.warehouse', verbose_name='Destination Warehouse')),
                ('notify_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Notify Users')),
                ('product', models.OneToOneField(help_text='Product to apply this restock policy', on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
                ('source_warehouse', models.ForeignKey(blank=True, help_text='Warehouse to transfer stock from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_policy_source', to='inventory.warehouse', verbose_name='Source Warehouse')),
            ],
            options={
                'verbose_name': 'Tiendanube Product Restock Policy',
                'verbose_name_plural': 'Tiendanube Product Restock Policies',
                'ordering': ['product__name'],
            },
        ),
    ]
