# Generated by Django 4.2 on 2025-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaNubeClienteMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiendanube_email', models.EmailField(max_length=254, unique=True, verbose_name='Email cliente Tiendanube')),
                ('adminet_idcliente', models.IntegerField(verbose_name='ID cliente administraNET')),
                ('adminet_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre cliente administraNET')),
                ('adminet_documento', models.CharField(blank=True, max_length=50, verbose_name='Documento cliente administraNET')),
                ('activo', models.BooleanField(default=True, verbose_name='Sincronización activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapeo cliente Tiendanube',
                'verbose_name_plural': 'Mapeos clientes Tiendanube',
                'ordering': ['tiendanube_email'],
            },
        ),
    ]
