# Generated by Django 4.2 on 2025-07-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube', '0005_tiendanubeclientemap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiendanubeclientemap',
            old_name='adminet_idcliente',
            new_name='adminet_codigo',
        ),
    ]
