# Generated by Django 4.2 on 2025-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube', '0006_auto_20250728_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendanubeclientemap',
            name='adminet_codigo',
            field=models.IntegerField(verbose_name='Código cliente administraNET'),
        ),
    ]
