# Generated by Django 4.2 on 2025-07-28 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube', '0007_unified_customer_sync_models'),
        ('sales', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaNubeUnifiedCustomerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiendanube_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Tiendanube ID')),
                ('tiendanube_email', models.EmailField(unique=True, verbose_name='Tiendanube Email')),
                ('tiendanube_document', models.CharField(blank=True, max_length=50, verbose_name='Tiendanube Document')),
                ('adminet_codigo', models.IntegerField(blank=True, null=True, verbose_name='AdministraNET Code')),
                ('adminet_nombre', models.CharField(blank=True, max_length=255, verbose_name='AdministraNET Name')),
                ('adminet_documento', models.CharField(blank=True, max_length=50, verbose_name='AdministraNET Document')),
                ('sync_direction', models.CharField(choices=[('bidirectional', 'Bidirectional'), ('tiendanube_to_synap', 'Tiendanube → Synap'), ('synap_to_tiendanube', 'Synap → Tiendanube'), ('adminet_only', 'AdministraNET Only')], default='bidirectional', max_length=30, verbose_name='Sync Direction')),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error'), ('conflict', 'Conflict')], default='pending', max_length=20, verbose_name='Sync Status')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sync Enabled')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('synap_client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.client', verbose_name='Synap Client')),
                ('synap_contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contact', verbose_name='Synap Contact')),
            ],
            options={
                'verbose_name': 'Unified Customer Mapping',
                'verbose_name_plural': 'Unified Customer Mappings',
                'ordering': ['tiendanube_email'],
            },
        ),
        migrations.CreateModel(
            name='TiendaNubeUnifiedSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('customer_sync', 'Customer Sync'), ('mapping_create', 'Mapping Create'), ('mapping_update', 'Mapping Update'), ('mapping_delete', 'Mapping Delete'), ('adminet_sync', 'AdministraNET Sync')], max_length=20, verbose_name='Sync Type')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial'), ('warning', 'Warning')], max_length=20, verbose_name='Status')),
                ('platform', models.CharField(choices=[('tiendanube', 'Tiendanube'), ('synap', 'Synap'), ('adminet', 'AdministraNET')], max_length=20, verbose_name='Platform')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('items_processed', models.IntegerField(default=0, verbose_name='Items Processed')),
                ('items_success', models.IntegerField(default=0, verbose_name='Items Success')),
                ('items_failed', models.IntegerField(default=0, verbose_name='Items Failed')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendanube.tiendanubeunifiedcustomermapping', verbose_name='Customer Mapping')),
            ],
            options={
                'verbose_name': 'Unified Sync Log',
                'verbose_name_plural': 'Unified Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TiendaNubeUnifiedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Configuration Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sync_mode', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('scheduled', 'Scheduled')], default='manual', max_length=20, verbose_name='Sync Mode')),
                ('tiendanube_store_id', models.CharField(blank=True, max_length=50, verbose_name='Tiendanube Store ID')),
                ('tiendanube_access_token', models.CharField(blank=True, max_length=255, verbose_name='Tiendanube Access Token')),
                ('tiendanube_api_url', models.URLField(default='https://api.tiendanube.com/v1', verbose_name='Tiendanube API URL')),
                ('adminet_host', models.CharField(blank=True, max_length=255, verbose_name='AdministraNET Host')),
                ('adminet_port', models.IntegerField(default=3306, verbose_name='AdministraNET Port')),
                ('adminet_database', models.CharField(blank=True, max_length=100, verbose_name='AdministraNET Database')),
                ('adminet_user', models.CharField(blank=True, max_length=100, verbose_name='AdministraNET User')),
                ('adminet_password', models.CharField(blank=True, max_length=255, verbose_name='AdministraNET Password')),
                ('sync_interval', models.IntegerField(default=30, verbose_name='Sync Interval (minutes)')),
                ('batch_size', models.IntegerField(default=100, verbose_name='Batch Size')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Max Retries')),
                ('notify_on_error', models.BooleanField(default=True, verbose_name='Notify on Error')),
                ('notify_email', models.EmailField(blank=True, verbose_name='Notification Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
            ],
            options={
                'verbose_name': 'Unified Configuration',
                'verbose_name_plural': 'Unified Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tiendanubeunifiedcustomermapping',
            index=models.Index(fields=['tiendanube_email'], name='tiendanube_tiendanube_email_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendanubeunifiedcustomermapping',
            index=models.Index(fields=['adminet_codigo'], name='tiendanube_adminet_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendanubeunifiedcustomermapping',
            index=models.Index(fields=['sync_status'], name='tiendanube_sync_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendanubeunifiedcustomermapping',
            index=models.Index(fields=['sync_enabled'], name='tiendanube_sync_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendanubeunifiedsynclog',
            index=models.Index(fields=['sync_type'], name='tiendanube_sync_type_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendanubeunifiedsynclog',
            index=models.Index(fields=['status'], name='tiendanube_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendanubeunifiedsynclog',
            index=models.Index(fields=['platform'], name='tiendanube_platform_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendanubeunifiedsynclog',
            index=models.Index(fields=['started_at'], name='tiendanube_started_at_idx'),
        ),
    ] 