# Generated by Django 4.2 on 2025-07-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube', '0008_create_unified_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tiendanubeunifiedcustomermapping',
            new_name='tiendanube__tiendan_edbce7_idx',
            old_name='tiendanube_tiendanube_email_idx',
        ),
        migrations.RenameIndex(
            model_name='tiendanubeunifiedcustomermapping',
            new_name='tiendanube__adminet_3ebe74_idx',
            old_name='tiendanube_adminet_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='tiendanubeunifiedcustomermapping',
            new_name='tiendanube__sync_st_aa3c5c_idx',
            old_name='tiendanube_sync_status_idx',
        ),
        migrations.RenameIndex(
            model_name='tiendanubeunifiedcustomermapping',
            new_name='tiendanube__sync_en_a967d0_idx',
            old_name='tiendanube_sync_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='tiendanubeunifiedsynclog',
            new_name='tiendanube__sync_ty_ab2bef_idx',
            old_name='tiendanube_sync_type_idx',
        ),
        migrations.RenameIndex(
            model_name='tiendanubeunifiedsynclog',
            new_name='tiendanube__status_08baab_idx',
            old_name='tiendanube_status_idx',
        ),
        migrations.RenameIndex(
            model_name='tiendanubeunifiedsynclog',
            new_name='tiendanube__platfor_b4bad3_idx',
            old_name='tiendanube_platform_idx',
        ),
        migrations.RenameIndex(
            model_name='tiendanubeunifiedsynclog',
            new_name='tiendanube__started_8fabcd_idx',
            old_name='tiendanube_started_at_idx',
        ),
    ]
