# Generated by Django 4.2 on 2025-07-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube', '0009_rename_tiendanube_tiendanube_email_idx_tiendanube__tiendan_edbce7_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TiendaNubeAdminetConfig',
        ),
        migrations.DeleteModel(
            name='TiendaNubeClienteMap',
        ),
        migrations.DeleteModel(
            name='TiendaNubeCondVentaMap',
        ),
        migrations.DeleteModel(
            name='TiendaNubeUnifiedConfig',
        ),
        migrations.RemoveField(
            model_name='tiendanubeunifiedsynclog',
            name='mapping',
        ),
        migrations.DeleteModel(
            name='TiendaNubeUnifiedCustomerMapping',
        ),
        migrations.DeleteModel(
            name='TiendaNubeUnifiedSyncLog',
        ),
    ]
