# Generated by Django 4.2 on 2025-11-10 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_increase_permiso_codigo_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique identifier used to query the report via API.', max_length=128, verbose_name='Slug')),
                ('name', models.CharField(help_text='Friendly name displayed in the catalog.', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Short description, supports markdown for highlights.', verbose_name='Description')),
                ('category', models.CharField(choices=[('operational', 'Operational'), ('managerial', 'Managerial')], default='operational', max_length=24, verbose_name='Category')),
                ('version', models.CharField(default='1.0.0', help_text='Semantic version of the definition for cache invalidation.', max_length=16, verbose_name='Version')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Declarative configuration (metrics, dimensions, datasource).', verbose_name='Configuration')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata such as owners, tags or compliance info.', verbose_name='Metadata')),
                ('refresh_interval', models.CharField(choices=[('realtime', 'Near real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='Recommended refresh cadence for aggregates.', max_length=16, verbose_name='Refresh interval')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive definitions are hidden from catalogs and APIs.', verbose_name='Is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('empresa', models.ForeignKey(blank=True, help_text='Company that owns this report definition. Null means global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_definitions', to='core.empresa', verbose_name='Company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Report definition',
                'verbose_name_plural': 'Report definitions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ReportWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Widget name')),
                ('widget_type', models.CharField(help_text='Type identifier, e.g. d3-line, d3-waterfall, pivot-table.', max_length=64, verbose_name='Type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Grid layout definition (cols, rows, responsive breakpoints).', verbose_name='Layout')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Visualization settings and bindings for the widget.', verbose_name='Configuration')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.reportdefinition', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Report widget',
                'verbose_name_plural': 'Report widgets',
                'ordering': ('report', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ReportExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Executed at')),
                ('status', models.CharField(default='success', help_text='Execution result status.', max_length=32, verbose_name='Status')),
                ('filters_snapshot', models.JSONField(blank=True, default=dict, help_text='Filters applied when the report was executed.', verbose_name='Filters snapshot')),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Total execution duration in milliseconds.', verbose_name='Execution time (ms)')),
                ('notes', models.TextField(blank=True, help_text='Optional information about the execution.', verbose_name='Notes')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_execution_logs', to=settings.AUTH_USER_MODEL, verbose_name='Executed by')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='reports.reportdefinition', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Report execution log',
                'verbose_name_plural': 'Report execution logs',
                'ordering': ('-executed_at',),
            },
        ),
        migrations.CreateModel(
            name='ReportDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Identifier to expose saved dashboards in URLs.', max_length=128, verbose_name='Slug')),
                ('category', models.CharField(choices=[('operational', 'Operational'), ('managerial', 'Managerial')], default='operational', max_length=24, verbose_name='Category')),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Serialized layout with widget ordering and sizing.', verbose_name='Layout')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Default filters')),
                ('is_shared', models.BooleanField(default=False, help_text='Shared dashboards are visible to roles with matching permissions.', verbose_name='Shared')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_dashboards', to='core.empresa', verbose_name='Company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Report dashboard',
                'verbose_name_plural': 'Report dashboards',
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='reportexecutionlog',
            index=models.Index(fields=['executed_at'], name='reports_execution_date_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecutionlog',
            index=models.Index(fields=['status'], name='reports_execution_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['empresa', 'category'], name='reports_by_company_cat'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['slug'], name='reports_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['is_active'], name='reports_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportdefinition',
            unique_together={('empresa', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='reportdashboard',
            unique_together={('empresa', 'slug')},
        ),
    ]
