# Generated by Django 4.2 on 2025-07-11 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_usuarioextendido_branches_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('layout_config', models.JSONField(default=dict, verbose_name='Layout Configuration')),
                ('data_sources', models.JSONField(default=list, verbose_name='Data Sources')),
                ('filters', models.JSONField(default=dict, verbose_name='Filters')),
                ('branding', models.JSONField(default=dict, verbose_name='Branding')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('layout_schema', models.JSONField(verbose_name='Layout Schema')),
                ('default_data', models.JSONField(default=dict, verbose_name='Default Data')),
                ('styling', models.JSONField(default=dict, verbose_name='Styling')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_system', models.BooleanField(default=False, verbose_name='System Template')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20, verbose_name='Frequency')),
                ('cron_expression', models.CharField(blank=True, max_length=200, verbose_name='Cron Expression')),
                ('recipients', models.JSONField(verbose_name='Recipients')),
                ('export_format', models.CharField(default='pdf', max_length=10, verbose_name='Export Format')),
                ('subject_template', models.CharField(max_length=200, verbose_name='Subject Template')),
                ('message_template', models.TextField(blank=True, verbose_name='Message Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Next Run')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('component_type', models.CharField(choices=[('chart', 'Chart'), ('table', 'Table'), ('kpi', 'KPI'), ('text', 'Text'), ('image', 'Image'), ('header', 'Header'), ('footer', 'Footer')], max_length=20, verbose_name='Component Type')),
                ('configuration', models.JSONField(verbose_name='Configuration')),
                ('data_source', models.CharField(blank=True, max_length=200, verbose_name='Data Source')),
                ('styling', models.JSONField(default=dict, verbose_name='Styling')),
                ('position', models.JSONField(verbose_name='Position')),
                ('z_index', models.IntegerField(default=0, verbose_name='Z-Index')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.reportcomponent', verbose_name='Parent')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='reports.report', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Report Component',
                'verbose_name_plural': 'Report Components',
                'ordering': ['z_index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='Template'),
        ),
    ]
