# Generated by Django 4.2 on 2025-07-12 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reporttemplate_empresa_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('pptx', 'PowerPoint'), ('html', 'HTML')], max_length=10, verbose_name='Export Format')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='File Path')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='File Size')),
                ('export_config', models.JSONField(default=dict, verbose_name='Export Configuration')),
                ('branding_config', models.JSONField(default=dict, verbose_name='Branding Configuration')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('export_date', models.DateTimeField(auto_now_add=True, verbose_name='Export Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'ordering': ['-export_date'],
            },
        ),
    ]
