# Generated by Django 4.2 on 2025-11-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportworkspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdefinition',
            name='refresh_interval',
            field=models.CharField(choices=[('realtime', 'Casi en tiempo real'), ('hourly', 'Horario'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='daily', help_text='Recommended refresh cadence for aggregates.', max_length=16, verbose_name='Refresh interval'),
        ),
    ]
