# Generated by Django 4.2 on 2025-11-12 14:50
# Modified to check table and field existence before altering

from django.db import migrations, models


def alter_refresh_interval_field(apps, schema_editor):
    """Modifica el campo refresh_interval si la tabla y el campo existen."""
    from django.db import connection
    cursor = connection.cursor()
    
    try:
        # Verificar si la tabla existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinition'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            print("⚠️  Tabla reports_reportdefinition no existe, saltando modificación de refresh_interval")
            return
        
        # Verificar si el campo existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinition'
                AND column_name = 'refresh_interval'
            );
        """)
        field_exists = cursor.fetchone()[0]
        
        if not field_exists:
            print("⚠️  Campo refresh_interval no existe, saltando modificación")
            return
        
        # Verificar el tipo actual del campo
        cursor.execute("""
            SELECT data_type, character_maximum_length
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'reports_reportdefinition'
            AND column_name = 'refresh_interval'
        """)
        field_info = cursor.fetchone()
        
        if field_info:
            current_type = field_info[0]
            current_length = field_info[1]
            
            # Si ya es VARCHAR(16), no hay nada que cambiar (solo las opciones en Django)
            # Las opciones de choices son solo a nivel de Django, no afectan la BD
            print("✅ Campo refresh_interval existe, opciones actualizadas en modelo Django")
        else:
            print("⚠️  No se pudo obtener información del campo")
        
    except Exception as e:
        print(f"⚠️  Error verificando/modificando campo refresh_interval: {e}")
    finally:
        cursor.close()


def reverse_alter_refresh_interval_field(apps, schema_editor):
    """Reversión: no hay cambios en la BD, solo en el modelo Django."""
    # AlterField solo cambia las opciones de choices, no modifica la estructura de la BD
    # Por lo tanto, no hay nada que revertir a nivel de base de datos
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportworkspace'),
    ]

    operations = [
        migrations.RunPython(alter_refresh_interval_field, reverse_alter_refresh_interval_field),
    ]
