# Generated by Django 4.2 on 2025-11-25 21:32
# Modified to check table existence before adding field

from django.db import migrations, models


def add_is_visible_field(apps, schema_editor):
    """Agrega el campo is_visible si la tabla existe."""
    from django.db import connection
    cursor = connection.cursor()
    
    try:
        # Verificar si la tabla existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinition'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            print("⚠️  Tabla reports_reportdefinition no existe, saltando agregado de campo is_visible")
            return
        
        # Verificar si el campo ya existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinition'
                AND column_name = 'is_visible'
            );
        """)
        field_exists = cursor.fetchone()[0]
        
        if field_exists:
            print("⚠️  Campo is_visible ya existe, saltando")
            return
        
        # Agregar el campo
        cursor.execute("""
            ALTER TABLE reports_reportdefinition 
            ADD COLUMN is_visible BOOLEAN DEFAULT TRUE NOT NULL;
        """)
        print("✅ Campo is_visible agregado exitosamente")
        
    except Exception as e:
        print(f"⚠️  Error agregando campo is_visible: {e}")
    finally:
        cursor.close()


def remove_is_visible_field(apps, schema_editor):
    """Elimina el campo is_visible si existe."""
    from django.db import connection
    cursor = connection.cursor()
    
    try:
        # Verificar si la tabla existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinition'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            print("⚠️  Tabla reports_reportdefinition no existe, saltando eliminación de campo is_visible")
            return
        
        # Verificar si el campo existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinition'
                AND column_name = 'is_visible'
            );
        """)
        field_exists = cursor.fetchone()[0]
        
        if not field_exists:
            print("⚠️  Campo is_visible no existe, saltando eliminación")
            return
        
        # Eliminar el campo
        cursor.execute("""
            ALTER TABLE reports_reportdefinition 
            DROP COLUMN is_visible;
        """)
        print("✅ Campo is_visible eliminado exitosamente")
        
    except Exception as e:
        print(f"⚠️  Error eliminando campo is_visible: {e}")
    finally:
        cursor.close()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_translate_cash_flow_detailed_movements'),
    ]

    operations = [
        migrations.RunPython(add_is_visible_field, remove_is_visible_field),
    ]
