# Generated by Django 4.2 on 2025-11-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_translate_cash_flow_detailed_movements'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdefinition',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Visible reports are shown to users with Supervisor role. Only the supervisor user can toggle this.', verbose_name='Is visible'),
        ),
    ]
