# Generated by Django 4.2 on 2025-11-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_add_is_visible_to_report_definition'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['is_visible'], name='reports_visible_idx'),
        ),
    ]
