# Generated by Django 4.2 on 2025-11-25 21:34
# Modified to check table existence before adding index

from django.db import migrations, models


def add_is_visible_index(apps, schema_editor):
    """Agrega el índice is_visible si la tabla y el campo existen."""
    from django.db import connection
    cursor = connection.cursor()
    
    try:
        # Verificar si la tabla existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinition'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            print("⚠️  Tabla reports_reportdefinition no existe, saltando agregado de índice is_visible")
            return
        
        # Verificar si el campo existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinition'
                AND column_name = 'is_visible'
            );
        """)
        field_exists = cursor.fetchone()[0]
        
        if not field_exists:
            print("⚠️  Campo is_visible no existe, saltando agregado de índice")
            return
        
        # Verificar si el índice ya existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM pg_indexes 
                WHERE schemaname = 'public' 
                AND tablename = 'reports_reportdefinition'
                AND indexname = 'reports_visible_idx'
            );
        """)
        index_exists = cursor.fetchone()[0]
        
        if index_exists:
            print("⚠️  Índice reports_visible_idx ya existe, saltando")
            return
        
        # Agregar el índice
        cursor.execute("""
            CREATE INDEX reports_visible_idx 
            ON reports_reportdefinition (is_visible);
        """)
        print("✅ Índice reports_visible_idx agregado exitosamente")
        
    except Exception as e:
        print(f"⚠️  Error agregando índice is_visible: {e}")
    finally:
        cursor.close()


def remove_is_visible_index(apps, schema_editor):
    """Elimina el índice is_visible si existe."""
    from django.db import connection
    cursor = connection.cursor()
    
    try:
        # Verificar si el índice existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM pg_indexes 
                WHERE schemaname = 'public' 
                AND tablename = 'reports_reportdefinition'
                AND indexname = 'reports_visible_idx'
            );
        """)
        index_exists = cursor.fetchone()[0]
        
        if not index_exists:
            print("⚠️  Índice reports_visible_idx no existe, saltando eliminación")
            return
        
        # Eliminar el índice
        cursor.execute("""
            DROP INDEX IF EXISTS reports_visible_idx;
        """)
        print("✅ Índice reports_visible_idx eliminado exitosamente")
        
    except Exception as e:
        print(f"⚠️  Error eliminando índice is_visible: {e}")
    finally:
        cursor.close()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_add_is_visible_to_report_definition'),
    ]

    operations = [
        migrations.RunPython(add_is_visible_index, remove_is_visible_index),
    ]
