# Generated by Django 4.2 on 2025-12-12 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_reportdefinitionversion_if_not_exists(apps, schema_editor):
    """Crea la tabla ReportDefinitionVersion solo si no existe (idempotente)."""
    from django.db import connection
    cursor = connection.cursor()
    
    try:
        # Verificar si ReportDefinitionVersion existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinitionversion'
            );
        """)
        version_exists = cursor.fetchone()[0]
        
        # Verificar si auth_user existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'auth_user'
            );
        """)
        auth_user_exists = cursor.fetchone()[0]
        
        if not version_exists:
            # Crear ReportDefinitionVersion usando SQL directo
            # Si auth_user no existe, crear la tabla sin la foreign key a created_by_id
            if auth_user_exists:
                cursor.execute("""
                    CREATE TABLE reports_reportdefinitionversion (
                        id BIGSERIAL NOT NULL PRIMARY KEY,
                        version_number INTEGER NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        config JSONB NOT NULL DEFAULT '{}'::jsonb,
                        change_summary TEXT NOT NULL DEFAULT '',
                        report_id BIGINT NOT NULL,
                        created_by_id BIGINT NULL,
                        CONSTRAINT reports_reportdefinitionversion_report_id_fkey 
                            FOREIGN KEY (report_id) REFERENCES reports_reportdefinition(id) ON DELETE CASCADE,
                        CONSTRAINT reports_reportdefinitionversion_created_by_id_fkey 
                            FOREIGN KEY (created_by_id) REFERENCES auth_user(id) ON DELETE SET NULL,
                        CONSTRAINT reports_reportdefinitionversion_report_id_version_number_uniq 
                            UNIQUE (report_id, version_number)
                    );
                """)
            else:
                # Crear sin foreign key a auth_user (se agregará después cuando auth_user exista)
                cursor.execute("""
                    CREATE TABLE reports_reportdefinitionversion (
                        id BIGSERIAL NOT NULL PRIMARY KEY,
                        version_number INTEGER NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        config JSONB NOT NULL DEFAULT '{}'::jsonb,
                        change_summary TEXT NOT NULL DEFAULT '',
                        report_id BIGINT NOT NULL,
                        created_by_id BIGINT NULL,
                        CONSTRAINT reports_reportdefinitionversion_report_id_fkey 
                            FOREIGN KEY (report_id) REFERENCES reports_reportdefinition(id) ON DELETE CASCADE,
                        CONSTRAINT reports_reportdefinitionversion_report_id_version_number_uniq 
                            UNIQUE (report_id, version_number)
                    );
                """)
            
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS reports_version_idx ON reports_reportdefinitionversion(report_id, version_number);
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS reports_version_created_idx ON reports_reportdefinitionversion(report_id, created_at DESC);
            """)
            print("✅ Tabla reports_reportdefinitionversion creada")
        else:
            # La tabla ya existe, verificar si necesita la foreign key a auth_user
            if auth_user_exists:
                # Verificar si la foreign key ya existe
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM information_schema.table_constraints 
                        WHERE table_schema = 'public' 
                        AND table_name = 'reports_reportdefinitionversion'
                        AND constraint_name = 'reports_reportdefinitionversion_created_by_id_fkey'
                    );
                """)
                fk_exists = cursor.fetchone()[0]
                
                if not fk_exists:
                    # Agregar la foreign key si no existe
                    try:
                        cursor.execute("""
                            ALTER TABLE reports_reportdefinitionversion
                            ADD CONSTRAINT reports_reportdefinitionversion_created_by_id_fkey 
                            FOREIGN KEY (created_by_id) REFERENCES auth_user(id) ON DELETE SET NULL;
                        """)
                        print("✅ Foreign key a auth_user agregada a reports_reportdefinitionversion")
                    except Exception as fk_error:
                        print(f"⚠️  No se pudo agregar foreign key a auth_user: {fk_error}")
            print("⚠️  Tabla reports_reportdefinitionversion ya existe, saltando creación")
            
    except Exception as e:
        print(f"⚠️  Error verificando/creando tabla ReportDefinitionVersion: {e}")
        import traceback
        traceback.print_exc()
    finally:
        cursor.close()


def reverse_create_reportdefinitionversion(apps, schema_editor):
    """No hacer nada en reversa - la tabla puede ser usada por otras migraciones."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_increase_permiso_codigo_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0016_add_sales_summary_report'),
    ]

    operations = [
        # Solo crear ReportDefinitionVersion si no existe
        # Las demás operaciones (is_visible, refresh_interval, ReportWorkspace) ya fueron hechas en migraciones anteriores
        migrations.RunPython(create_reportdefinitionversion_if_not_exists, reverse_create_reportdefinitionversion),
    ]
