# Generated by Django 4.2 on 2025-12-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_add_ventas_netas_v2_report'),
        ('reports', '0019_remove_ventas_netas_v2_report'),
    ]

    operations = [
    ]
