# Generated by Django 4.2 on 2025-12-12 22:06

from django.db import migrations, models


def add_show_in_catalog_if_not_exists(apps, schema_editor):
    """Agrega la columna show_in_catalog solo si no existe (idempotente)."""
    from django.db import connection
    cursor = connection.cursor()
    
    try:
        # Verificar si la columna ya existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinition'
                AND column_name = 'show_in_catalog'
            );
        """)
        column_exists = cursor.fetchone()[0]
        
        if not column_exists:
            # Agregar la columna
            cursor.execute("""
                ALTER TABLE reports_reportdefinition 
                ADD COLUMN show_in_catalog boolean DEFAULT true NOT NULL;
            """)
            print("✅ Columna show_in_catalog agregada a reports_reportdefinition")
        else:
            print("⚠️  Columna show_in_catalog ya existe, saltando creación")
            
    except Exception as e:
        print(f"⚠️  Error verificando/agregando columna show_in_catalog: {e}")
        import traceback
        traceback.print_exc()
    finally:
        cursor.close()


def reverse_add_show_in_catalog(apps, schema_editor):
    """Elimina la columna show_in_catalog si existe."""
    from django.db import connection
    cursor = connection.cursor()
    
    try:
        # Verificar si la columna existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinition'
                AND column_name = 'show_in_catalog'
            );
        """)
        column_exists = cursor.fetchone()[0]
        
        if column_exists:
            cursor.execute("""
                ALTER TABLE reports_reportdefinition 
                DROP COLUMN show_in_catalog;
            """)
            print("✅ Columna show_in_catalog eliminada de reports_reportdefinition")
    except Exception as e:
        print(f"⚠️  Error eliminando columna show_in_catalog: {e}")
    finally:
        cursor.close()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_merge_20251212_1354'),
    ]

    operations = [
        migrations.RunPython(add_show_in_catalog_if_not_exists, reverse_add_show_in_catalog),
    ]






