# Generated by Django 4.2 on 2025-12-12 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_report_template_table_if_not_exists(apps, schema_editor):
    """Crea la tabla ReportTemplate solo si no existe (idempotente)."""
    from django.db import connection
    cursor = connection.cursor()
    
    try:
        # Verificar si la tabla ya existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reporttemplate'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            # Verificar si auth_user existe antes de crear la foreign key
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'auth_user'
                );
            """)
            auth_user_exists = cursor.fetchone()[0]
            
            # Crear la tabla ReportTemplate usando SQL directo
            if auth_user_exists:
                cursor.execute("""
                    CREATE TABLE reports_reporttemplate (
                        id BIGSERIAL NOT NULL PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        description TEXT NOT NULL DEFAULT '',
                        category VARCHAR(24) NOT NULL DEFAULT 'operational',
                        config JSONB NOT NULL DEFAULT '{}'::jsonb,
                        widgets JSONB NOT NULL DEFAULT '[]'::jsonb,
                        is_system BOOLEAN NOT NULL DEFAULT false,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        created_by_id BIGINT NULL,
                        CONSTRAINT reports_reporttemplate_created_by_id_fkey 
                            FOREIGN KEY (created_by_id) REFERENCES auth_user(id) ON DELETE SET NULL
                    );
                """)
            else:
                # Crear sin foreign key a auth_user (se agregará después cuando auth_user exista)
                cursor.execute("""
                    CREATE TABLE reports_reporttemplate (
                        id BIGSERIAL NOT NULL PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        description TEXT NOT NULL DEFAULT '',
                        category VARCHAR(24) NOT NULL DEFAULT 'operational',
                        config JSONB NOT NULL DEFAULT '{}'::jsonb,
                        widgets JSONB NOT NULL DEFAULT '[]'::jsonb,
                        is_system BOOLEAN NOT NULL DEFAULT false,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        created_by_id BIGINT NULL
                    );
                """)
            
            # Crear índices
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS reports_reporttemplate_is_system_idx 
                ON reports_reporttemplate(is_system, created_at DESC, name);
            """)
            print("✅ Tabla reports_reporttemplate creada")
        else:
            # La tabla ya existe, verificar y agregar campos faltantes
            # Verificar si el campo config existe
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = 'reports_reporttemplate'
                    AND column_name = 'config'
                );
            """)
            config_exists = cursor.fetchone()[0]
            
            if not config_exists:
                try:
                    cursor.execute("""
                        ALTER TABLE reports_reporttemplate 
                        ADD COLUMN config JSONB NOT NULL DEFAULT '{}'::jsonb;
                    """)
                    print("✅ Columna config agregada a reports_reporttemplate")
                except Exception as config_error:
                    print(f"⚠️  No se pudo agregar columna config: {config_error}")
            
            # Verificar si el campo widgets existe
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = 'reports_reporttemplate'
                    AND column_name = 'widgets'
                );
            """)
            widgets_exists = cursor.fetchone()[0]
            
            if not widgets_exists:
                try:
                    cursor.execute("""
                        ALTER TABLE reports_reporttemplate 
                        ADD COLUMN widgets JSONB NOT NULL DEFAULT '[]'::jsonb;
                    """)
                    print("✅ Columna widgets agregada a reports_reporttemplate")
                except Exception as widgets_error:
                    print(f"⚠️  No se pudo agregar columna widgets: {widgets_error}")
            
            # Verificar si necesita la foreign key a auth_user
            if auth_user_exists:
                # Verificar si la foreign key ya existe
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM information_schema.table_constraints 
                        WHERE table_schema = 'public' 
                        AND table_name = 'reports_reporttemplate'
                        AND constraint_name = 'reports_reporttemplate_created_by_id_fkey'
                    );
                """)
                fk_exists = cursor.fetchone()[0]
                
                if not fk_exists:
                    # Agregar la foreign key si no existe
                    try:
                        cursor.execute("""
                            ALTER TABLE reports_reporttemplate
                            ADD CONSTRAINT reports_reporttemplate_created_by_id_fkey 
                            FOREIGN KEY (created_by_id) REFERENCES auth_user(id) ON DELETE SET NULL;
                        """)
                        print("✅ Foreign key a auth_user agregada a reports_reporttemplate")
                    except Exception as fk_error:
                        print(f"⚠️  No se pudo agregar foreign key a auth_user: {fk_error}")
            print("⚠️  Tabla reports_reporttemplate ya existe, saltando creación")
            
    except Exception as e:
        print(f"⚠️  Error verificando/creando tabla ReportTemplate: {e}")
        import traceback
        traceback.print_exc()
    finally:
        cursor.close()


def reverse_create_report_template(apps, schema_editor):
    """No hacer nada en reversa - la tabla puede ser usada por otras migraciones."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_increase_permiso_codigo_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0021_add_show_in_catalog'),
    ]

    operations = [
        migrations.RunPython(create_report_template_table_if_not_exists, reverse_create_report_template),
    ]






