# Generated by Django 4.2 on 2025-12-13 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def apply_migration_0023_idempotent(apps, schema_editor):
    """Aplica la migración 0023 de forma idempotente, verificando qué ya existe."""
    from django.db import connection
    cursor = connection.cursor()
    
    try:
        # 1. Verificar y crear ReportDefinitionVersion si no existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinitionversion'
            );
        """)
        version_table_exists = cursor.fetchone()[0]
        
        if not version_table_exists:
            # La tabla ya debería existir por la migración 0018, pero por si acaso...
            print("⚠️  Tabla reports_reportdefinitionversion no existe, debería haber sido creada por migración 0018")
        else:
            print("✅ Tabla reports_reportdefinitionversion ya existe")
        
        # 2. Verificar y crear ReportWorkspace si no existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportworkspace'
            );
        """)
        workspace_table_exists = cursor.fetchone()[0]
        
        if not workspace_table_exists:
            # Verificar si auth_user existe antes de crear foreign keys
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'auth_user'
                );
            """)
            auth_user_exists = cursor.fetchone()[0]
            
            if auth_user_exists:
                cursor.execute("""
                    CREATE TABLE reports_reportworkspace (
                        id BIGSERIAL NOT NULL PRIMARY KEY,
                        name VARCHAR(128) NOT NULL DEFAULT 'Workspace',
                        items JSONB NOT NULL DEFAULT '[]'::jsonb,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        empresa_id BIGINT NULL,
                        owner_id BIGINT NOT NULL,
                        CONSTRAINT reports_reportworkspace_empresa_id_fkey 
                            FOREIGN KEY (empresa_id) REFERENCES core_empresa(id) ON DELETE CASCADE,
                        CONSTRAINT reports_reportworkspace_owner_id_fkey 
                            FOREIGN KEY (owner_id) REFERENCES auth_user(id) ON DELETE CASCADE,
                        CONSTRAINT reports_reportworkspace_owner_id_empresa_id_uniq 
                            UNIQUE (owner_id, empresa_id)
                    );
                """)
            else:
                cursor.execute("""
                    CREATE TABLE reports_reportworkspace (
                        id BIGSERIAL NOT NULL PRIMARY KEY,
                        name VARCHAR(128) NOT NULL DEFAULT 'Workspace',
                        items JSONB NOT NULL DEFAULT '[]'::jsonb,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        empresa_id BIGINT NULL,
                        owner_id BIGINT NOT NULL
                    );
                """)
            print("✅ Tabla reports_reportworkspace creada")
        else:
            print("✅ Tabla reports_reportworkspace ya existe")
        
        # 3. Verificar y agregar is_visible a ReportDefinition si no existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'reports_reportdefinition'
                AND column_name = 'is_visible'
            );
        """)
        is_visible_exists = cursor.fetchone()[0]
        
        if not is_visible_exists:
            cursor.execute("""
                ALTER TABLE reports_reportdefinition 
                ADD COLUMN is_visible BOOLEAN NOT NULL DEFAULT true;
            """)
            print("✅ Columna is_visible agregada a reports_reportdefinition")
        else:
            print("✅ Columna is_visible ya existe en reports_reportdefinition")
        
        # 4. Verificar y agregar índice reports_visible_idx si no existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM pg_indexes 
                WHERE schemaname = 'public' 
                AND tablename = 'reports_reportdefinition'
                AND indexname = 'reports_visible_idx'
            );
        """)
        visible_idx_exists = cursor.fetchone()[0]
        
        if not visible_idx_exists:
            cursor.execute("""
                CREATE INDEX reports_visible_idx ON reports_reportdefinition(is_visible);
            """)
            print("✅ Índice reports_visible_idx creado")
        else:
            print("✅ Índice reports_visible_idx ya existe")
        
        # 5. Verificar y agregar empresa_id a ReportWorkspace si no existe
        if workspace_table_exists:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = 'reports_reportworkspace'
                    AND column_name = 'empresa_id'
                );
            """)
            empresa_id_exists = cursor.fetchone()[0]
            
            if not empresa_id_exists:
                cursor.execute("""
                    ALTER TABLE reports_reportworkspace 
                    ADD COLUMN empresa_id BIGINT NULL;
                """)
                print("✅ Columna empresa_id agregada a reports_reportworkspace")
                
                # Agregar foreign key si core_empresa existe
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM information_schema.tables 
                        WHERE table_schema = 'public' 
                        AND table_name = 'core_empresa'
                    );
                """)
                core_empresa_exists = cursor.fetchone()[0]
                
                if core_empresa_exists:
                    try:
                        cursor.execute("""
                            ALTER TABLE reports_reportworkspace
                            ADD CONSTRAINT reports_reportworkspace_empresa_id_fkey 
                            FOREIGN KEY (empresa_id) REFERENCES core_empresa(id) ON DELETE CASCADE;
                        """)
                        print("✅ Foreign key empresa_id agregada a reports_reportworkspace")
                    except Exception as e:
                        print(f"⚠️  No se pudo agregar foreign key empresa_id: {e}")
            else:
                print("✅ Columna empresa_id ya existe en reports_reportworkspace")
        
        # 6. Verificar y agregar owner_id a ReportWorkspace si no existe
        if workspace_table_exists:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = 'reports_reportworkspace'
                    AND column_name = 'owner_id'
                );
            """)
            owner_id_exists = cursor.fetchone()[0]
            
            if not owner_id_exists:
                cursor.execute("""
                    ALTER TABLE reports_reportworkspace 
                    ADD COLUMN owner_id BIGINT NOT NULL DEFAULT 1;
                """)
                print("✅ Columna owner_id agregada a reports_reportworkspace")
                
                # Agregar foreign key si auth_user existe
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM information_schema.tables 
                        WHERE table_schema = 'public' 
                        AND table_name = 'auth_user'
                    );
                """)
                auth_user_exists = cursor.fetchone()[0]
                
                if auth_user_exists:
                    try:
                        cursor.execute("""
                            ALTER TABLE reports_reportworkspace
                            ADD CONSTRAINT reports_reportworkspace_owner_id_fkey 
                            FOREIGN KEY (owner_id) REFERENCES auth_user(id) ON DELETE CASCADE;
                        """)
                        print("✅ Foreign key owner_id agregada a reports_reportworkspace")
                    except Exception as e:
                        print(f"⚠️  No se pudo agregar foreign key owner_id: {e}")
            else:
                print("✅ Columna owner_id ya existe en reports_reportworkspace")
        
        # 7. Verificar y agregar unique constraint (owner_id, empresa_id) si no existe
        if workspace_table_exists:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.table_constraints 
                    WHERE table_schema = 'public' 
                    AND table_name = 'reports_reportworkspace'
                    AND constraint_name = 'reports_reportworkspace_owner_id_empresa_id_uniq'
                );
            """)
            unique_constraint_exists = cursor.fetchone()[0]
            
            if not unique_constraint_exists:
                try:
                    cursor.execute("""
                        ALTER TABLE reports_reportworkspace
                        ADD CONSTRAINT reports_reportworkspace_owner_id_empresa_id_uniq 
                        UNIQUE (owner_id, empresa_id);
                    """)
                    print("✅ Unique constraint (owner_id, empresa_id) agregado a reports_reportworkspace")
                except Exception as e:
                    print(f"⚠️  No se pudo agregar unique constraint: {e}")
            else:
                print("✅ Unique constraint (owner_id, empresa_id) ya existe en reports_reportworkspace")
        
        # 8. Verificar y agregar report_id a ReportDefinitionVersion si no existe
        if version_table_exists:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = 'reports_reportdefinitionversion'
                    AND column_name = 'report_id'
                );
            """)
            report_id_exists = cursor.fetchone()[0]
            
            if not report_id_exists:
                cursor.execute("""
                    ALTER TABLE reports_reportdefinitionversion 
                    ADD COLUMN report_id BIGINT NOT NULL DEFAULT 1;
                """)
                print("✅ Columna report_id agregada a reports_reportdefinitionversion")
                
                # Agregar foreign key
                try:
                    cursor.execute("""
                        ALTER TABLE reports_reportdefinitionversion
                        ADD CONSTRAINT reports_reportdefinitionversion_report_id_fkey 
                        FOREIGN KEY (report_id) REFERENCES reports_reportdefinition(id) ON DELETE CASCADE;
                    """)
                    print("✅ Foreign key report_id agregada a reports_reportdefinitionversion")
                except Exception as e:
                    print(f"⚠️  No se pudo agregar foreign key report_id: {e}")
            else:
                print("✅ Columna report_id ya existe en reports_reportdefinitionversion")
        
        # 9. Verificar y agregar created_by_id a ReportDefinitionVersion si no existe
        if version_table_exists:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = 'reports_reportdefinitionversion'
                    AND column_name = 'created_by_id'
                );
            """)
            created_by_id_exists = cursor.fetchone()[0]
            
            if not created_by_id_exists:
                cursor.execute("""
                    ALTER TABLE reports_reportdefinitionversion 
                    ADD COLUMN created_by_id BIGINT NULL;
                """)
                print("✅ Columna created_by_id agregada a reports_reportdefinitionversion")
                
                # Agregar foreign key si auth_user existe
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM information_schema.tables 
                        WHERE table_schema = 'public' 
                        AND table_name = 'auth_user'
                    );
                """)
                auth_user_exists = cursor.fetchone()[0]
                
                if auth_user_exists:
                    try:
                        cursor.execute("""
                            ALTER TABLE reports_reportdefinitionversion
                            ADD CONSTRAINT reports_reportdefinitionversion_created_by_id_fkey 
                            FOREIGN KEY (created_by_id) REFERENCES auth_user(id) ON DELETE SET NULL;
                        """)
                        print("✅ Foreign key created_by_id agregada a reports_reportdefinitionversion")
                    except Exception as e:
                        print(f"⚠️  No se pudo agregar foreign key created_by_id: {e}")
            else:
                print("✅ Columna created_by_id ya existe en reports_reportdefinitionversion")
        
        # 10. Verificar y agregar índices a ReportDefinitionVersion si no existen
        if version_table_exists:
            # Índice reports_version_idx
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND tablename = 'reports_reportdefinitionversion'
                    AND indexname = 'reports_version_idx'
                );
            """)
            version_idx_exists = cursor.fetchone()[0]
            
            if not version_idx_exists:
                cursor.execute("""
                    CREATE INDEX reports_version_idx ON reports_reportdefinitionversion(report_id, version_number);
                """)
                print("✅ Índice reports_version_idx creado")
            else:
                print("✅ Índice reports_version_idx ya existe")
            
            # Índice reports_version_created_idx
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND tablename = 'reports_reportdefinitionversion'
                    AND indexname = 'reports_version_created_idx'
                );
            """)
            version_created_idx_exists = cursor.fetchone()[0]
            
            if not version_created_idx_exists:
                cursor.execute("""
                    CREATE INDEX reports_version_created_idx ON reports_reportdefinitionversion(report_id, created_at DESC);
                """)
                print("✅ Índice reports_version_created_idx creado")
            else:
                print("✅ Índice reports_version_created_idx ya existe")
            
            # Unique constraint (report_id, version_number)
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.table_constraints 
                    WHERE table_schema = 'public' 
                    AND table_name = 'reports_reportdefinitionversion'
                    AND constraint_name = 'reports_reportdefinitionversion_report_id_version_number_uniq'
                );
            """)
            unique_version_constraint_exists = cursor.fetchone()[0]
            
            if not unique_version_constraint_exists:
                try:
                    cursor.execute("""
                        ALTER TABLE reports_reportdefinitionversion
                        ADD CONSTRAINT reports_reportdefinitionversion_report_id_version_number_uniq 
                        UNIQUE (report_id, version_number);
                    """)
                    print("✅ Unique constraint (report_id, version_number) agregado a reports_reportdefinitionversion")
                except Exception as e:
                    print(f"⚠️  No se pudo agregar unique constraint: {e}")
            else:
                print("✅ Unique constraint (report_id, version_number) ya existe en reports_reportdefinitionversion")
        
        print("✅ Migración 0023 aplicada de forma idempotente")
            
    except Exception as e:
        print(f"⚠️  Error aplicando migración 0023: {e}")
        import traceback
        traceback.print_exc()
    finally:
        cursor.close()


def reverse_migration_0023(apps, schema_editor):
    """No hacer nada en reversa - las tablas pueden ser usadas por otras migraciones."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_increase_permiso_codigo_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0022_add_report_template'),
    ]

    operations = [
        migrations.RunPython(apply_migration_0023_idempotent, reverse_migration_0023),
    ]
