# Generated by Django 4.2 on 2025-12-13 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_increase_permiso_codigo_length'),
        ('reports', '0023_add_learned_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_table', models.CharField(help_text='Tabla origen de la relación', max_length=255, verbose_name='From Table')),
                ('from_column', models.CharField(help_text='Columna origen de la relación', max_length=255, verbose_name='From Column')),
                ('to_table', models.CharField(help_text='Tabla destino de la relación', max_length=255, verbose_name='To Table')),
                ('to_column', models.CharField(help_text='Columna destino de la relación', max_length=255, verbose_name='To Column')),
                ('usage_count', models.IntegerField(default=0, help_text='Número de veces que se ha usado esta relación', verbose_name='Usage Count')),
                ('success_count', models.IntegerField(default=0, help_text='Número de veces que se ha usado exitosamente', verbose_name='Success Count')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Última vez que se usó esta relación', null=True, verbose_name='Last Used At')),
                ('confidence', models.FloatField(default=0.5, help_text='Confianza en la relación (0.0 a 1.0). Mayor = más confiable', verbose_name='Confidence')),
                ('source', models.CharField(default='usage', help_text="Origen de la relación: 'usage' (aprendida por uso)", max_length=32, verbose_name='Source')),
                ('is_blocked', models.BooleanField(default=False, help_text='Si está bloqueada, no se sugerirá ni aprenderá', verbose_name='Is Blocked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa específica. NULL significa relación global (todas las empresas).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learned_relationships', to='core.empresa', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Learned Relationship',
                'verbose_name_plural': 'Learned Relationships',
                'ordering': ['-confidence', '-last_used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='learnedrelationship',
            index=models.Index(fields=['empresa', 'from_table'], name='learned_rel_empresa_from_idx'),
        ),
        migrations.AddIndex(
            model_name='learnedrelationship',
            index=models.Index(fields=['empresa', 'to_table'], name='learned_rel_empresa_to_idx'),
        ),
        migrations.AddIndex(
            model_name='learnedrelationship',
            index=models.Index(fields=['from_table', 'to_table'], name='learned_rel_tables_idx'),
        ),
        migrations.AddIndex(
            model_name='learnedrelationship',
            index=models.Index(fields=['-confidence', '-last_used_at'], name='learned_rel_ranking_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learnedrelationship',
            unique_together={('empresa', 'from_table', 'from_column', 'to_table', 'to_column')},
        ),
    ]
