# Generated by Django 4.2 on 2025-12-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_fix_remitos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnedrelationship',
            name='confidence_calculated',
            field=models.FloatField(blank=True, help_text='Confianza calculada automáticamente por validación', null=True, verbose_name='Confidence Calculated'),
        ),
        migrations.AddField(
            model_name='learnedrelationship',
            name='confidence_override',
            field=models.FloatField(blank=True, help_text='Confianza manualmente sobrescrita por administrador', null=True, verbose_name='Confidence Override'),
        ),
        migrations.AddField(
            model_name='learnedrelationship',
            name='deprecated_reason',
            field=models.TextField(blank=True, help_text='Razón por la cual la relación fue deprecada', null=True, verbose_name='Deprecated Reason'),
        ),
        migrations.AddField(
            model_name='learnedrelationship',
            name='match_rule_json',
            field=models.JSONField(blank=True, default=dict, help_text='Reglas de transformación para matching (TRIM, UPPER, CAST, REPLACE, CONCAT)', verbose_name='Match Rule JSON'),
        ),
        migrations.AddField(
            model_name='learnedrelationship',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('deprecated', 'Deprecated')], default='proposed', help_text='Estado de la relación: proposed (pendiente), approved (aprobada), deprecated (deprecada)', max_length=16, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='learnedrelationship',
            name='validation_metrics_json',
            field=models.JSONField(blank=True, default=dict, help_text='Métricas de validación: match_rate, null_rate, duplicates_dest, cardinality_est', verbose_name='Validation Metrics JSON'),
        ),
        migrations.AddField(
            model_name='learnedrelationship',
            name='version',
            field=models.IntegerField(default=1, help_text='Versión de la relación (se incrementa al editar)', verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='learnedrelationship',
            name='source',
            field=models.CharField(default='usage', help_text="Origen de la relación: 'usage' (aprendida por uso), 'manual' (creada manualmente)", max_length=32, verbose_name='Source'),
        ),
    ]
