# Generated by Django 4.2 on 2025-12-17 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0027_extend_learned_relationship_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Acción realizada: created, approved, deprecated, edited, deleted', max_length=32, verbose_name='Action')),
                ('diff_json', models.JSONField(blank=True, default=dict, help_text='Cambios realizados (antes/después)', verbose_name='Diff JSON')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la acción', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('actor', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='reports.learnedrelationship', verbose_name='Relationship')),
            ],
            options={
                'verbose_name': 'Relationship Audit Log',
                'verbose_name_plural': 'Relationship Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='relationshipauditlog',
            index=models.Index(fields=['relationship', '-created_at'], name='audit_log_rel_created_idx'),
        ),
        migrations.AddIndex(
            model_name='relationshipauditlog',
            index=models.Index(fields=['actor', '-created_at'], name='audit_log_actor_created_idx'),
        ),
    ]
