# Generated by Django 4.2 on 2025-12-17 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_increase_permiso_codigo_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0028_add_relationship_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableClusterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_empresa', models.CharField(help_text='Base de datos MySQL donde se encuentra la tabla', max_length=128, verbose_name='Base Empresa')),
                ('cluster_id', models.CharField(help_text="Identificador único del cluster (ej: 'ventas', 'inventario')", max_length=128, verbose_name='Cluster ID')),
                ('cluster_label', models.CharField(help_text="Etiqueta descriptiva del cluster (ej: 'Ventas', 'Inventario')", max_length=255, verbose_name='Cluster Label')),
                ('table_name', models.CharField(help_text='Nombre de la tabla asignada a este cluster', max_length=255, verbose_name='Table Name')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización dentro del cluster', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cluster_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('empresa', models.ForeignKey(blank=True, help_text='Company that owns this cluster assignment. Null means global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_cluster_assignments', to='core.empresa', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Table Cluster Assignment',
                'verbose_name_plural': 'Table Cluster Assignments',
            },
        ),
        migrations.AddIndex(
            model_name='tableclusterassignment',
            index=models.Index(fields=['base_empresa', 'cluster_id'], name='reports_tab_base_em_14e133_idx'),
        ),
        migrations.AddIndex(
            model_name='tableclusterassignment',
            index=models.Index(fields=['empresa', 'base_empresa'], name='reports_tab_empresa_b3f973_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tableclusterassignment',
            unique_together={('base_empresa', 'table_name')},
        ),
    ]
