from django.urls import path
from . import api_views

app_name = 'self-checkout-api'

urlpatterns = [
    path('health/', api_views.health, name='health'),
    path('afip-health/', api_views.afip_health, name='afip-health'),
    path('afip-caea-mode/', api_views.afip_caea_mode, name='afip-caea-mode'),
    path('supervisor-authorize-caea/', api_views.supervisor_authorize_caea, name='supervisor-authorize-caea'),
    path('audit/', api_views.audit_list, name='audit-list'),
    path('kiosks/', api_views.kiosk_list, name='kiosk-list'),
    path('kiosk/<str:kiosk_id>/acquire/', api_views.kiosk_session_acquire, name='kiosk-session-acquire'),
    path('kiosk/<str:kiosk_id>/heartbeat/', api_views.kiosk_session_heartbeat, name='kiosk-session-heartbeat'),
    path('kiosk/<str:kiosk_id>/release/', api_views.kiosk_session_release, name='kiosk-session-release'),
    path('payment-methods/', api_views.payment_methods_list, name='payment-methods-list'),
    path('price-lists/', api_views.price_lists_list, name='price-lists-list'),
    path('vendedores/', api_views.vendedores_list, name='vendedores-list'),
    path('cart/', api_views.cart_create, name='cart-create'),
    path('cart/<int:cart_id>/', api_views.cart_detail, name='cart-detail'),
    path('cart/<int:cart_id>/items/', api_views.cart_add_item, name='cart-add-item'),
    path('cart/<int:cart_id>/items/<int:item_id>/', api_views.cart_remove_item, name='cart-remove-item'),
    path('cart/<int:cart_id>/items/<int:item_id>/series-disponibles/', api_views.cart_item_series_disponibles, name='cart-item-series-disponibles'),
    path('cart/<int:cart_id>/items/<int:item_id>/series/', api_views.cart_item_series_asignadas, name='cart-item-series-asignadas'),
    path('cart/<int:cart_id>/items/<int:item_id>/series/asignar/', api_views.cart_item_series_asignar, name='cart-item-series-asignar'),
    path('cart/<int:cart_id>/items/<int:item_id>/descuento/', api_views.cart_update_item_descuento, name='cart-update-item-descuento'),
    path('cart/<int:cart_id>/vouchers-disponibles/', api_views.cart_vouchers_disponibles, name='cart-vouchers-disponibles'),
    path('cart/<int:cart_id>/aplicar-voucher/', api_views.cart_aplicar_voucher, name='cart-aplicar-voucher'),
    path('cart/<int:cart_id>/quitar-voucher/', api_views.cart_quitar_voucher, name='cart-quitar-voucher'),
    path('cart/<int:cart_id>/descuento-pie/', api_views.cart_aplicar_descuento_pie, name='cart-aplicar-descuento-pie'),
    path('cart/<int:cart_id>/payment-intent/', api_views.cart_create_payment_intent, name='cart-create-payment-intent'),
    path('cart/<int:cart_id>/email/', api_views.cart_set_email, name='cart-set-email'),
    path('cart/<int:cart_id>/confirm/', api_views.cart_confirm, name='cart-confirm'),
    path('cart/<int:cart_id>/confirm-pending/', api_views.cart_confirm_pending, name='cart-confirm-pending'),
    path('cart/<int:cart_id>/cancel/', api_views.cart_cancel, name='cart-cancel'),
    path('cart/<int:cart_id>/buscar-pago-mp/', api_views.cart_buscar_pago_mp, name='cart-buscar-pago-mp'),
    path('cart/<int:cart_id>/ticket/', api_views.cart_ticket, name='cart-ticket'),
    path('talonarios/consulta-afip/', api_views.talonarios_consulta_afip, name='talonarios-consulta-afip'),
    path('talonarios/sincronizar/', api_views.talonarios_sincronizar, name='talonarios-sincronizar'),
    path('clientes/', api_views.clientes_buscar, name='clientes-buscar'),
    path('consultar-cuit/', api_views.consultar_cuit, name='consultar-cuit'),
    path('cliente/<int:id_cliente>/actualizar-desde-afip/', api_views.cliente_actualizar_desde_afip, name='cliente-actualizar-desde-afip'),
    path('cliente/<int:id_cliente>/cuenta-corriente/', api_views.cliente_cuenta_corriente, name='cliente-cuenta-corriente'),
    path('articulo/por-codigo/', api_views.articulo_por_codigo, name='articulo-por-codigo'),
    path('articulos/', api_views.articulos_list, name='articulos-list'),
]
