"""
Códigos de error API Self-Checkout.
Respuesta consistente: error + code para frontend.
"""

# Códigos de error
E_NO_EMPRESA = 'NO_EMPRESA'
E_KIOSK_REQUIRED = 'KIOSK_ID_REQUIRED'
E_KIOSK_NOT_CONFIGURED = 'KIOSK_NOT_CONFIGURED'
E_CART_NOT_FOUND = 'CART_NOT_FOUND'
E_CART_EMPTY = 'CART_EMPTY'
E_ITEM_NOT_FOUND = 'ITEM_NOT_FOUND'
E_ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND'
E_STOCK_INSUFFICIENT = 'STOCK_INSUFFICIENT'
E_EMAIL_REQUIRED = 'EMAIL_REQUIRED'
E_ARTICLE_REQUIRED = 'ARTICLE_REQUIRED'
E_CART_STATE_INVALID = 'CART_STATE_INVALID'
E_CONFIRM_FAILED = 'CONFIRM_FAILED'
E_AFIP_UNAVAILABLE = 'AFIP_UNAVAILABLE'  # No se pudo obtener CAE/CAEA; operación interrumpida sin afectar stock
E_SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'  # Autoservicio fuera de servicio (talonario, AFIP, stock, etc.)
E_KIOSK_IN_USE = 'KIOSK_IN_USE'  # Kiosco ya abierto en otra máquina
