# Generated by Django 4.2 on 2025-07-15 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='Sandbox Mode')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
                ('webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook Secret')),
                ('supported_payment_methods', models.JSONField(default=list, verbose_name='Supported Payment Methods')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Commission %')),
                ('auto_capture', models.BooleanField(default=True, verbose_name='Auto Capture')),
                ('installments_enabled', models.BooleanField(default=True, verbose_name='Installments Enabled')),
                ('max_installments', models.IntegerField(default=12, verbose_name='Max Installments')),
                ('smartpos_enabled', models.BooleanField(default=True, verbose_name='SmartPOS Enabled')),
                ('smartpos_api_key', models.CharField(blank=True, max_length=255, verbose_name='SmartPOS API Key')),
                ('smartpos_webhook_url', models.URLField(blank=True, verbose_name='SmartPOS Webhook URL')),
                ('allow_multiple_devices', models.BooleanField(default=True, verbose_name='Allow Multiple Devices')),
                ('max_devices_per_branch', models.IntegerField(default=5, verbose_name='Max Devices per Branch')),
                ('device_sync_interval', models.IntegerField(default=300, verbose_name='Device Sync Interval (seconds)')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Additional Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mercadopago_configs', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mercadopago_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MercadoPago Configuration',
                'verbose_name_plural': 'MercadoPago Configurations',
                'ordering': ['empresa'],
            },
        ),
        migrations.CreateModel(
            name='MercadoPagoDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('device_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Device ID')),
                ('device_type', models.CharField(choices=[('smartpos', 'SmartPOS Terminal'), ('mobile_pos', 'Mobile POS'), ('web_checkout', 'Web Checkout'), ('api_integration', 'API Integration')], max_length=20, verbose_name='Device Type')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('offline', 'Offline'), ('error', 'Error')], default='inactive', max_length=20, verbose_name='Status')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Device')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('device_config', models.JSONField(blank=True, default=dict, verbose_name='Device Configuration')),
                ('supported_payment_methods', models.JSONField(blank=True, default=list, verbose_name='Supported Payment Methods')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('last_transaction', models.DateTimeField(blank=True, null=True, verbose_name='Last Transaction')),
                ('connection_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Connection Status')),
                ('firmware_version', models.CharField(blank=True, max_length=50, verbose_name='Firmware Version')),
                ('hardware_model', models.CharField(blank=True, max_length=100, verbose_name='Hardware Model')),
                ('location_description', models.TextField(blank=True, verbose_name='Location Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='Branch')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadopago.mercadopagoconfig', verbose_name='Configuration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mercadopago_devices', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'MercadoPago Device',
                'verbose_name_plural': 'MercadoPago Devices',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MercadoPagoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(max_length=255, unique=True, verbose_name='External Reference')),
                ('mercadopago_id', models.CharField(max_length=255, unique=True, verbose_name='MercadoPago ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(default='ARS', max_length=3, verbose_name='Currency')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('payment_type', models.CharField(max_length=50, verbose_name='Payment Type')),
                ('installments', models.IntegerField(default=1, verbose_name='Installments')),
                ('device_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Device Transaction ID')),
                ('device_response', models.JSONField(blank=True, default=dict, verbose_name='Device Response')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('authorized', 'Authorized'), ('in_process', 'In Process'), ('in_mediation', 'In Mediation'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('charged_back', 'Chargeback')], max_length=20, verbose_name='Status')),
                ('status_detail', models.CharField(blank=True, max_length=100, verbose_name='Status Detail')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='Branch')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercadopago.mercadopagodevice', verbose_name='Device')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.invoice', verbose_name='Invoice')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.possale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'MercadoPago Transaction',
                'verbose_name_plural': 'MercadoPago Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mercadopagotransaction',
            index=models.Index(fields=['empresa', 'branch'], name='mercadopago_empresa_a93855_idx'),
        ),
        migrations.AddIndex(
            model_name='mercadopagotransaction',
            index=models.Index(fields=['device'], name='mercadopago_device__9f37db_idx'),
        ),
        migrations.AddIndex(
            model_name='mercadopagotransaction',
            index=models.Index(fields=['status'], name='mercadopago_status_86a2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='mercadopagotransaction',
            index=models.Index(fields=['mercadopago_id'], name='mercadopago_mercado_788748_idx'),
        ),
        migrations.AddIndex(
            model_name='mercadopagotransaction',
            index=models.Index(fields=['external_reference'], name='mercadopago_externa_f9284e_idx'),
        ),
        migrations.AddIndex(
            model_name='mercadopagotransaction',
            index=models.Index(fields=['created_at'], name='mercadopago_created_e4d39f_idx'),
        ),
        migrations.AddIndex(
            model_name='mercadopagodevice',
            index=models.Index(fields=['empresa', 'branch'], name='mercadopago_empresa_a22fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='mercadopagodevice',
            index=models.Index(fields=['device_type', 'status'], name='mercadopago_device__bb0b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='mercadopagodevice',
            index=models.Index(fields=['device_id'], name='mercadopago_device__b57af2_idx'),
        ),
        migrations.AddIndex(
            model_name='mercadopagodevice',
            index=models.Index(fields=['is_active', 'status'], name='mercadopago_is_acti_5a2aa4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mercadopagodevice',
            unique_together={('empresa', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='mercadopagoconfig',
            index=models.Index(fields=['empresa', 'is_active'], name='mercadopago_empresa_64b490_idx'),
        ),
        migrations.AddIndex(
            model_name='mercadopagoconfig',
            index=models.Index(fields=['is_sandbox'], name='mercadopago_is_sand_ca3bf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mercadopagoconfig',
            unique_together={('empresa',)},
        ),
    ]
