# Generated by Django 4.2 on 2026-04-14 23:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_moduleconfig_logistica'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner_legacy_user_id', models.IntegerField(blank=True, null=True, verbose_name='ID usuario legacy')),
                ('owner_legacy_user_code', models.CharField(blank=True, max_length=80, verbose_name='Código usuario legacy')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('archived', 'Archivada'), ('closed', 'Cerrada')], default='active', max_length=20, verbose_name='Estado')),
                ('channel', models.CharField(choices=[('web', 'Web'), ('pwa', 'PWA'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('api', 'API')], default='web', max_length=20, verbose_name='Canal')),
                ('pwa_context', models.JSONField(blank=True, default=dict, verbose_name='Contexto PWA')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Último mensaje')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Conversación de agente',
                'verbose_name_plural': 'Conversaciones de agentes',
                'ordering': ('-last_message_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, verbose_name='Slug')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('domain', models.CharField(default='general', max_length=80, verbose_name='Dominio')),
                ('system_prompt', models.TextField(blank=True, verbose_name='Prompt del sistema')),
                ('soul_summary', models.TextField(blank=True, verbose_name='Resumen del alma')),
                ('required_permission', models.CharField(blank=True, default='', help_text='Si está vacío, basta con autenticación.', max_length=100, verbose_name='Permiso requerido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_system', models.BooleanField(default=True, verbose_name='Agente del sistema')),
                ('default_model_name', models.CharField(blank=True, max_length=120, verbose_name='Modelo principal')),
                ('tool_use_model_name', models.CharField(blank=True, max_length=120, verbose_name='Modelo tool use')),
                ('memory_write_model_name', models.CharField(blank=True, max_length=120, verbose_name='Modelo memoria')),
                ('fast_model_name', models.CharField(blank=True, max_length=120, verbose_name='Modelo rápido')),
                ('fallback_model_name', models.CharField(blank=True, max_length=120, verbose_name='Modelo fallback')),
                ('reasoning_profile', models.CharField(blank=True, default='balanced', max_length=40)),
                ('max_input_tokens', models.PositiveIntegerField(default=16000)),
                ('max_output_tokens', models.PositiveIntegerField(default=4000)),
                ('supports_structured_output', models.BooleanField(default=True)),
                ('supports_parallel_tool_calls', models.BooleanField(default=False)),
                ('supports_streaming', models.BooleanField(default=True)),
                ('supports_vision', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuración')),
                ('memory_policy', models.JSONField(blank=True, default=dict, verbose_name='Política de memoria')),
                ('ui_config', models.JSONField(blank=True, default=dict, verbose_name='Configuración UI')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Definición de agente',
                'verbose_name_plural': 'Definiciones de agentes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='Modelo')),
                ('task_type', models.CharField(default='conversation', max_length=40, verbose_name='Tipo de tarea')),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('error', 'Error'), ('rejected', 'Rechazada'), ('partial', 'Parcial')], default='success', max_length=20, verbose_name='Estado')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload request')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload response')),
                ('memory_items_read', models.PositiveIntegerField(default=0)),
                ('memory_items_written', models.PositiveIntegerField(default=0)),
                ('tool_calls_count', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ia.agentdefinition', verbose_name='Agente')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ia.agentconversation', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Ejecución de agente',
                'verbose_name_plural': 'Ejecuciones de agentes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LlmProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('provider_kind', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic / Claude'), ('openai_compatible', 'OpenAI-compatible'), ('local', 'Local / SML')], max_length=32, verbose_name='Tipo de proveedor')),
                ('base_url', models.URLField(blank=True, verbose_name='Base URL')),
                ('api_key_env_var', models.CharField(blank=True, help_text='Nombre de la variable de entorno. La clave real no se persiste en base.', max_length=100, verbose_name='Variable de entorno para API key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('supports_structured_output', models.BooleanField(default=True)),
                ('supports_tool_use', models.BooleanField(default=True)),
                ('supports_streaming', models.BooleanField(default=True)),
                ('supports_vision', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de proveedor LLM',
                'verbose_name_plural': 'Configuraciones de proveedores LLM',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AgentToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=120, verbose_name='Herramienta')),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('error', 'Error'), ('rejected', 'Rechazada')], default='success', max_length=20, verbose_name='Estado')),
                ('input_payload', models.JSONField(blank=True, default=dict, verbose_name='Input')),
                ('output_payload', models.JSONField(blank=True, default=dict, verbose_name='Output')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='ia.agentexecution', verbose_name='Ejecución')),
            ],
            options={
                'verbose_name': 'Ejecución de herramienta',
                'verbose_name_plural': 'Ejecuciones de herramientas',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema'), ('tool', 'Herramienta')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('structured_content', models.JSONField(blank=True, default=dict, verbose_name='Contenido estructurado')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ia.agentconversation', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Mensaje de agente',
                'verbose_name_plural': 'Mensajes de agentes',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AgentMemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_legacy_user_id', models.IntegerField(blank=True, null=True, verbose_name='ID usuario legacy')),
                ('owner_legacy_user_code', models.CharField(blank=True, max_length=80, verbose_name='Código usuario legacy')),
                ('scope', models.CharField(choices=[('tenant', 'Tenant'), ('agent', 'Agente'), ('user', 'Usuario'), ('conversation', 'Conversación')], default='user', max_length=20)),
                ('memory_type', models.CharField(choices=[('profile', 'Perfil'), ('episodic', 'Episódica'), ('semantic', 'Semántica'), ('working', 'Trabajo')], default='episodic', max_length=20)),
                ('sensitivity', models.CharField(choices=[('low', 'Baja'), ('internal', 'Interna'), ('restricted', 'Restringida')], default='internal', max_length=20)),
                ('key', models.CharField(blank=True, max_length=120, verbose_name='Clave')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('source_summary', models.TextField(blank=True, verbose_name='Resumen de origen')),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_items', to='ia.agentdefinition', verbose_name='Agente')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_items', to='ia.agentconversation', verbose_name='Conversación origen')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ia_memory_items', to='core.empresa', verbose_name='Empresa')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ia_memory_items', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Synap')),
            ],
            options={
                'verbose_name': 'Ítem de memoria',
                'verbose_name_plural': 'Ítems de memoria',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AgentMemoryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_legacy_user_id', models.IntegerField(blank=True, null=True, verbose_name='ID usuario legacy')),
                ('actor_legacy_user_code', models.CharField(blank=True, max_length=80, verbose_name='Código usuario legacy')),
                ('feedback_value', models.CharField(choices=[('accept', 'Aceptar'), ('reject', 'Rechazar'), ('correct', 'Corregir')], max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ia_memory_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Synap')),
                ('memory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='ia.agentmemoryitem', verbose_name='Memoria')),
            ],
            options={
                'verbose_name': 'Feedback de memoria',
                'verbose_name_plural': 'Feedback de memoria',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='provider_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='ia.llmproviderconfig', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='request_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_executions', to='ia.agentmessage', verbose_name='Mensaje de solicitud'),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='response_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_executions', to='ia.agentmessage', verbose_name='Mensaje de respuesta'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='default_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_default', to='ia.llmproviderconfig', verbose_name='Proveedor por defecto'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Null indica agente global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ia_agents', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='fallback_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_fallback', to='ia.llmproviderconfig', verbose_name='Proveedor fallback'),
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ia.agentdefinition', verbose_name='Agente'),
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ia_conversations', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ia_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Synap'),
        ),
        migrations.AddIndex(
            model_name='agenttoolexecution',
            index=models.Index(fields=['execution', 'tool_name'], name='ia_tool_exec_tool_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ia_msg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmemoryitem',
            index=models.Index(fields=['agent', 'scope'], name='ia_mem_agent_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmemoryitem',
            index=models.Index(fields=['empresa', 'memory_type'], name='ia_mem_empresa_type_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmemoryitem',
            index=models.Index(fields=['owner_legacy_user_id'], name='ia_mem_legacy_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmemoryitem',
            index=models.Index(fields=['is_active', 'expires_at'], name='ia_mem_active_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['agent', '-created_at'], name='ia_exec_agent_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['status'], name='ia_exec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdefinition',
            index=models.Index(fields=['empresa', 'slug'], name='ia_agent_empresa_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdefinition',
            index=models.Index(fields=['is_active'], name='ia_agent_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentdefinition',
            unique_together={('empresa', 'slug')},
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['agent', 'status'], name='ia_conv_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['empresa', '-last_message_at'], name='ia_conv_empresa_last_idx'),
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['owner_legacy_user_id'], name='ia_conv_legacy_user_id_idx'),
        ),
    ]
