# Generated by Django 4.2 on 2026-04-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_bootstrap_default_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmproviderconfig',
            name='api_key_last4',
            field=models.CharField(blank=True, max_length=8, verbose_name='Últimos 4'),
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='available_models',
            field=models.JSONField(blank=True, default=list, verbose_name='Modelos disponibles'),
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='encrypted_api_key',
            field=models.TextField(blank=True, verbose_name='API key cifrada'),
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuración extra'),
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='organization_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='Organization / Workspace'),
        ),
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='api_key_env_var',
            field=models.CharField(blank=True, help_text='Campo legacy. La configuración principal debe cargarse por UI.', max_length=100, verbose_name='Variable de entorno para API key'),
        ),
    ]
