# Generated by Django 4.2 on 2026-04-10 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura_compra_captura', '0004_alter_expediente_codigo_proveedor_label'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentofuente',
            new_name='factura_com_expedie_ea9850_idx',
            old_name='factura_com_expedie_9a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='expedientefacturacompra',
            new_name='factura_com_estado_eb0b3e_idx',
            old_name='factura_com_estado_3e6fbd_idx',
        ),
        migrations.AlterField(
            model_name='lineaexpedientecompra',
            name='orden',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
