from django.urls import path
from . import views
from mpr.best_migration import views as best_migration_views

app_name = "mpr"

urlpatterns = [
    path("", views.TableroView.as_view(), name="tablero"),
    path("ordenes/", views.OpListView.as_view(), name="op_list"),
    path("wizard/", views.WizardProduccionView.as_view(), name="wizard"),
    path("bom/", views.BomListView.as_view(), name="bom_list"),
    path("bom/nuevo/", views.BomCreateView.as_view(), name="bom_create"),
    path("bom/<int:id_en_abm>/", views.BomDetailView.as_view(), name="bom_detail"),
    path("bom/<int:id_en_abm>/editar/", views.BomEditView.as_view(), name="bom_edit"),
    path("armado/", views.ArmadoView.as_view(), name="armado"),
    path("armado/legacy/<int:id_en_abm>/", views.ArmadoLegacyView.as_view(), name="armado_bom"),
    path("reclasificacion/", views.ReclasificacionView.as_view(), name="reclasificacion"),
    path("armado-surtido/", views.ArmadoSurtidoRedirectView.as_view(), name="armado_surtido"),
    path(
        "imputacion-armado-1ra/",
        views.ImputacionArmado1raView.as_view(),
        name="imputacion_armado_1ra",
    ),
    path(
        "api/imputacion-armado-1ra/sugerir/",
        views.ImputacionArmadoSugerirAPIView.as_view(),
        name="api_imputacion_armado_sugerir",
    ),
    path(
        "api/imputacion-armado-1ra/confirmar/",
        views.ImputacionArmadoConfirmarAPIView.as_view(),
        name="api_imputacion_armado_confirmar",
    ),
    path(
        "api/armado/packs-catalog/",
        views.ArmadoPacksCatalogAPIView.as_view(),
        name="api_armado_packs_catalog",
    ),
    path(
        "api/armado/bom-pack/",
        views.ArmadoBomPackAPIView.as_view(),
        name="api_armado_bom_pack",
    ),
    path(
        "api/armado-surtido/stock-origen/",
        views.ArmadoSurtidoStockOrigenAPIView.as_view(),
        name="api_armado_surtido_stock",
    ),
    path(
        "api/armado-surtido/validar-item-lote/",
        views.ArmadoSurtidoValidarItemLoteAPIView.as_view(),
        name="api_armado_surtido_validar_item_lote",
    ),
    path("reportes/", views.ReportesMPRView.as_view(), name="reportes"),
    path("config/depositos/", views.ConfigDepositosView.as_view(), name="config_depositos"),
    path("operarios/", views.OperariosListView.as_view(), name="operarios_list"),
    path("operarios/nuevo/", views.OperarioCreateView.as_view(), name="operario_create"),
    path("operarios/<int:id_operario>/editar/", views.OperarioUpdateView.as_view(), name="operario_edit"),
    path("operarios/<int:id_operario>/anular/", views.OperarioAnularView.as_view(), name="operario_anular"),
    path("operarios/<int:id_operario>/reactivar/", views.OperarioReactivarView.as_view(), name="operario_reactivar"),
    path("demanda/ventana-pack/", views.VentanaPackView.as_view(), name="ventana_pack"),
    path("demanda/ventana-pack/actualizar/", views.VentanaPackActualizarView.as_view(), name="ventana_pack_actualizar"),
    path("demanda/ventana-pack/agrupar/", views.VentanaPackAgruparView.as_view(), name="ventana_pack_agrupar"),
    path("api/empleados/", views.EmpleadosOperariosAPIView.as_view(), name="api_empleados"),
    path("demanda/pedidos-fabrica/", views.PedidosFabricaListView.as_view(), name="pedidos_fabrica_list"),
    path("demanda/opts-por-pedido/", views.OptsPorPedidoView.as_view(), name="opts_por_pedido"),
    path("opt/", views.OptListView.as_view(), name="opt_list"),
    path("opt/nueva/", views.NuevaOptView.as_view(), name="opt_create"),
    path("opt/<int:id_lista>/", views.OptDetailView.as_view(), name="opt_detail"),
    path("opt/<int:id_lista>/trazabilidad/", views.TrazabilidadOptView.as_view(), name="opt_trazabilidad"),
    path("opt/<int:id_lista>/armado/", views.ArmadoOptView.as_view(), name="armado_opt"),
    # DEPRECATED (E6/E11): usar /mpr/parte-produccion/ para registrar parte de producción.
    path("opt/<int:id_lista>/registrar-opp/", views.RegistrarOppView.as_view(), name="registrar_opp"),
    path("opt/<int:id_lista>/cerrar/", views.CerrarOptView.as_view(), name="opt_cerrar"),
    path("opt/<int:id_lista>/comprobante.pdf/", views.opt_comprobante_pdf_view, name="opt_comprobante_pdf"),
    # Etapa 2: Tablero de Demanda Consolidado por Artículo
    path("tablero-produccion/", views.TableroProduccionView.as_view(), name="tablero_produccion"),
    path("tablero-produccion/actualizar/", views.TableroProduccionActualizarView.as_view(), name="tablero_produccion_actualizar"),
    # Etapa 3: Turnos (CRUD) + Roster Rotativo
    path("turnos/", views.TurnosListView.as_view(), name="turnos_list"),
    path("turnos/nuevo/", views.TurnoCreateView.as_view(), name="turno_create"),
    path("turnos/<int:id_turno>/editar/", views.TurnoUpdateView.as_view(), name="turno_edit"),
    # Trazabilidad: catálogos de líneas y máquinas (+ asignación versionada)
    path("lineas/", views.LineasListView.as_view(), name="lineas_list"),
    path("lineas/nueva/", views.LineaCreateView.as_view(), name="linea_create"),
    path("lineas/<int:id_linea>/editar/", views.LineaUpdateView.as_view(), name="linea_edit"),
    path("maquinas/", views.MaquinasListView.as_view(), name="maquinas_list"),
    path("maquinas/nueva/", views.MaquinaCreateView.as_view(), name="maquina_create"),
    path("maquinas/<int:id_maquina>/editar/", views.MaquinaUpdateView.as_view(), name="maquina_edit"),
    path("maquinas/<int:id_maquina>/articulos/", views.MaquinaArticulosView.as_view(), name="maquina_articulos"),
    path("maquinas/asignar-linea/", views.MaquinaAsignarLineaView.as_view(), name="maquina_asignar_linea"),
    path("operarios-usuarios/", views.OperarioUsuarioMapView.as_view(), name="operario_usuario_map"),
    path("operarios-lineas/", views.OperarioLineaView.as_view(), name="operario_linea"),
    # Carga móvil del operario
    path("mi-parte/", views.ParteMovilOperarioView.as_view(), name="parte_movil_operario"),
    # Bandeja de aprobación de partes (supervisor)
    path("partes-pendientes/", views.PartesPendientesView.as_view(), name="partes_pendientes"),
    path("partes-pendientes/<int:id_parte>/", views.PartePendienteDetailView.as_view(), name="parte_pendiente_detail"),
    path("planificacion-turnos/", views.PlanificacionTurnosView.as_view(), name="planificacion_turnos"),
    path("planificacion-turnos/asignar/", views.AsignarTurnoRosterView.as_view(), name="roster_asignar"),
    path("planificacion-turnos/eliminar/", views.EliminarAsignacionRosterView.as_view(), name="roster_eliminar"),
    # Etapa 4: Parte de producción (ledger OPP-parte)
    path("parte-produccion/", views.ParteProduccionView.as_view(), name="parte_produccion"),
    path("parte-produccion/registrar/", views.RegistrarParteProduccionView.as_view(), name="parte_produccion_registrar"),
    path("parte-produccion/<str:parte_id>/ajuste/", views.AjusteParteView.as_view(), name="parte_ajuste"),
    # Etapa 5: Transición de stock entre etapas MPR
    # DEPRECADO UI (E9): la UI de transición por fila fue reemplazada por las pantallas
    # globales de Inspección y Clasificación. La URL se mantiene backward-safe.
    path("tablero-produccion/transicion/", views.TransicionLoteView.as_view(), name="transicion_lote"),
    # Etapa 7: Envío directo a producción desde el Tablero (ledger-componente, lote)
    path("tablero-produccion/enviar/", views.EnviarProduccionLoteView.as_view(), name="tablero_produccion_enviar"),
    path("tablero-produccion/envios/", views.EnviosProduccionListView.as_view(), name="envios_produccion"),
    path("tablero-produccion/envios/anular/", views.AnularEnviosProduccionView.as_view(), name="envios_produccion_anular"),
    # Etapa 10: Clasificación de Producción (pantalla única; reemplaza Inspección/Clasificación E9)
    path("tablero-produccion/clasificacion-produccion/", views.ClasificacionProduccionView.as_view(), name="clasificacion_produccion"),
    path("tablero-produccion/clasificacion-produccion/registrar/", views.RegistrarClasificacionProduccionView.as_view(), name="clasificacion_produccion_registrar"),
    # Migración BEST → MPR (paridad de maestros + gate de pedidos)
    path("migracion-best/", best_migration_views.MigracionBestHubView.as_view(), name="migracion_best_hub"),
    path("migracion-best/articulos/", best_migration_views.MigracionBestArticulosView.as_view(), name="migracion_best_articulos"),
    path("migracion-best/articulos/recalcular/", best_migration_views.MigracionBestRecalcularArticulosView.as_view(), name="migracion_best_recalcular_articulos"),
    path("migracion-best/articulos/aceptar-inferidos/", best_migration_views.MigracionBestAceptarInferidosArticulosView.as_view(), name="migracion_best_aceptar_inferidos_articulos"),
    path("migracion-best/articulos/validar/", best_migration_views.MigracionBestValidarArticuloView.as_view(), name="migracion_best_validar_articulo"),
    path("migracion-best/articulos-fabricados/", best_migration_views.MigracionBestArticulosFabricadosView.as_view(), name="migracion_best_articulos_fabricados"),
    path("migracion-best/articulos-fabricados/resolver/", best_migration_views.MigracionBestResolverFabricadosView.as_view(), name="migracion_best_resolver_fabricados"),
    path("migracion-best/articulos-fabricados/aceptar-inferidos/", best_migration_views.MigracionBestAceptarInferidosFabricadosView.as_view(), name="migracion_best_aceptar_inferidos_fabricados"),
    path("migracion-best/articulos-fabricados/validar/", best_migration_views.MigracionBestValidarArticuloFabricadoView.as_view(), name="migracion_best_validar_articulo_fabricado"),
    path("migracion-best/stock-inicial/sincronizar-fabricados-semi/", best_migration_views.MigracionBestSincronizarStockFabricadosSemiView.as_view(), name="migracion_best_sincronizar_stock_fabricados_semi"),
    path("migracion-best/clientes/", best_migration_views.MigracionBestClientesView.as_view(), name="migracion_best_clientes"),
    path("migracion-best/clientes/sincronizar/", best_migration_views.MigracionBestSincronizarClientesView.as_view(), name="migracion_best_sincronizar_clientes"),
    path("migracion-best/clientes/validar/", best_migration_views.MigracionBestValidarClienteView.as_view(), name="migracion_best_validar_cliente"),
    path("migracion-best/depositos/", best_migration_views.MigracionBestDepositosView.as_view(), name="migracion_best_depositos"),
    path("migracion-best/depositos/sincronizar/", best_migration_views.MigracionBestSincronizarDepositosView.as_view(), name="migracion_best_sincronizar_depositos"),
    path("migracion-best/depositos/validar/", best_migration_views.MigracionBestValidarDepositoView.as_view(), name="migracion_best_validar_deposito"),
    path("migracion-best/operarios/", best_migration_views.MigracionBestOperariosView.as_view(), name="migracion_best_operarios"),
    path("migracion-best/operarios/sincronizar/", best_migration_views.MigracionBestSincronizarOperariosView.as_view(), name="migracion_best_sincronizar_operarios"),
    path("migracion-best/operarios/validar/", best_migration_views.MigracionBestValidarOperarioView.as_view(), name="migracion_best_validar_operario"),
    path("migracion-best/stock-inicial/", best_migration_views.MigracionBestStockInicialView.as_view(), name="migracion_best_stock_inicial"),
    path("migracion-best/stock-inicial/sincronizar/", best_migration_views.MigracionBestSincronizarStockInicialView.as_view(), name="migracion_best_sincronizar_stock_inicial"),
    path("migracion-best/stock-inicial/validar/", best_migration_views.MigracionBestValidarStockInicialView.as_view(), name="migracion_best_validar_stock_inicial"),
    path("migracion-best/stock-inicial/cargar/", best_migration_views.MigracionBestCargarStockInicialView.as_view(), name="migracion_best_cargar_stock_inicial"),
    path("migracion-best/unidades/", best_migration_views.MigracionBestConfirmarUnidadesView.as_view(), name="migracion_best_confirmar_unidades"),
    path("migracion-best/reiniciar/", best_migration_views.MigracionBestReiniciarView.as_view(), name="migracion_best_reiniciar"),
    path("migracion-best/pedidos/", best_migration_views.MigracionBestPedidosGateView.as_view(), name="migracion_best_pedidos"),
    path("migracion-best/pedidos/migrar/", best_migration_views.MigracionBestMigrarPedidosView.as_view(), name="migracion_best_migrar_pedidos"),
    path("migracion-best/stock-reserva/cargar/", best_migration_views.MigracionBestCargarStockReservaView.as_view(), name="migracion_best_cargar_stock_reserva"),
]
