# Generated by Django 4.2 on 2026-02-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "escalation_emails_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Emails escalamiento"
                    ),
                ),
                (
                    "sla_warning_message_template",
                    models.TextField(blank=True, verbose_name="Plantilla aviso SLA"),
                ),
                (
                    "sla_breach_message_template",
                    models.TextField(blank=True, verbose_name="Plantilla SLA vencido"),
                ),
                (
                    "internal_alert_channel",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Canal alertas internas",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración notificaciones",
                "db_table": "support_system_config_notifications",
            },
        ),
        migrations.CreateModel(
            name="SecurityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_limits_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Límites por canal/IP"
                    ),
                ),
                (
                    "anti_spam_enabled",
                    models.BooleanField(default=True, verbose_name="Anti-spam activo"),
                ),
                (
                    "pii_warning_enabled",
                    models.BooleanField(default=True, verbose_name="Aviso PII activo"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración seguridad",
                "db_table": "support_system_config_security",
            },
        ),
        migrations.CreateModel(
            name="StorageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Endpoint"
                    ),
                ),
                (
                    "bucket",
                    models.CharField(blank=True, max_length=256, verbose_name="Bucket"),
                ),
                (
                    "region",
                    models.CharField(
                        default="us-east-1", max_length=64, verbose_name="Región"
                    ),
                ),
                (
                    "force_path_style",
                    models.BooleanField(default=False, verbose_name="Force path style"),
                ),
                (
                    "access_key_masked",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Access key (enmascarado en UI)",
                    ),
                ),
                (
                    "secret_encrypted",
                    models.TextField(blank=True, verbose_name="Secret cifrado"),
                ),
                (
                    "max_size_bytes",
                    models.PositiveIntegerField(
                        default=10485760, verbose_name="Tamaño máximo (bytes)"
                    ),
                ),
                (
                    "allowed_content_types_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Content types permitidos",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Retención (días)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("validating", "Validando"),
                            ("active", "Activo"),
                            ("error", "Error"),
                            ("disabled", "Desactivado"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración storage",
                "db_table": "support_system_config_storage",
            },
        ),
        migrations.CreateModel(
            name="RAGConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "top_k",
                    models.PositiveSmallIntegerField(default=10, verbose_name="Top K"),
                ),
                (
                    "sources_enabled_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Fuentes habilitadas"
                    ),
                ),
                (
                    "cache_ttl_seconds",
                    models.PositiveIntegerField(
                        default=300, verbose_name="TTL caché (s)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("validating", "Validando"),
                            ("active", "Activo"),
                            ("error", "Error"),
                            ("disabled", "Desactivado"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_ingest_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_configs",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración RAG",
                "db_table": "support_system_config_rag",
            },
        ),
        migrations.CreateModel(
            name="IAConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Proveedor"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=128, verbose_name="Modelo"),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(blank=True, verbose_name="API key cifrada"),
                ),
                (
                    "limits_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Límites (rate, tokens)"
                    ),
                ),
                (
                    "prompt_version_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Versión de prompt",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("validating", "Validando"),
                            ("active", "Activo"),
                            ("error", "Error"),
                            ("disabled", "Desactivado"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ia_configs",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración IA",
                "db_table": "support_system_config_ia",
            },
        ),
        migrations.CreateModel(
            name="ChannelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de canal",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Nombre para mostrar"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("validating", "Validando"),
                            ("active", "Activo"),
                            ("error", "Error"),
                            ("disabled", "Desactivado"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "config_encrypted_json",
                    models.TextField(
                        blank=True, verbose_name="Config cifrada (tokens, keys, etc.)"
                    ),
                ),
                (
                    "last_check_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última comprobación"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Último error (humano)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_configs",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de canal",
                "verbose_name_plural": "Configuraciones de canal",
                "db_table": "support_system_config_channel",
                "ordering": ["company_id", "channel_type"],
            },
        ),
        migrations.CreateModel(
            name="BrandingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assistant_name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Nombre del asistente"
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(blank=True, verbose_name="Mensaje de bienvenida"),
                ),
                (
                    "default_language",
                    models.CharField(
                        default="es", max_length=10, verbose_name="Idioma por defecto"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding_configs",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración branding",
                "db_table": "support_system_config_branding",
            },
        ),
        migrations.AddConstraint(
            model_name="ragconfig",
            constraint=models.UniqueConstraint(
                fields=("company",), name="support_sysconfig_rag_company_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="iaconfig",
            constraint=models.UniqueConstraint(
                fields=("company",), name="support_sysconfig_ia_company_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="channelconfig",
            constraint=models.UniqueConstraint(
                fields=("company", "channel_type"),
                name="support_sysconfig_channel_company_type_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="brandingconfig",
            constraint=models.UniqueConstraint(
                fields=("company",), name="support_sysconfig_branding_company_uniq"
            ),
        ),
    ]
