"""
Configuración específica para MercadoPago
"""

import os
from django.conf import settings

# Configuración de MercadoPago
MERCADOPAGO_CLIENT_ID = os.getenv('MERCADOPAGO_CLIENT_ID', '')
MERCADOPAGO_CLIENT_SECRET = os.getenv('MERCADOPAGO_CLIENT_SECRET', '')
MERCADOPAGO_WEBHOOK_SECRET = os.getenv('MERCADOPAGO_WEBHOOK_SECRET', '')

# Configuración de SmartPOS
MERCADOPAGO_SMARTPOS_ENABLED = os.getenv('MERCADOPAGO_SMARTPOS_ENABLED', 'true').lower() == 'true'
MERCADOPAGO_SMARTPOS_API_KEY = os.getenv('MERCADOPAGO_SMARTPOS_API_KEY', '')
MERCADOPAGO_SMARTPOS_WEBHOOK_URL = os.getenv('MERCADOPAGO_SMARTPOS_WEBHOOK_URL', '')

# Configuración de dispositivos
MERCADOPAGO_MAX_DEVICES_PER_BRANCH = int(os.getenv('MERCADOPAGO_MAX_DEVICES_PER_BRANCH', '5'))
MERCADOPAGO_DEVICE_SYNC_INTERVAL = int(os.getenv('MERCADOPAGO_DEVICE_SYNC_INTERVAL', '300'))

# Configuración de sandbox
MERCADOPAGO_SANDBOX_MODE = os.getenv('MERCADOPAGO_SANDBOX_MODE', 'true').lower() == 'true'

# URLs de API
MERCADOPAGO_API_BASE_URL = 'https://api.mercadopago.com/sandbox' if MERCADOPAGO_SANDBOX_MODE else 'https://api.mercadopago.com'
MERCADOPAGO_SMARTPOS_API_URL = f"{MERCADOPAGO_API_BASE_URL}/point"

# Configuración de webhooks
MERCADOPAGO_WEBHOOK_TIMEOUT = int(os.getenv('MERCADOPAGO_WEBHOOK_TIMEOUT', '30'))
MERCADOPAGO_WEBHOOK_RETRY_ATTEMPTS = int(os.getenv('MERCADOPAGO_WEBHOOK_RETRY_ATTEMPTS', '3'))

# Configuración de logging
MERCADOPAGO_LOG_LEVEL = os.getenv('MERCADOPAGO_LOG_LEVEL', 'INFO')

# Configuración de pagos
MERCADOPAGO_DEFAULT_CURRENCY = os.getenv('MERCADOPAGO_DEFAULT_CURRENCY', 'ARS')
MERCADOPAGO_DEFAULT_INSTALLMENTS = int(os.getenv('MERCADOPAGO_DEFAULT_INSTALLMENTS', '1'))
MERCADOPAGO_MAX_INSTALLMENTS = int(os.getenv('MERCADOPAGO_MAX_INSTALLMENTS', '12'))

# Configuración de comisiones
MERCADOPAGO_DEFAULT_COMMISSION_PERCENTAGE = float(os.getenv('MERCADOPAGO_DEFAULT_COMMISSION_PERCENTAGE', '0.0'))

# Configuración de timeouts
MERCADOPAGO_API_TIMEOUT = int(os.getenv('MERCADOPAGO_API_TIMEOUT', '30'))
MERCADOPAGO_DEVICE_TIMEOUT = int(os.getenv('MERCADOPAGO_DEVICE_TIMEOUT', '60'))

# Configuración de reintentos
MERCADOPAGO_API_RETRY_ATTEMPTS = int(os.getenv('MERCADOPAGO_API_RETRY_ATTEMPTS', '3'))
MERCADOPAGO_API_RETRY_DELAY = int(os.getenv('MERCADOPAGO_API_RETRY_DELAY', '1')) 