# Generated by Django 4.2 on 2026-02-18 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("creacion_caso", "Creación caso"),
                            ("cambio_estado", "Cambio estado"),
                            ("asignacion", "Asignación"),
                            ("mensaje_recibido", "Mensaje recibido"),
                            ("mensaje_enviado", "Mensaje enviado"),
                            ("accion_ia", "Acción IA"),
                            ("sla_inicio", "SLA inicio"),
                            ("sla_pausa", "SLA pausa"),
                            ("sla_reanudacion", "SLA reanudación"),
                            ("sla_warning", "SLA warning"),
                            ("sla_vencido", "SLA vencido"),
                            ("reapertura", "Reapertura"),
                            ("adjunto_descarga", "Descarga adjunto"),
                            ("acceso_caso", "Acceso caso"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Tipo evento",
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="Payload")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="cases.case",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento auditoría",
                "verbose_name_plural": "Eventos auditoría",
                "db_table": "support_audit_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["case", "created_at"], name="support_aud_case_id_c1d6af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["company", "event_type", "created_at"],
                name="support_aud_company_2d93f5_idx",
            ),
        ),
    ]
