# Generated by Django 4.2 on 2026-02-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_config_events_company_nullable"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="idempotencyrecord",
            new_name="support_ide_case_id_5d4a66_idx",
            old_name="support_idem_case_i_actor_idx",
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("creacion_caso", "Creación caso"),
                    ("cambio_estado", "Cambio estado"),
                    ("asignacion", "Asignación"),
                    ("mensaje_recibido", "Mensaje recibido"),
                    ("mensaje_enviado", "Mensaje enviado"),
                    ("accion_ia", "Acción IA"),
                    ("sla_inicio", "SLA inicio"),
                    ("sla_pausa", "SLA pausa"),
                    ("sla_reanudacion", "SLA reanudación"),
                    ("sla_warning", "SLA warning"),
                    ("sla_vencido", "SLA vencido"),
                    ("reapertura", "Reapertura"),
                    ("adjunto_descarga", "Descarga adjunto"),
                    ("acceso_caso", "Acceso caso"),
                    ("config.updated", "Config actualizada"),
                    ("config.tested", "Config probada"),
                    ("config.activated", "Config activada"),
                    ("config.deactivated", "Config desactivada"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="Tipo evento",
            ),
        ),
    ]
