# Generated by Django 4.2 on 2025-07-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministraNETConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Configuration Name')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.IntegerField(default=3306, verbose_name='Port')),
                ('database', models.CharField(max_length=100, verbose_name='Database')),
                ('user', models.CharField(max_length=100, verbose_name='User')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AdministraNET Configuration',
                'verbose_name_plural': 'AdministraNET Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiendanube_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Tiendanube ID')),
                ('tiendanube_email', models.EmailField(max_length=254, unique=True, verbose_name='Tiendanube Email')),
                ('tiendanube_name', models.CharField(blank=True, max_length=255, verbose_name='Tiendanube Name')),
                ('tiendanube_document', models.CharField(blank=True, max_length=50, verbose_name='Tiendanube Document')),
                ('tiendanube_phone', models.CharField(blank=True, max_length=50, verbose_name='Tiendanube Phone')),
                ('tiendanube_address', models.TextField(blank=True, verbose_name='Tiendanube Address')),
                ('adminet_codigo', models.IntegerField(blank=True, null=True, verbose_name='AdministraNET Code')),
                ('adminet_nombre', models.CharField(blank=True, max_length=255, verbose_name='AdministraNET Name')),
                ('adminet_documento', models.CharField(blank=True, max_length=50, verbose_name='AdministraNET Document')),
                ('adminet_telefono', models.CharField(blank=True, max_length=50, verbose_name='AdministraNET Phone')),
                ('adminet_direccion', models.TextField(blank=True, verbose_name='AdministraNET Address')),
                ('sync_direction', models.CharField(choices=[('bidirectional', 'Bidirectional'), ('tiendanube_to_adminet', 'Tiendanube → AdministraNET'), ('adminet_to_tiendanube', 'AdministraNET → Tiendanube')], default='bidirectional', max_length=30, verbose_name='Sync Direction')),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error'), ('conflict', 'Conflict')], default='pending', max_length=20, verbose_name='Sync Status')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sync Enabled')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Customer Mapping',
                'verbose_name_plural': 'Customer Mappings',
                'ordering': ['tiendanube_email'],
            },
        ),
        migrations.CreateModel(
            name='OrderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiendanube_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Tiendanube ID')),
                ('tiendanube_number', models.CharField(blank=True, max_length=50, verbose_name='Tiendanube Number')),
                ('tiendanube_status', models.CharField(blank=True, max_length=50, verbose_name='Tiendanube Status')),
                ('tiendanube_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tiendanube Total')),
                ('tiendanube_customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Tiendanube Customer Email')),
                ('adminet_codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='AdministraNET Code')),
                ('adminet_numero', models.CharField(blank=True, max_length=50, verbose_name='AdministraNET Number')),
                ('adminet_estado', models.CharField(blank=True, max_length=50, verbose_name='AdministraNET Status')),
                ('adminet_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='AdministraNET Total')),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error'), ('conflict', 'Conflict')], default='pending', max_length=20, verbose_name='Sync Status')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sync Enabled')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Order Mapping',
                'verbose_name_plural': 'Order Mappings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiendanube_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Tiendanube ID')),
                ('tiendanube_name', models.CharField(blank=True, max_length=255, verbose_name='Tiendanube Name')),
                ('tiendanube_sku', models.CharField(blank=True, max_length=100, verbose_name='Tiendanube SKU')),
                ('tiendanube_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tiendanube Price')),
                ('tiendanube_stock', models.IntegerField(default=0, verbose_name='Tiendanube Stock')),
                ('adminet_codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='AdministraNET Code')),
                ('adminet_nombre', models.CharField(blank=True, max_length=255, verbose_name='AdministraNET Name')),
                ('adminet_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='AdministraNET Price')),
                ('adminet_stock', models.IntegerField(default=0, verbose_name='AdministraNET Stock')),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error'), ('conflict', 'Conflict')], default='pending', max_length=20, verbose_name='Sync Status')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sync Enabled')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product Mapping',
                'verbose_name_plural': 'Product Mappings',
                'ordering': ['tiendanube_name'],
            },
        ),
        migrations.CreateModel(
            name='TiendanubeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Configuration Name')),
                ('store_id', models.CharField(max_length=50, unique=True, verbose_name='Store ID')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access Token')),
                ('api_url', models.URLField(default='https://api.tiendanube.com/v1', verbose_name='API URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Tiendanube Configuration',
                'verbose_name_plural': 'Tiendanube Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('customer_sync', 'Customer Sync'), ('customer_create', 'Customer Create'), ('customer_update', 'Customer Update'), ('customer_delete', 'Customer Delete'), ('mapping_create', 'Mapping Create'), ('mapping_update', 'Mapping Update'), ('mapping_delete', 'Mapping Delete')], max_length=20, verbose_name='Sync Type')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial'), ('warning', 'Warning')], max_length=20, verbose_name='Status')),
                ('platform', models.CharField(choices=[('tiendanube', 'Tiendanube'), ('adminet', 'AdministraNET')], max_length=20, verbose_name='Platform')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('items_processed', models.IntegerField(default=0, verbose_name='Items Processed')),
                ('items_success', models.IntegerField(default=0, verbose_name='Items Success')),
                ('items_failed', models.IntegerField(default=0, verbose_name='Items Failed')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendanube_administranet.customermapping', verbose_name='Customer Mapping')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productmapping',
            index=models.Index(fields=['tiendanube_sku'], name='tiendanube__tiendan_d15237_idx'),
        ),
        migrations.AddIndex(
            model_name='productmapping',
            index=models.Index(fields=['adminet_codigo'], name='tiendanube__adminet_54ac66_idx'),
        ),
        migrations.AddIndex(
            model_name='productmapping',
            index=models.Index(fields=['sync_status'], name='tiendanube__sync_st_1a3296_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermapping',
            index=models.Index(fields=['tiendanube_number'], name='tiendanube__tiendan_f7c2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermapping',
            index=models.Index(fields=['adminet_codigo'], name='tiendanube__adminet_abf25e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermapping',
            index=models.Index(fields=['sync_status'], name='tiendanube__sync_st_ca647e_idx'),
        ),
        migrations.AddIndex(
            model_name='customermapping',
            index=models.Index(fields=['tiendanube_email'], name='tiendanube__tiendan_7dc410_idx'),
        ),
        migrations.AddIndex(
            model_name='customermapping',
            index=models.Index(fields=['adminet_codigo'], name='tiendanube__adminet_9fb13f_idx'),
        ),
        migrations.AddIndex(
            model_name='customermapping',
            index=models.Index(fields=['sync_status'], name='tiendanube__sync_st_00c71c_idx'),
        ),
        migrations.AddIndex(
            model_name='customermapping',
            index=models.Index(fields=['sync_enabled'], name='tiendanube__sync_en_1a4749_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['sync_type'], name='tiendanube__sync_ty_dc9bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status'], name='tiendanube__status_2704d4_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['platform'], name='tiendanube__platfor_9485d3_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['started_at'], name='tiendanube__started_229be8_idx'),
        ),
    ]
