# Generated by Django 4.2 on 2025-07-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning')], max_length=20, verbose_name='Status')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('validated_data', models.JSONField(blank=True, default=dict, verbose_name='Validated Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Validation Log',
                'verbose_name_plural': 'Validation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rule Name')),
                ('rule_type', models.CharField(choices=[('customer', 'Customer'), ('product', 'Product'), ('order', 'Order')], max_length=20, verbose_name='Rule Type')),
                ('validation_type', models.CharField(choices=[('required_field', 'Required Field'), ('field_format', 'Field Format'), ('business_rule', 'Business Rule'), ('custom', 'Custom')], max_length=20, verbose_name='Validation Type')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Field Name')),
                ('rule_config', models.JSONField(default=dict, verbose_name='Rule Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Critical')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Validation Rule',
                'verbose_name_plural': 'Validation Rules',
                'ordering': ['rule_type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='customermapping',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Mapping', 'verbose_name_plural': 'Customer Mappings'},
        ),
        migrations.AlterModelOptions(
            name='productmapping',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Mapping', 'verbose_name_plural': 'Product Mappings'},
        ),
        migrations.RemoveIndex(
            model_name='customermapping',
            name='tiendanube__tiendan_7dc410_idx',
        ),
        migrations.RemoveIndex(
            model_name='customermapping',
            name='tiendanube__adminet_9fb13f_idx',
        ),
        migrations.RemoveIndex(
            model_name='customermapping',
            name='tiendanube__sync_st_00c71c_idx',
        ),
        migrations.RemoveIndex(
            model_name='customermapping',
            name='tiendanube__sync_en_1a4749_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordermapping',
            name='tiendanube__tiendan_f7c2b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordermapping',
            name='tiendanube__adminet_abf25e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordermapping',
            name='tiendanube__sync_st_ca647e_idx',
        ),
        migrations.RemoveIndex(
            model_name='productmapping',
            name='tiendanube__tiendan_d15237_idx',
        ),
        migrations.RemoveIndex(
            model_name='productmapping',
            name='tiendanube__adminet_54ac66_idx',
        ),
        migrations.RemoveIndex(
            model_name='productmapping',
            name='tiendanube__sync_st_1a3296_idx',
        ),
        migrations.RemoveIndex(
            model_name='synclog',
            name='tiendanube__sync_ty_dc9bc1_idx',
        ),
        migrations.RemoveIndex(
            model_name='synclog',
            name='tiendanube__status_2704d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='synclog',
            name='tiendanube__platfor_9485d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='synclog',
            name='tiendanube__started_229be8_idx',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='items_failed',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='items_processed',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='items_success',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='mapping',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='message',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='platform',
        ),
        migrations.AddField(
            model_name='synclog',
            name='adminet_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiendanube_administranet.administranetconfig', verbose_name='AdministraNET Config'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='direction',
            field=models.CharField(choices=[('to_adminet', 'To AdministraNET'), ('from_adminet', 'From AdministraNET'), ('bidirectional', 'Bidirectional')], default='to_adminet', max_length=20, verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration (seconds)'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='failed_items',
            field=models.IntegerField(default=0, verbose_name='Failed Items'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='processed_items',
            field=models.IntegerField(default=0, verbose_name='Processed Items'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='successful_items',
            field=models.IntegerField(default=0, verbose_name='Successful Items'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='tiendanube_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiendanube_administranet.tiendanubeconfig', verbose_name='Tiendanube Config'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='total_items',
            field=models.IntegerField(default=0, verbose_name='Total Items'),
        ),
        migrations.AlterField(
            model_name='administranetconfig',
            name='database',
            field=models.CharField(max_length=255, verbose_name='Database'),
        ),
        migrations.AlterField(
            model_name='administranetconfig',
            name='user',
            field=models.CharField(max_length=255, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('product', 'Product'), ('order', 'Order'), ('full', 'Full Sync')], max_length=20, verbose_name='Sync Type'),
        ),
        migrations.AddField(
            model_name='validationlog',
            name='sync_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendanube_administranet.synclog', verbose_name='Sync Log'),
        ),
        migrations.AddField(
            model_name='validationlog',
            name='validation_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendanube_administranet.validationrule', verbose_name='Validation Rule'),
        ),
    ]
