# Generated by Django 4.2 on 2025-07-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0002_validationlog_validationrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.BigIntegerField(blank=True, null=True, verbose_name='Tiendanube Webhook ID')),
                ('webhook_url', models.URLField(verbose_name='Webhook URL')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook Secret')),
                ('events', models.JSONField(default=list, help_text='List of events this webhook is subscribed to', verbose_name='Subscribed Events')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Max Retries')),
                ('retry_delay', models.IntegerField(default=300, verbose_name='Retry Delay (seconds)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='Last Triggered')),
                ('tiendanube_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='tiendanube_administranet.tiendanubeconfig', verbose_name='Tiendanube Configuration')),
            ],
            options={
                'verbose_name': 'Webhook Configuration',
                'verbose_name_plural': 'Webhook Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='Event Type')),
                ('event_id', models.CharField(max_length=100, verbose_name='Event ID')),
                ('resource_id', models.BigIntegerField(blank=True, null=True, verbose_name='Resource ID')),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='Resource Type')),
                ('payload', models.JSONField(verbose_name='Event Payload')),
                ('headers', models.JSONField(default=dict, verbose_name='Request Headers')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retry', 'Retry')], default='pending', max_length=20, verbose_name='Status')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('processing_result', models.JSONField(blank=True, default=dict, verbose_name='Processing Result')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Next Retry At')),
                ('webhook_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='tiendanube_administranet.webhookconfig', verbose_name='Webhook Configuration')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('invalid_response', 'Invalid Response')], max_length=20, verbose_name='Status')),
                ('response_code', models.IntegerField(blank=True, null=True, verbose_name='Response Code')),
                ('response_body', models.TextField(blank=True, verbose_name='Response Body')),
                ('response_headers', models.JSONField(blank=True, default=dict, verbose_name='Response Headers')),
                ('request_duration', models.FloatField(blank=True, null=True, verbose_name='Request Duration (seconds)')),
                ('payload_size', models.IntegerField(blank=True, null=True, verbose_name='Payload Size (bytes)')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Received At')),
                ('webhook_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_delivery_logs', to='tiendanube_administranet.webhookconfig', verbose_name='Webhook Configuration')),
                ('webhook_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='tiendanube_administranet.webhookevent', verbose_name='Webhook Event')),
            ],
            options={
                'verbose_name': 'Webhook Delivery Log',
                'verbose_name_plural': 'Webhook Delivery Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type', 'status'], name='tiendanube__event_t_97375a_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['resource_type', 'resource_id'], name='tiendanube__resourc_cf5928_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['received_at'], name='tiendanube__receive_1b3b69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webhookconfig',
            unique_together={('tiendanube_config', 'webhook_url')},
        ),
    ]
