# Generated by Django 4.2 on 2025-07-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0003_webhookconfig_webhookevent_webhookdeliverylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_accepts_marketing',
            field=models.BooleanField(default=False, verbose_name='Tiendanube Accepts Marketing'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiendanube City'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiendanube Country'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiendanube Created At'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiendanube First Name'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiendanube Last Name'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_last_order_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tiendanube Last Order ID'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_multipass_identifier',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiendanube Multipass Identifier'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_notes',
            field=models.TextField(blank=True, verbose_name='Tiendanube Notes'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_orders_count',
            field=models.IntegerField(default=0, verbose_name='Tiendanube Orders Count'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tiendanube Postal Code'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiendanube State'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tiendanube Tags'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_tax_exempt',
            field=models.BooleanField(default=False, verbose_name='Tiendanube Tax Exempt'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_tax_exemptions',
            field=models.JSONField(blank=True, default=list, verbose_name='Tiendanube Tax Exemptions'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tiendanube Total Spent'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiendanube Updated At'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_verified_email',
            field=models.BooleanField(default=False, verbose_name='Tiendanube Verified Email'),
        ),
    ]
