# Generated by Django 4.2 on 2025-07-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0004_customermapping_tiendanube_accepts_marketing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiendanube_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Tiendanube Category ID')),
                ('tiendanube_name', models.CharField(blank=True, max_length=255, verbose_name='Tiendanube Category Name')),
                ('tiendanube_handle', models.CharField(blank=True, max_length=255, verbose_name='Tiendanube Category Handle')),
                ('tiendanube_description', models.TextField(blank=True, verbose_name='Tiendanube Category Description')),
                ('tiendanube_parent_id', models.BigIntegerField(blank=True, null=True, verbose_name='Tiendanube Parent Category ID')),
                ('tiendanube_image', models.URLField(blank=True, verbose_name='Tiendanube Category Image')),
                ('tiendanube_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Tiendanube Category Created At')),
                ('tiendanube_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Tiendanube Category Updated At')),
                ('adminet_codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='AdministraNET Category Code')),
                ('adminet_nombre', models.CharField(blank=True, max_length=255, verbose_name='AdministraNET Category Name')),
                ('adminet_descripcion', models.TextField(blank=True, verbose_name='AdministraNET Category Description')),
                ('adminet_categoria_padre', models.CharField(blank=True, max_length=50, null=True, verbose_name='AdministraNET Parent Category')),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error'), ('conflict', 'Conflict')], default='pending', max_length=20, verbose_name='Sync Status')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sync Enabled')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product Category Mapping',
                'verbose_name_plural': 'Product Category Mappings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_alto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='AdministraNET Height'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='AdministraNET Width'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_descripcion',
            field=models.TextField(blank=True, verbose_name='AdministraNET Description'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='AdministraNET Weight'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_profundo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='AdministraNET Depth'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='sync_description',
            field=models.BooleanField(default=True, verbose_name='Sync Description'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='sync_images',
            field=models.BooleanField(default=True, verbose_name='Sync Images'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='sync_price',
            field=models.BooleanField(default=True, verbose_name='Sync Price'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='sync_stock',
            field=models.BooleanField(default=True, verbose_name='Sync Stock'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='Tiendanube Categories'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tiendanube Compare At Price'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tiendanube Cost'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiendanube Created At'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tiendanube Depth (cm)'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_description',
            field=models.TextField(blank=True, verbose_name='Tiendanube Description'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_featured',
            field=models.BooleanField(default=False, verbose_name='Tiendanube Featured'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_free_shipping',
            field=models.BooleanField(default=False, verbose_name='Tiendanube Free Shipping'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_handle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiendanube Handle'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tiendanube Height (cm)'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_images',
            field=models.JSONField(blank=True, default=list, verbose_name='Tiendanube Images'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_product_type',
            field=models.CharField(choices=[('physical', 'Physical Product'), ('digital', 'Digital Product'), ('service', 'Service')], default='physical', max_length=20, verbose_name='Tiendanube Product Type'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_published',
            field=models.BooleanField(default=True, verbose_name='Tiendanube Published'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_seo_description',
            field=models.TextField(blank=True, verbose_name='Tiendanube SEO Description'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiendanube SEO Title'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiendanube Updated At'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_videos',
            field=models.JSONField(blank=True, default=list, verbose_name='Tiendanube Videos'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Tiendanube Weight (kg)'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tiendanube Width (cm)'),
        ),
        migrations.CreateModel(
            name='ProductVariantMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiendanube_variant_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Tiendanube Variant ID')),
                ('tiendanube_name', models.CharField(blank=True, max_length=255, verbose_name='Tiendanube Variant Name')),
                ('tiendanube_sku', models.CharField(blank=True, max_length=100, verbose_name='Tiendanube Variant SKU')),
                ('tiendanube_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tiendanube Variant Price')),
                ('tiendanube_compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tiendanube Variant Compare At Price')),
                ('tiendanube_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tiendanube Variant Cost')),
                ('tiendanube_stock', models.IntegerField(default=0, verbose_name='Tiendanube Variant Stock')),
                ('tiendanube_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Tiendanube Variant Weight')),
                ('tiendanube_width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tiendanube Variant Width')),
                ('tiendanube_height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tiendanube Variant Height')),
                ('tiendanube_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tiendanube Variant Depth')),
                ('tiendanube_free_shipping', models.BooleanField(default=False, verbose_name='Tiendanube Variant Free Shipping')),
                ('tiendanube_published', models.BooleanField(default=True, verbose_name='Tiendanube Variant Published')),
                ('tiendanube_values', models.JSONField(blank=True, default=dict, verbose_name='Tiendanube Variant Values')),
                ('tiendanube_images', models.JSONField(blank=True, default=list, verbose_name='Tiendanube Variant Images')),
                ('tiendanube_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Tiendanube Variant Created At')),
                ('tiendanube_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Tiendanube Variant Updated At')),
                ('adminet_codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='AdministraNET Variant Code')),
                ('adminet_nombre', models.CharField(blank=True, max_length=255, verbose_name='AdministraNET Variant Name')),
                ('adminet_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='AdministraNET Variant Price')),
                ('adminet_stock', models.IntegerField(default=0, verbose_name='AdministraNET Variant Stock')),
                ('adminet_peso', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='AdministraNET Variant Weight')),
                ('adminet_ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='AdministraNET Variant Width')),
                ('adminet_alto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='AdministraNET Variant Height')),
                ('adminet_profundo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='AdministraNET Variant Depth')),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error'), ('conflict', 'Conflict')], default='pending', max_length=20, verbose_name='Sync Status')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sync Enabled')),
                ('sync_price', models.BooleanField(default=True, verbose_name='Sync Price')),
                ('sync_stock', models.BooleanField(default=True, verbose_name='Sync Stock')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tiendanube_administranet.productmapping', verbose_name='Product Mapping')),
            ],
            options={
                'verbose_name': 'Product Variant Mapping',
                'verbose_name_plural': 'Product Variant Mappings',
                'ordering': ['-created_at'],
            },
        ),
    ]
