# Generated by Django 4.2 on 2025-07-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0005_productcategorymapping_productmapping_adminet_alto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmapping',
            name='adminet_alto',
        ),
        migrations.RemoveField(
            model_name='productmapping',
            name='adminet_ancho',
        ),
        migrations.RemoveField(
            model_name='productmapping',
            name='adminet_codigo',
        ),
        migrations.RemoveField(
            model_name='productmapping',
            name='adminet_descripcion',
        ),
        migrations.RemoveField(
            model_name='productmapping',
            name='adminet_peso',
        ),
        migrations.RemoveField(
            model_name='productmapping',
            name='adminet_precio',
        ),
        migrations.RemoveField(
            model_name='productmapping',
            name='adminet_profundo',
        ),
        migrations.RemoveField(
            model_name='productvariantmapping',
            name='adminet_alto',
        ),
        migrations.RemoveField(
            model_name='productvariantmapping',
            name='adminet_ancho',
        ),
        migrations.RemoveField(
            model_name='productvariantmapping',
            name='adminet_codigo',
        ),
        migrations.RemoveField(
            model_name='productvariantmapping',
            name='adminet_peso',
        ),
        migrations.RemoveField(
            model_name='productvariantmapping',
            name='adminet_precio',
        ),
        migrations.RemoveField(
            model_name='productvariantmapping',
            name='adminet_profundo',
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_alicuota',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alicuota IVA AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_alicuota_ib',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alicuota IB AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_codigo_articulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código Artículo AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_codigo_barra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de Barra AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_codigo_barra_f',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de Barra F AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_codigo_marca',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Marca AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_codigo_modelo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Modelo AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_codigo_proveedor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Proveedor AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_codigo_rubro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Rubro AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_codigo_subrubro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código SubRubro AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_detalle',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_detalle_web',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle Web AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_discontinuo',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Discontinuo AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_disponible_compra',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Disponible Compra AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_disponible_venta',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Disponible Venta AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_ecommerce',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Ecommerce AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_fecha_alta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Alta AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_fecha_mod',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Modificación AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID Artículo AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_id_manual',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Manual AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_moneda',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Moneda AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_precio_1v',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio 1V AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_precio_2v',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio 2V AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_precio_3v',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio 3V AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_precio_4v',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio 4V AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_precio_5v',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio 5V AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_precio_costo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio Costo AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_stock_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Stock Máximo AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_stock_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Stock Mínimo AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_tipo_ib',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo IB AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_tipo_iva',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo IVA AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_alicuota',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alicuota IVA Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_alicuota_ib',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alicuota IB Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_codigo_articulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_codigo_barra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de Barra Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_codigo_marca',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Marca Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_codigo_modelo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Modelo Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_codigo_proveedor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Proveedor Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_detalle',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_detalle_web',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle Web Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_discontinuo',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Discontinuo Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_disponible_compra',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Disponible Compra Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_disponible_venta',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Disponible Venta Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_ecommerce',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Ecommerce Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_fecha_alta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Alta Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_fecha_mod',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Modificación Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_id_manual',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Manual Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_moneda',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Moneda Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_precio_1v',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio 1V Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_precio_costo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio Costo Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_tipo_ib',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo IB Variante AdministraNET'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='adminet_tipo_iva',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo IVA Variante AdministraNET'),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='adminet_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Artículo AdministraNET'),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='adminet_stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock AdministraNET'),
        ),
        migrations.AlterField(
            model_name='productvariantmapping',
            name='adminet_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Variante AdministraNET'),
        ),
        migrations.AlterField(
            model_name='productvariantmapping',
            name='adminet_stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock Variante AdministraNET'),
        ),
    ]
