# Generated by Django 4.2 on 2025-07-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0006_remove_productmapping_adminet_alto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermapping',
            name='adminet_cod_provincia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Provincia AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_estado',
            field=models.CharField(blank=True, max_length=30, verbose_name='Estado AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_fecha_alta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Alta AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_id_departamento',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Departamento AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='tiendanube_billing_address',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tiendanube Billing Address'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='tiendanube_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiendanube Created At'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='tiendanube_currency',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tiendanube Currency'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='tiendanube_customer_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tiendanube Customer ID'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='tiendanube_customer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiendanube Customer Name'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='tiendanube_notes',
            field=models.TextField(blank=True, verbose_name='Tiendanube Notes'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='tiendanube_payment_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiendanube Payment Method'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='tiendanube_payment_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tiendanube Payment Status'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='tiendanube_shipping_address',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tiendanube Shipping Address'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='tiendanube_shipping_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiendanube Shipping Method'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='tiendanube_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiendanube Updated At'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='adminet_promo_destacado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Promo Destacado AdministraNET'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_brand',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiendanube Brand'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='tiendanube_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tiendanube Tags'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='tiendanube_options',
            field=models.JSONField(blank=True, default=list, verbose_name='Tiendanube Variant Options'),
        ),
        migrations.AddField(
            model_name='productvariantmapping',
            name='tiendanube_product_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tiendanube Product ID'),
        ),
    ]
