# Generated by Django 4.2 on 2025-07-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0007_customermapping_adminet_cod_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermapping',
            name='tiendanube_address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tiendanube Address Number'),
        ),
    ]
