# Generated by Django 4.2 on 2025-07-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0008_customermapping_tiendanube_address_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermapping',
            name='tiendanube_address_number',
        ),
    ]
