# Generated by Django 4.2 on 2025-07-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0009_remove_customermapping_tiendanube_address_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermapping',
            name='adminet_calle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Calle AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_dpto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Departamento AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_nro_calle',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número Calle AdministraNET'),
        ),
    ]
