# Generated by Django 4.2 on 2025-07-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0010_add_adminet_address_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministraNETDepartamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Departamento')),
                ('nombre_departamento', models.CharField(blank=True, max_length=50, verbose_name='Nombre Departamento')),
                ('cod_provincia', models.IntegerField(verbose_name='Código Provincia')),
                ('anulado', models.CharField(blank=True, max_length=5, verbose_name='Anulado')),
                ('cod_postal', models.CharField(blank=True, max_length=50, verbose_name='Código Postal')),
            ],
            options={
                'verbose_name': 'AdministraNET Departamento',
                'verbose_name_plural': 'AdministraNET Departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='AdministraNETDistrito',
            fields=[
                ('id_distrito', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Distrito')),
                ('id_departamento', models.IntegerField(blank=True, null=True, verbose_name='ID Departamento')),
                ('nombre_distrito', models.CharField(blank=True, max_length=50, verbose_name='Nombre Distrito')),
                ('anulado', models.CharField(blank=True, max_length=5, verbose_name='Anulado')),
                ('cod_postal', models.CharField(blank=True, max_length=50, verbose_name='Código Postal')),
            ],
            options={
                'verbose_name': 'AdministraNET Distrito',
                'verbose_name_plural': 'AdministraNET Distritos',
                'db_table': 'distrito',
            },
        ),
        migrations.CreateModel(
            name='AdministraNETPais',
            fields=[
                ('id_pais', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID País')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('anulado', models.CharField(blank=True, max_length=2, verbose_name='Anulado')),
            ],
            options={
                'verbose_name': 'AdministraNET País',
                'verbose_name_plural': 'AdministraNET Países',
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='AdministraNETProvincia',
            fields=[
                ('cod_provincia', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Provincia')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('anulado', models.CharField(blank=True, max_length=5, verbose_name='Anulado')),
                ('id_pais', models.IntegerField(blank=True, null=True, verbose_name='ID País')),
                ('cod_afip', models.IntegerField(blank=True, null=True, verbose_name='Código AFIP')),
                ('id_juridic_convenio', models.IntegerField(blank=True, null=True, verbose_name='ID Jurídico Convenio')),
                ('id_pc', models.IntegerField(blank=True, null=True, verbose_name='ID PC')),
            ],
            options={
                'verbose_name': 'AdministraNET Provincia',
                'verbose_name_plural': 'AdministraNET Provincias',
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='AdministraNETTipoCliente',
            fields=[
                ('id_tipo_cliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Tipo Cliente')),
                ('nombre_tipo_cliente', models.CharField(blank=True, max_length=50, verbose_name='Nombre Tipo Cliente')),
                ('anulado', models.CharField(blank=True, max_length=5, verbose_name='Anulado')),
            ],
            options={
                'verbose_name': 'AdministraNET Tipo Cliente',
                'verbose_name_plural': 'AdministraNET Tipos Cliente',
                'db_table': 'tipo_cliente',
            },
        ),
        migrations.CreateModel(
            name='AdministraNETViajante',
            fields=[
                ('cod_viajante', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Viajante')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('comision_vta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Comisión Venta')),
                ('comision_cob', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Comisión Cobro')),
                ('zona', models.CharField(blank=True, max_length=50, verbose_name='Zona')),
                ('observaciones', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('anulado', models.CharField(blank=True, max_length=5, verbose_name='Anulado')),
                ('web_desc_renglon', models.CharField(blank=True, max_length=2, verbose_name='Web Desc Renglón')),
                ('web_desc_pie', models.CharField(blank=True, max_length=2, verbose_name='Web Desc Pie')),
                ('web_cliente_todos', models.CharField(blank=True, max_length=2, verbose_name='Web Cliente Todos')),
                ('cobrador', models.CharField(blank=True, max_length=2, verbose_name='Cobrador')),
                ('clave_caja', models.CharField(blank=True, max_length=50, verbose_name='Clave Caja')),
                ('logueado', models.CharField(blank=True, max_length=2, verbose_name='Logueado')),
                ('detalle_logueo', models.CharField(blank=True, max_length=500, verbose_name='Detalle Logueo')),
                ('ip_logueo', models.CharField(blank=True, max_length=30, verbose_name='IP Logueo')),
                ('comisiones_avanzadas', models.CharField(blank=True, max_length=2, verbose_name='Comisiones Avanzadas')),
            ],
            options={
                'verbose_name': 'AdministraNET Viajante',
                'verbose_name_plural': 'AdministraNET Viajantes',
                'db_table': 'viajantes',
            },
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_cliente_ecommerce',
            field=models.CharField(blank=True, max_length=5, verbose_name='Cliente Ecommerce AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_cod_viajante',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Viajante AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Crédito AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_cuit',
            field=models.CharField(blank=True, max_length=20, verbose_name='CUIT AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Descuento AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_fecha_ultima_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Última Compra AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_id_distrito',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Distrito AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_id_manual_cli',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID Manual Cliente AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_id_pais',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID País AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_lista_precio',
            field=models.CharField(blank=True, max_length=60, verbose_name='Lista Precio AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_nombre_fantasia',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nombre Fantasía AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='Saldo AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_tipo_cliente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tipo Cliente AdministraNET'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='adminet_tipo_doc',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tipo Documento AdministraNET'),
        ),
    ]
