# Generated by Django 4.2 on 2025-07-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0011_add_all_adminet_customer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermapping',
            name='datos_completos',
            field=models.BooleanField(default=False, verbose_name='Datos Completos'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='fecha_registro_incompleto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Registro Incompleto'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='intentos_completar_datos',
            field=models.IntegerField(default=0, verbose_name='Intentos Completar Datos'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='ultimo_intento_completar',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Intento Completar'),
        ),
        migrations.AddField(
            model_name='customermapping',
            name='workflow_estado',
            field=models.CharField(choices=[('incompleto', 'Datos Incompletos'), ('pendiente', 'Pendiente de Completar'), ('completo', 'Datos Completos'), ('abandonado', 'Abandonado')], default='incompleto', max_length=20, verbose_name='Estado del Workflow'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_calle_entrega',
            field=models.CharField(blank=True, max_length=255, verbose_name='Calle Entrega AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_calle_facturacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Calle Facturación AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_ciudad_entrega',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad Entrega AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_ciudad_facturacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad Facturación AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_codigo_postal_entrega',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Postal Entrega AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_codigo_postal_facturacion',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Postal Facturación AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_direccion_entrega',
            field=models.TextField(blank=True, verbose_name='Dirección de Entrega AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_direccion_facturacion',
            field=models.TextField(blank=True, verbose_name='Dirección de Facturación AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_dpto_entrega',
            field=models.CharField(blank=True, max_length=50, verbose_name='Departamento Entrega AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_dpto_facturacion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Departamento Facturación AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_nro_calle_entrega',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número Calle Entrega AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_nro_calle_facturacion',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número Calle Facturación AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_provincia_entrega',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia Entrega AdministraNET'),
        ),
        migrations.AddField(
            model_name='ordermapping',
            name='adminet_provincia_facturacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia Facturación AdministraNET'),
        ),
    ]
