# Generated by Django 4.2 on 2025-07-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0012_customermapping_datos_completos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMappingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(choices=[('customer', 'Customer'), ('product', 'Product'), ('order', 'Order'), ('variant', 'Product Variant'), ('category', 'Category')], max_length=20, verbose_name='Mapping Type')),
                ('field_type', models.CharField(choices=[('adminet', 'AdministraNET'), ('tiendanube', 'Tiendanube')], max_length=20, verbose_name='Field Type')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('field_display_name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('field_description', models.TextField(blank=True, verbose_name='Field Description')),
                ('is_mappable', models.BooleanField(default=True, verbose_name='Is Mappable')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
                ('is_primary_key', models.BooleanField(default=False, verbose_name='Is Primary Key')),
                ('mapped_to_field', models.CharField(blank=True, help_text='Field name in the other system', max_length=100, verbose_name='Mapped To Field')),
                ('mapping_notes', models.TextField(blank=True, verbose_name='Mapping Notes')),
                ('transformation_type', models.CharField(choices=[('direct', 'Direct Mapping'), ('address_parse', 'Address Parsing'), ('name_mapping', 'Name Mapping'), ('custom', 'Custom Transformation')], default='direct', max_length=50, verbose_name='Transformation Type')),
                ('transformation_config', models.JSONField(blank=True, default=dict, verbose_name='Transformation Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Field Mapping Configuration',
                'verbose_name_plural': 'Field Mapping Configurations',
                'ordering': ['mapping_type', 'field_type', 'display_order'],
                'unique_together': {('mapping_type', 'field_type', 'field_name')},
            },
        ),
    ]
