# Generated by Django 4.2 on 2025-10-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0013_fieldmappingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='administranetconfig',
            name='deposito_tiendanube_id',
            field=models.IntegerField(blank=True, help_text='ID del depósito en AdministraNET que se sincronizará con TiendaNube', null=True, verbose_name='Depósito TiendaNube'),
        ),
    ]
