# Generated by Django 4.2 on 2025-10-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0014_add_deposito_tiendanube'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendanubeconfig',
            name='auto_restock',
            field=models.BooleanField(default=False, help_text='Reabastecimiento automático cuando el stock esté bajo', verbose_name='Auto Restock'),
        ),
        migrations.AddField(
            model_name='tiendanubeconfig',
            name='auto_sync',
            field=models.BooleanField(default=True, help_text='Habilitar sincronización automática', verbose_name='Auto Sync'),
        ),
        migrations.AddField(
            model_name='tiendanubeconfig',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='Última sincronización realizada', null=True, verbose_name='Last Sync'),
        ),
        migrations.AddField(
            model_name='tiendanubeconfig',
            name='restock_quantity',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Cantidad a reabastecer cuando se active el reabastecimiento', max_digits=10, verbose_name='Restock Quantity'),
        ),
        migrations.AddField(
            model_name='tiendanubeconfig',
            name='restock_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Umbral mínimo de stock para reabastecimiento', max_digits=10, verbose_name='Restock Threshold'),
        ),
        migrations.AddField(
            model_name='tiendanubeconfig',
            name='sync_customers',
            field=models.BooleanField(default=True, help_text='Sincronizar clientes', verbose_name='Sync Customers'),
        ),
        migrations.AddField(
            model_name='tiendanubeconfig',
            name='sync_interval',
            field=models.IntegerField(default=30, help_text='Intervalo en minutos para sincronización automática', verbose_name='Sync Interval (minutes)'),
        ),
        migrations.AddField(
            model_name='tiendanubeconfig',
            name='sync_orders',
            field=models.BooleanField(default=True, help_text='Sincronizar pedidos', verbose_name='Sync Orders'),
        ),
        migrations.AddField(
            model_name='tiendanubeconfig',
            name='sync_products',
            field=models.BooleanField(default=True, help_text='Sincronizar productos', verbose_name='Sync Products'),
        ),
        migrations.AddField(
            model_name='tiendanubeconfig',
            name='sync_stock',
            field=models.BooleanField(default=True, help_text='Sincronizar stock', verbose_name='Sync Stock'),
        ),
    ]
