# Generated by Django 4.2 on 2025-10-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0015_tiendanubeconfig_auto_restock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendanubeconfig',
            name='auto_restock',
        ),
        migrations.RemoveField(
            model_name='tiendanubeconfig',
            name='restock_threshold',
        ),
        migrations.RemoveField(
            model_name='tiendanubeconfig',
            name='restock_quantity',
        ),
    ]
