# Generated by Django 4.2 on 2025-10-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0016_remove_auto_restock_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendanubeconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Secret para verificación de webhooks de TiendaNube', max_length=255, verbose_name='Webhook Secret'),
        ),
    ]
