# Generated by Django 4.2 on 2025-10-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0017_add_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='administranetconfig',
            name='sucursal_tiendanube_id',
            field=models.IntegerField(default=1, help_text='ID de la sucursal para órdenes de Tiendanube', verbose_name='Sucursal Tiendanube ID'),
        ),
    ]
