# Generated by Django 4.2 on 2025-10-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0018_administranetconfig_sucursal_tiendanube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='administranetconfig',
            name='viajante_tiendanube_id',
            field=models.IntegerField(blank=True, help_text='ID del vendedor para órdenes de Tiendanube', null=True, verbose_name='Vendedor Tiendanube ID'),
        ),
    ]
