# Generated by Django 4.2 on 2025-10-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendanube_administranet', '0019_administranetconfig_viajante_tiendanube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='administranetconfig',
            name='punto_venta_tiendanube_id',
            field=models.IntegerField(blank=True, help_text='ID del punto de venta para numeración de comprobantes (ej: 0001-00000001)', null=True, verbose_name='Punto de Venta Tiendanube ID'),
        ),
    ]
