"""
Configuración de pantallas listado mayoristapp (F1/F2).

Cada entrada alimenta ``ListadoMayoristappView`` + ``listado_mayoristapp.html``.
"""

from __future__ import annotations

from typing import Any

# columnas estándar comprobantes (PED/PRE/REM/FE/NC)
_COLS_COMPROBANTE = [
    {"key": "FechaB", "label": "Fecha"},
    {"key": "NroComprobante", "label": "N.º comp."},
    {"key": "nombre_cliente", "label": "Cliente"},
    {"key": "CondVenta", "label": "Cond. vta."},
    {"key": "SubTotalDesc", "label": "Subtotal", "fmt": "money"},
    {"key": "IVA", "label": "IVA", "fmt": "money"},
    {"key": "Total", "label": "Total", "fmt": "money"},
    {"key": "TipoPedido", "label": "Tipo"},
    {"key": "Estado", "label": "Estado"},
    {"key": "Anulado", "label": "Anul."},
]

MAYORISTAPP_LISTADOS: dict[str, dict[str, Any]] = {
    "remitos": {
        "title": "Remitos",
        "subtitle": "Listado de remitos (tipo REM)",
        "api_url_name": "ecom:mayoristapp_comprobantes_remitos",
        "api_method": "POST",
        "api_query": "ajax=1",
        "payload_base": {"ajax": "true", "vendedor": "true"},
        "results_key": "filas",
        "busca_tipo_label": "Tipo remito",
        "sugerencias_url_name": "ecom:mayoristapp_comprobantes_sugerencias_nro",
        "sugerencias_query": "ajax=1&tipo=REM",
        "columns": _COLS_COMPROBANTE,
    },
    "facturas": {
        "title": "Facturas electrónicas",
        "subtitle": "Listado de facturas electrónicas",
        "api_url_name": "ecom:mayoristapp_fe_factura_electronica_listado",
        "api_method": "POST",
        "api_query": "ajax=1",
        "payload_base": {"ajax": "true", "vendedor": "true"},
        "results_key": "filas",
        "sugerencias_url_name": "ecom:mayoristapp_fe_factura_electronica_sugerencias_nro",
        "sugerencias_query": "ajax=1",
        "columns": _COLS_COMPROBANTE,
    },
    "recibos": {
        "title": "Recibos web",
        "subtitle": "Listado de recibos de cobranza",
        "api_url_name": "ecom:mayoristapp_recibos_listado",
        "api_method": "POST",
        "api_query": "ajax=1&consulta=1",
        "payload_base": {"ajax": "true", "consulta": "1"},
        "results_key": "filas",
        "columns": [
            {"key": "FechaB", "label": "Fecha"},
            {"key": "NroComprobante", "label": "N.º recibo"},
            {"key": "nombre_cliente", "label": "Cliente"},
            {"key": "Total", "label": "Total", "fmt": "money"},
            {"key": "Estado", "label": "Estado"},
            {"key": "Anulado", "label": "Anul."},
        ],
    },
    "nota-credito": {
        "title": "Notas de crédito",
        "subtitle": "Listado de notas de crédito",
        "api_url_name": "ecom:mayoristapp_fe_nota_credito_listado",
        "api_method": "POST",
        "api_query": "ajax=1",
        "payload_base": {"ajax": "true", "vendedor": "true"},
        "results_key": "filas",
        "sugerencias_url_name": "ecom:mayoristapp_fe_nota_credito_sugerencias_nro",
        "sugerencias_query": "ajax=1",
        "columns": _COLS_COMPROBANTE,
    },
    "devoluciones": {
        "title": "Devoluciones",
        "subtitle": "Gestión y listado de devoluciones",
        "api_url_name": "ecom:mayoristapp_estadisticas_devoluciones",
        "api_method": "POST",
        "api_query": "ajax=1",
        "payload_base": {"ajax": "true", "queAccion": "listar"},
        "results_key": "filas",
        "sugerencias_url_name": "ecom:mayoristapp_estadisticas_devoluciones_sugerencias_nro",
        "sugerencias_query": "ajax=1",
        "columns": [
            {"key": "FechaB", "label": "Fecha"},
            {"key": "NroComprobante", "label": "N.º DEV"},
            {"key": "nombre_cliente", "label": "Cliente"},
            {"key": "Total", "label": "Total", "fmt": "money"},
            {"key": "Estado", "label": "Estado"},
        ],
    },
    "promociones": {
        "title": "Promociones",
        "subtitle": "Artículos en promoción vigente",
        "api_url_name": "ecom:mayoristapp_precios_promociones",
        "api_method": "GET",
        "api_query": "ajax=1",
        "payload_base": {},
        "results_key": "articulos",
        "show_filters": True,
        "filter_mode": "promociones",
        "columns": [
            {"key": "IDArt", "label": "Cód."},
            {"key": "Descripcion", "label": "Descripción"},
            {"key": "rubro", "label": "Rubro"},
            {"key": "marca", "label": "Marca"},
            {"key": "precio", "label": "Precio", "fmt": "money"},
        ],
    },
    "articulos-remitados": {
        "title": "Artículos remitados",
        "subtitle": "Líneas de stock en remitos (tipo REM)",
        "api_url_name": "ecom:mayoristapp_articulo_remito_listado",
        "api_method": "POST",
        "api_query": "ajax=1",
        "payload_base": {"ajax": "true"},
        "results_key": "filas",
        "busca_tipo_label": "Tipo remito",
        "sugerencias_url_name": "ecom:mayoristapp_comprobantes_sugerencias_nro",
        "sugerencias_query": "ajax=1&tipo=REM",
        "columns": [
            {"key": "FechaB", "label": "Fecha"},
            {"key": "NroComprobante", "label": "Remito"},
            {"key": "Descripcion", "label": "Artículo"},
            {"key": "Cantidad", "label": "Cant."},
            {"key": "nombre_cliente", "label": "Cliente"},
            {"key": "Estado", "label": "Estado"},
            {"key": "Total", "label": "Total", "fmt": "money"},
        ],
    },
}

# F2 — portal cliente (requiere idcliente en sesión)
PORTAL_CLIENTE_LISTADOS: dict[str, dict[str, Any]] = {
    "consumos": {
        "title": "Consumos del cliente",
        "subtitle": "Resumen de consumos (portal cliente)",
        "api_url_name": "ecom:mayoristapp_ctacte_consumos_resumen",
        "api_method": "POST",
        "api_query": "ajax=1",
        "payload_base": {"ajax": "true"},
        "results_key": "filas",
        "portal_cliente": True,
        "columns": [
            {"key": "periodo", "label": "Período"},
            {"key": "total", "label": "Total", "fmt": "money"},
        ],
    },
    "cuenta-corriente": {
        "title": "Cuenta corriente",
        "subtitle": "Movimientos de cuenta corriente del cliente",
        "api_url_name": "ecom:mayoristapp_ctacte_movimientos",
        "api_method": "POST",
        "api_query": "ajax=1",
        "payload_base": {"ajax": "true"},
        "results_key": "filas",
        "portal_cliente": True,
        "sugerencias_url_name": "ecom:mayoristapp_ctacte_sugerencias_nro",
        "sugerencias_query": "ajax=1",
        "columns": [
            {"key": "FechaB", "label": "Fecha"},
            {"key": "NroComprobante", "label": "Comprobante"},
            {"key": "TipoComprobante", "label": "Tipo"},
            {"key": "Total", "label": "Importe", "fmt": "money"},
            {"key": "Saldo", "label": "Saldo", "fmt": "money"},
        ],
    },
    "no-cancelados": {
        "title": "Comprobantes no cancelados",
        "subtitle": "Saldo pendiente de comprobantes del cliente",
        "api_url_name": "ecom:mayoristapp_comprobantes_no_cancelados",
        "api_method": "POST",
        "api_query": "ajax=1",
        "payload_base": {"ajax": "true"},
        "results_key": "filas",
        "portal_cliente": True,
        "columns": [
            {"key": "FechaB", "label": "Fecha"},
            {"key": "NroComprobante", "label": "Comprobante"},
            {"key": "TipoComprobante", "label": "Tipo"},
            {"key": "Total", "label": "Total", "fmt": "money"},
            {"key": "Saldo", "label": "Saldo", "fmt": "money"},
        ],
    },
    "pedidos-cliente": {
        "title": "Pedidos del cliente",
        "subtitle": "Pedidos emitidos en cuenta corriente",
        "api_url_name": "ecom:mayoristapp_ctacte_pedidos",
        "api_method": "POST",
        "api_query": "ajax=1",
        "payload_base": {"ajax": "true"},
        "results_key": "filas",
        "portal_cliente": True,
        "sugerencias_url_name": "ecom:mayoristapp_ctacte_pedidos_sugerencias_nro",
        "sugerencias_query": "ajax=1",
        "columns": _COLS_COMPROBANTE,
    },
}

HUB_LISTADO_URLS: dict[str, str] = {
    "Promociones": "ecom:mayoristapp_listado_promociones",
    "Devoluciones": "ecom:mayoristapp_listado_devoluciones",
    "Listado de clientes": "ecom:mayoristapp_clientes",
    "Consumos cliente": "ecom:mayoristapp_portal_consumos",
    "Cuenta corriente": "ecom:mayoristapp_portal_cuenta_corriente",
    "Comprobantes no cancelados": "ecom:mayoristapp_portal_no_cancelados",
    "Artículos remitados": "ecom:mayoristapp_listado_articulos_remitados",
    "Facturas": "ecom:mayoristapp_listado_facturas",
    "Recibos web": "ecom:mayoristapp_listado_recibos",
    "Nota de crédito": "ecom:mayoristapp_listado_nota_credito",
    "Remitos": "ecom:mayoristapp_listado_remitos",
}
