from django.urls import path
from django.views.generic import RedirectView

from ecom import views
from ecom.logistica_legacy_redirects import redirect_api_remito_legacy
from ecom.mayoristapp_web_views import (
    AltaReciboMayoristappView,
    CompraMayoristaView,
    HubMayoristappView,
    PedidosVendedorView,
    PresupuestosVendedorView,
)
from ecom.pedido_gestion_views import (
    AprobacionLoteAprobarAPIView,
    AprobacionLoteRechazarAPIView,
    AprobacionPedidoAprobarAPIView,
    AprobacionPedidoRechazarAPIView,
    AprobacionPendientesAPIView,
    CarritoDesdePedidoAPIView,
    CarritoDesdePedidoPreviewAPIView,
    CompraMayoristaContextoAPIView,
    ComprobanteComercialCabeceraAPIView,
    ComprobanteComercialDetalleAPIView,
    ComprobanteComercialDetalleView,
    LoteResumenAPIView,
    LoteResumenView,
    PedidoCabeceraV1APIView,
    PedidoComprobantePDFAPIView,
    PedidoDetalleView,
    PedidosHubAPIView,
    PedidosHubArchivarDraftAPIView,
    PedidosHubArchivarCarritoAPIView,
    PedidosHubEliminarDraftAPIView,
    PedidosHubMigrarCarritoAPIView,
    PedidosHubView,
    PedidosKpisAPIView,
    PedidosRecientesAPIView,
    PresupuestoConvertirPedidoAPIView,
)
from ecom.vendedor_cliente_marca_views import (
    ConfigVendedorClienteMarcaView,
    VendedorClienteMarcaAnularAPIView,
    VendedorClienteMarcaClientesAPIView,
    VendedorClienteMarcaCrearAPIView,
    VendedorClienteMarcaMarcasAPIView,
    VendedorClienteMarcaSucursalesAPIView,
    VendedorClienteMarcaTernasAPIView,
    VendedorClienteMarcaVendedoresAPIView,
)
from ecom.ajustes_ventas_views import AjustesVentasAPIView, AjustesVentasView, AjustesWorkflowAPIView
from ecom.jerarquia_views import JerarquiaNodosAPIView, JerarquiaUsuariosAPIView
from ecom.pedido_masivo_views import (
    PedidoMasivoAbrirAPIView,
    PedidoMasivoAbrirPedidoAPIView,
    PedidoMasivoArticulosAPIView,
    PedidoMasivoCeldaAPIView,
    PedidoMasivoClientesAPIView,
    PedidoMasivoConfirmarAPIView,
    PedidoMasivoAnularAPIView,
    PedidoMasivoDescuentoFilaAPIView,
    PedidoMasivoDescuentoPieAPIView,
    PedidoMasivoEliminarFilaAPIView,
    PedidoMasivoMatrizAPIView,
    PedidoMasivoPreviewAPIView,
    PedidoMasivoSucursalesAPIView,
    PedidoMasivoSucursalesView,
)
from ecom.logistica_estado_pedidos_views import (
    EstadoPedidosKanbanAPIView,
    EstadoPedidosPreparacionView,
)
from ecom.cliente_relay_views import (
    ClienteBuscarRelayAPIView,
    ClienteComprobanteFormularioRelayAPIView,
    ClienteContactoRelayAPIView,
    ClienteDomicilioOpcionesVisitaRelayAPIView,
    ClienteDomicilioRelayAPIView,
    ClienteRapidoRelayAPIView,
    ClienteSeleccionadoRelayAPIView,
    ClienteSeleccionarRelayAPIView,
)
from ecom.precio_relay_views import (
    CondicionesVentaRelayAPIView,
    ListaPrecioRelayAPIView,
    PromocionesRelayAPIView,
)
from ecom.comprobantes_relay_views import (
    ComprobantesAnularPedidoRelayAPIView,
    ComprobanteAMailRelayAPIView,
    ComprobanteAMailEnqueueRelayAPIView,
    ComprobanteAMailQueueStatusRelayAPIView,
    ComprobantesNoCanceladosRelayAPIView,
    ComprobantesNoCanceladosResumenRelayAPIView,
    ComprobantesPedidosRelayAPIView,
    ComprobantesPresupuestosRelayAPIView,
    ComprobantesRemitosRelayAPIView,
    ComprobantesSugerenciasNroRelayAPIView,
)
from ecom.ctacte_relay_views import (
    ConsumosResumenRelayAPIView,
    CuentaCorrientePedidosRelayAPIView,
    CuentaCorrientePedidosSugerenciasNroRelayAPIView,
    CtacteMovimientosRelayAPIView,
    CtacteSugerenciasNroRelayAPIView,
)
from ecom.recibos_relay_views import RecibosListadoRelayAPIView
from ecom.nota_credito_relay_views import (
    NotaCreditoListadoRelayAPIView,
    NotaCreditoSugerenciasNroRelayAPIView,
)
from ecom.factura_electronica_relay_views import (
    FacturaElectronicaListadoRelayAPIView,
    FacturaElectronicaSugerenciasNroRelayAPIView,
)
from ecom.facturas_imputar_relay_views import (
    FacturasImputarAccionRelayAPIView,
    FacturasImputarListadoRelayAPIView,
    FacturasImputarSugerenciasNroRelayAPIView,
)
from ecom.filtros_estadisticas_relay_views import FiltrosEstadisticasRelayAPIView
from ecom.devoluciones_relay_views import (
    DevolucionesRelayAPIView,
    DevolucionesSugerenciasNroRelayAPIView,
)
from ecom.catalogo_relay_views import (
    CatalogoArticulosAutocompleteAPIView,
    CatalogoFiltroRubroCatalogoAPIView,
    CatalogoLaboratoriosRelayAPIView,
    CatalogoLotesRelayAPIView,
    CatalogoMarcasRelayAPIView,
    CatalogoMasVendidosRelayAPIView,
    CatalogoProveedoresRelayAPIView,
    CatalogoRubrosRelayAPIView,
    CatalogoSubrubrosRelayAPIView,
    CatalogoSubrubrosTipoClienteRelayAPIView,
    CatalogoTaccRelayAPIView,
)
from ecom.catalogo_producto_relay_views import (
    CatalogoArticulosListadoRelayAPIView,
    CatalogoArticuloDetalleRelayAPIView,
)
from ecom.carrito_relay_views import (
    CarritoDescuentoPieRelayAPIView,
    CarritoItemRelayAPIView,
    CarritoListaPrecioRelayAPIView,
    CarritoRelayAPIView,
    CarritoTipoComprobanteRelayAPIView,
    CarritoVaciarRelayAPIView,
)
from ecom.checkout_relay_views import CheckoutConfirmarRelayAPIView
from ecom.vendedor_operativo_views import (
    VendedorOperativoRelayAPIView,
    VendedoresCarteraRelayAPIView,
)
from ecom.lista_precio_pdf_relay_views import ExportarListaPreciosPDFRelayAPIView
from ecom.api.v1.comprobantes.pedidos import (
    PedidosDetalleV1APIView,
    PedidosListV1APIView,
    PedidosSugerenciasNumeroV1APIView,
)
from ecom.recibo_alta_relay_views import ReciboAltaRelayAPIView
from ecom.recibo_alta_catalogos_views import ReciboAltaCatalogosRelayAPIView
from ecom.articulo_remito_relay_views import ArticuloRemitoListadoRelayAPIView
from ecom.mayoristapp_listado_urls import mayoristapp_listado_urlpatterns

app_name = "ecom"

urlpatterns = [
    path("manual/", views.manual_usuario_view, name="manual_usuario"),
    path(
        "mayoristapp/",
        HubMayoristappView.as_view(),
        name="mayoristapp_hub",
    ),
    path(
        "mayoristapp/presupuestos-vendedor/",
        PresupuestosVendedorView.as_view(),
        name="mayoristapp_presupuestos_vendedor",
    ),
    path(
        "mayoristapp/pedidos-vendedor/",
        PedidosVendedorView.as_view(),
        name="mayoristapp_pedidos_vendedor",
    ),
    path(
        "mayoristapp/pedidos/",
        PedidosHubView.as_view(),
        name="mayoristapp_pedidos_hub",
    ),
    path(
        "mayoristapp/pedidos/lote/<int:draft_id>/",
        LoteResumenView.as_view(),
        name="mayoristapp_lote_resumen",
    ),
    path(
        "api/mayoristapp/pedidos/lote/<int:draft_id>/",
        LoteResumenAPIView.as_view(),
        name="api_lote_resumen",
    ),
    path(
        "api/mayoristapp/pedidos/hub/",
        PedidosHubAPIView.as_view(),
        name="mayoristapp_pedidos_hub_api",
    ),
    path(
        "api/mayoristapp/pedidos/hub/archivar-draft/",
        PedidosHubArchivarDraftAPIView.as_view(),
        name="mayoristapp_pedidos_hub_archivar_draft",
    ),
    path(
        "api/mayoristapp/pedidos/hub/eliminar-draft/",
        PedidosHubEliminarDraftAPIView.as_view(),
        name="mayoristapp_pedidos_hub_eliminar_draft",
    ),
    path(
        "api/mayoristapp/pedidos/hub/migrar-carrito/",
        PedidosHubMigrarCarritoAPIView.as_view(),
        name="mayoristapp_pedidos_hub_migrar_carrito",
    ),
    path(
        "api/mayoristapp/pedidos/hub/archivar-carrito/",
        PedidosHubArchivarCarritoAPIView.as_view(),
        name="mayoristapp_pedidos_hub_archivar_carrito",
    ),
    path(
        "mayoristapp/pedido-masivo-sucursales/",
        PedidoMasivoSucursalesView.as_view(),
        name="mayoristapp_pedido_masivo_sucursales",
    ),
    path(
        "api/mayoristapp/pedido-masivo/clientes/",
        PedidoMasivoClientesAPIView.as_view(),
        name="api_pedido_masivo_clientes",
    ),
    path(
        "api/mayoristapp/pedido-masivo/sucursales/",
        PedidoMasivoSucursalesAPIView.as_view(),
        name="api_pedido_masivo_sucursales",
    ),
    path(
        "api/mayoristapp/pedido-masivo/abrir/",
        PedidoMasivoAbrirAPIView.as_view(),
        name="api_pedido_masivo_abrir",
    ),
    path(
        "api/mayoristapp/pedido-masivo/abrir-pedido/",
        PedidoMasivoAbrirPedidoAPIView.as_view(),
        name="api_pedido_masivo_abrir_pedido",
    ),
    path(
        "api/mayoristapp/pedido-masivo/matriz/",
        PedidoMasivoMatrizAPIView.as_view(),
        name="api_pedido_masivo_matriz",
    ),
    path(
        "api/mayoristapp/pedido-masivo/celda/",
        PedidoMasivoCeldaAPIView.as_view(),
        name="api_pedido_masivo_celda",
    ),
    path(
        "api/mayoristapp/pedido-masivo/eliminar-fila/",
        PedidoMasivoEliminarFilaAPIView.as_view(),
        name="api_pedido_masivo_eliminar_fila",
    ),
    path(
        "api/mayoristapp/pedido-masivo/articulos/",
        PedidoMasivoArticulosAPIView.as_view(),
        name="api_pedido_masivo_articulos",
    ),
    path(
        "api/mayoristapp/pedido-masivo/preview/",
        PedidoMasivoPreviewAPIView.as_view(),
        name="api_pedido_masivo_preview",
    ),
    path(
        "api/mayoristapp/pedido-masivo/descuento-fila/",
        PedidoMasivoDescuentoFilaAPIView.as_view(),
        name="api_pedido_masivo_descuento_fila",
    ),
    path(
        "api/mayoristapp/pedido-masivo/descuento-pie/",
        PedidoMasivoDescuentoPieAPIView.as_view(),
        name="api_pedido_masivo_descuento_pie",
    ),
    path(
        "api/mayoristapp/pedido-masivo/confirmar/",
        PedidoMasivoConfirmarAPIView.as_view(),
        name="api_pedido_masivo_confirmar",
    ),
    path(
        "api/mayoristapp/pedido-masivo/anular/",
        PedidoMasivoAnularAPIView.as_view(),
        name="api_pedido_masivo_anular",
    ),
    path(
        "mayoristapp/config/vendedor-cliente-marca/",
        ConfigVendedorClienteMarcaView.as_view(),
        name="mayoristapp_config_vendedor_cliente_marca",
    ),
    path(
        "mayoristapp/ajustes-ventas/",
        AjustesVentasView.as_view(),
        name="mayoristapp_ajustes_ventas",
    ),
    path(
        "api/mayoristapp/ajustes-ventas/",
        AjustesVentasAPIView.as_view(),
        name="api_ajustes_ventas",
    ),
    path(
        "api/mayoristapp/ajustes/workflow/",
        AjustesWorkflowAPIView.as_view(),
        name="api_ajustes_workflow",
    ),
    path(
        "api/mayoristapp/jerarquia/nodos/",
        JerarquiaNodosAPIView.as_view(),
        name="api_jerarquia_nodos",
    ),
    path(
        "api/mayoristapp/jerarquia/usuarios/",
        JerarquiaUsuariosAPIView.as_view(),
        name="api_jerarquia_usuarios",
    ),
    path(
        "api/mayoristapp/aprobacion/pendientes/",
        AprobacionPendientesAPIView.as_view(),
        name="api_aprobacion_pendientes",
    ),
    path(
        "api/mayoristapp/aprobacion/<int:cod_mov>/aprobar/",
        AprobacionPedidoAprobarAPIView.as_view(),
        name="api_aprobacion_pedido_aprobar",
    ),
    path(
        "api/mayoristapp/aprobacion/<int:cod_mov>/rechazar/",
        AprobacionPedidoRechazarAPIView.as_view(),
        name="api_aprobacion_pedido_rechazar",
    ),
    path(
        "api/mayoristapp/aprobacion/lote/<int:draft_id>/aprobar/",
        AprobacionLoteAprobarAPIView.as_view(),
        name="api_aprobacion_lote_aprobar",
    ),
    path(
        "api/mayoristapp/aprobacion/lote/<int:draft_id>/rechazar/",
        AprobacionLoteRechazarAPIView.as_view(),
        name="api_aprobacion_lote_rechazar",
    ),
    path(
        "api/mayoristapp/vendedor-cliente-marca/ternas/",
        VendedorClienteMarcaTernasAPIView.as_view(),
        name="api_vendedor_cliente_marca_ternas",
    ),
    path(
        "api/mayoristapp/vendedor-cliente-marca/crear/",
        VendedorClienteMarcaCrearAPIView.as_view(),
        name="api_vendedor_cliente_marca_crear",
    ),
    path(
        "api/mayoristapp/vendedor-cliente-marca/anular/",
        VendedorClienteMarcaAnularAPIView.as_view(),
        name="api_vendedor_cliente_marca_anular",
    ),
    path(
        "api/mayoristapp/vendedor-cliente-marca/vendedores/",
        VendedorClienteMarcaVendedoresAPIView.as_view(),
        name="api_vendedor_cliente_marca_vendedores",
    ),
    path(
        "api/mayoristapp/vendedor-cliente-marca/clientes/",
        VendedorClienteMarcaClientesAPIView.as_view(),
        name="api_vendedor_cliente_marca_clientes",
    ),
    path(
        "api/mayoristapp/vendedor-cliente-marca/sucursales/",
        VendedorClienteMarcaSucursalesAPIView.as_view(),
        name="api_vendedor_cliente_marca_sucursales",
    ),
    path(
        "api/mayoristapp/vendedor-cliente-marca/marcas/",
        VendedorClienteMarcaMarcasAPIView.as_view(),
        name="api_vendedor_cliente_marca_marcas",
    ),
    path(
        "mayoristapp/pedidos/<int:cod_mov>/",
        PedidoDetalleView.as_view(),
        name="mayoristapp_pedido_detalle",
    ),
    path(
        "mayoristapp/comprobantes/<int:cod_mov>/",
        ComprobanteComercialDetalleView.as_view(),
        name="mayoristapp_comprobante_detalle",
    ),
    path(
        "mayoristapp/recibos/alta/",
        AltaReciboMayoristappView.as_view(),
        name="mayoristapp_alta_recibo",
    ),
    path(
        "mayoristapp/venta/",
        CompraMayoristaView.as_view(),
        name="mayoristapp_venta",
    ),
    # Alias deprecado: bookmarks /compra/ → pedido simple masivo (mismo destino que /venta/)
    path(
        "mayoristapp/compra/",
        CompraMayoristaView.as_view(),
        name="mayoristapp_compra",
    ),
    # Logística operativa vive en la app ``logistica`` (/logistica/…). Redirecciones 301 por bookmarks.
    path(
        "logistica/entregas/",
        RedirectView.as_view(
            pattern_name="logistica:entregas", permanent=True, query_string=True
        ),
        name="logistica_entregas",
    ),
    path(
        "api/logistica/entregas/lista/",
        RedirectView.as_view(
            pattern_name="logistica:api_entregas_lista", permanent=True, query_string=True
        ),
        name="logistica_entregas_api_lista",
    ),
    path(
        "api/logistica/entregas/catalogos/",
        RedirectView.as_view(
            pattern_name="logistica:api_entregas_catalogos", permanent=True, query_string=True
        ),
        name="logistica_entregas_api_catalogos",
    ),
    path(
        "api/logistica/entregas/remito/<int:cod_mov>/",
        redirect_api_remito_legacy,
        name="logistica_entregas_api_remito",
    ),
    path(
        "api/logistica/entregas/entrega/",
        RedirectView.as_view(
            pattern_name="logistica:api_entregas_entrega", permanent=True, query_string=True
        ),
        name="logistica_entregas_api_entrega",
    ),
    path(
        "api/logistica/entregas/motivos-no-entrega/",
        RedirectView.as_view(
            pattern_name="logistica:api_entregas_motivos", permanent=True, query_string=True
        ),
        name="logistica_entregas_api_motivos",
    ),
    path(
        "api/logistica/entregas/clientes/autocomplete/",
        RedirectView.as_view(
            pattern_name="logistica:api_entregas_clientes_autocomplete",
            permanent=True,
            query_string=True,
        ),
        name="logistica_entregas_api_clientes_autocomplete",
    ),
    path(
        "mayoristapp/logistica/estado-pedidos/",
        EstadoPedidosPreparacionView.as_view(),
        name="mayoristapp_estado_pedidos_preparacion",
    ),
    path(
        "api/mayoristapp/logistica/estado-pedidos/",
        EstadoPedidosKanbanAPIView.as_view(),
        name="mayoristapp_logistica_estado_pedidos",
    ),
    path("api/health/", views.health, name="health"),
    path("api/migration-info/", views.migration_info, name="migration_info"),
    # --- API REST v1 (contrato canónico Synap) ---
    path(
        "api/v1/mayoristapp/comprobantes/pedidos/",
        PedidosListV1APIView.as_view(),
        name="v1_comprobantes_pedidos",
    ),
    path(
        "api/v1/mayoristapp/comprobantes/pedidos/sugerencias-numero/",
        PedidosSugerenciasNumeroV1APIView.as_view(),
        name="v1_comprobantes_pedidos_sugerencias",
    ),
    path(
        "api/v1/mayoristapp/comprobantes/pedidos/<int:cod_mov>/",
        PedidoCabeceraV1APIView.as_view(),
        name="v1_comprobantes_pedidos_cabecera",
    ),
    path(
        "api/v1/mayoristapp/comprobantes/pedidos/<int:cod_mov>/detalle/",
        PedidosDetalleV1APIView.as_view(),
        name="v1_comprobantes_pedidos_detalle",
    ),
    path(
        "api/mayoristapp/articulo-remito/listado/",
        ArticuloRemitoListadoRelayAPIView.as_view(),
        name="mayoristapp_articulo_remito_listado",
    ),
    path(
        "api/mayoristapp/relay-inventory/",
        views.mayoristapp_relay_inventory,
        name="mayoristapp_relay_inventory",
    ),
    path(
        "api/mayoristapp/catalogo/rubros/",
        CatalogoRubrosRelayAPIView.as_view(),
        name="mayoristapp_catalogo_rubros",
    ),
    path(
        "api/mayoristapp/catalogo/subrubros/",
        CatalogoSubrubrosRelayAPIView.as_view(),
        name="mayoristapp_catalogo_subrubros",
    ),
    path(
        "api/mayoristapp/catalogo/filtro-rubro-catalogo/",
        CatalogoFiltroRubroCatalogoAPIView.as_view(),
        name="mayoristapp_catalogo_filtro_rubro",
    ),
    path(
        "api/mayoristapp/catalogo/articulos/autocomplete/",
        CatalogoArticulosAutocompleteAPIView.as_view(),
        name="mayoristapp_catalogo_articulos_autocomplete",
    ),
    path(
        "api/mayoristapp/catalogo/subrubros-tipo-cliente/",
        CatalogoSubrubrosTipoClienteRelayAPIView.as_view(),
        name="mayoristapp_catalogo_subrubros_tipo_cliente",
    ),
    path(
        "api/mayoristapp/catalogo/marcas/",
        CatalogoMarcasRelayAPIView.as_view(),
        name="mayoristapp_catalogo_marcas",
    ),
    path(
        "api/mayoristapp/catalogo/laboratorios/",
        CatalogoLaboratoriosRelayAPIView.as_view(),
        name="mayoristapp_catalogo_laboratorios",
    ),
    path(
        "api/mayoristapp/catalogo/proveedores/",
        CatalogoProveedoresRelayAPIView.as_view(),
        name="mayoristapp_catalogo_proveedores",
    ),
    path(
        "api/mayoristapp/catalogo/lotes/",
        CatalogoLotesRelayAPIView.as_view(),
        name="mayoristapp_catalogo_lotes",
    ),
    path(
        "api/mayoristapp/catalogo/tacc-opciones/",
        CatalogoTaccRelayAPIView.as_view(),
        name="mayoristapp_catalogo_tacc_opciones",
    ),
    path(
        "api/mayoristapp/catalogo/mas-vendidos/",
        CatalogoMasVendidosRelayAPIView.as_view(),
        name="mayoristapp_catalogo_mas_vendidos",
    ),
    path(
        "api/mayoristapp/catalogo/articulos/listado/",
        CatalogoArticulosListadoRelayAPIView.as_view(),
        name="mayoristapp_catalogo_articulos_listado",
    ),
    path(
        "api/mayoristapp/catalogo/articulos/<int:idart>/detalle/",
        CatalogoArticuloDetalleRelayAPIView.as_view(),
        name="mayoristapp_catalogo_articulo_detalle",
    ),
    path(
        "api/mayoristapp/precios/lista-precio/",
        ListaPrecioRelayAPIView.as_view(),
        name="mayoristapp_precios_lista_precio",
    ),
    path(
        "api/mayoristapp/precios/condiciones-venta/",
        CondicionesVentaRelayAPIView.as_view(),
        name="mayoristapp_precios_condiciones_venta",
    ),
    path(
        "api/mayoristapp/precios/promociones/",
        PromocionesRelayAPIView.as_view(),
        name="mayoristapp_precios_promociones",
    ),
    path(
        "api/mayoristapp/clientes/buscar/",
        ClienteBuscarRelayAPIView.as_view(),
        name="mayoristapp_clientes_buscar",
    ),
    path(
        "api/mayoristapp/clientes/seleccionado/",
        ClienteSeleccionadoRelayAPIView.as_view(),
        name="mayoristapp_clientes_seleccionado",
    ),
    path(
        "api/mayoristapp/clientes/comprobante-formulario/",
        ClienteComprobanteFormularioRelayAPIView.as_view(),
        name="mayoristapp_clientes_comprobante_formulario",
    ),
    path(
        "api/mayoristapp/clientes/seleccionar/",
        ClienteSeleccionarRelayAPIView.as_view(),
        name="mayoristapp_clientes_seleccionar",
    ),
    path(
        "api/mayoristapp/clientes/domicilio/",
        ClienteDomicilioRelayAPIView.as_view(),
        name="mayoristapp_clientes_domicilio",
    ),
    path(
        "api/mayoristapp/clientes/domicilio-opciones-visita/",
        ClienteDomicilioOpcionesVisitaRelayAPIView.as_view(),
        name="mayoristapp_clientes_domicilio_opciones_visita",
    ),
    path(
        "api/mayoristapp/clientes/contacto/",
        ClienteContactoRelayAPIView.as_view(),
        name="mayoristapp_clientes_contacto",
    ),
    path(
        "api/mayoristapp/clientes/rapido/",
        ClienteRapidoRelayAPIView.as_view(),
        name="mayoristapp_clientes_rapido",
    ),
    path(
        "api/mayoristapp/comprobantes/pedidos/",
        ComprobantesPedidosRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_pedidos",
    ),
    path(
        "api/mayoristapp/comprobantes/presupuestos/",
        ComprobantesPresupuestosRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_presupuestos",
    ),
    path(
        "api/mayoristapp/comprobantes/remitos/",
        ComprobantesRemitosRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_remitos",
    ),
    path(
        "api/mayoristapp/comprobantes/sugerencias-nro/",
        ComprobantesSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_sugerencias_nro",
    ),
    path(
        "api/mayoristapp/comprobantes/comprobante-a-mail/",
        ComprobanteAMailRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_comprobante_a_mail",
    ),
    path(
        "api/mayoristapp/comprobantes/comprobante-a-mail/enqueue/",
        ComprobanteAMailEnqueueRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_comprobante_a_mail_enqueue",
    ),
    path(
        "api/mayoristapp/comprobantes/comprobante-a-mail/queue-status/",
        ComprobanteAMailQueueStatusRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_comprobante_a_mail_queue_status",
    ),
    path(
        "api/mayoristapp/comprobantes/no-cancelados/",
        ComprobantesNoCanceladosRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_no_cancelados",
    ),
    path(
        "api/mayoristapp/comprobantes/no-cancelados-resumen/",
        ComprobantesNoCanceladosResumenRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_no_cancelados_resumen",
    ),
    path(
        "api/mayoristapp/comprobantes/anular-pedido/",
        ComprobantesAnularPedidoRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_anular_pedido",
    ),
    path(
        "api/mayoristapp/ctacte/consumos-resumen/",
        ConsumosResumenRelayAPIView.as_view(),
        name="mayoristapp_ctacte_consumos_resumen",
    ),
    path(
        "api/mayoristapp/ctacte/movimientos/",
        CtacteMovimientosRelayAPIView.as_view(),
        name="mayoristapp_ctacte_movimientos",
    ),
    path(
        "api/mayoristapp/ctacte/sugerencias-nro/",
        CtacteSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_ctacte_sugerencias_nro",
    ),
    path(
        "api/mayoristapp/ctacte/pedidos/sugerencias-nro/",
        CuentaCorrientePedidosSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_ctacte_pedidos_sugerencias_nro",
    ),
    path(
        "api/mayoristapp/ctacte/pedidos/",
        CuentaCorrientePedidosRelayAPIView.as_view(),
        name="mayoristapp_ctacte_pedidos",
    ),
    path(
        "api/mayoristapp/recibos/listado/",
        RecibosListadoRelayAPIView.as_view(),
        name="mayoristapp_recibos_listado",
    ),
    path(
        "api/mayoristapp/fe/nota-credito/listado/",
        NotaCreditoListadoRelayAPIView.as_view(),
        name="mayoristapp_fe_nota_credito_listado",
    ),
    path(
        "api/mayoristapp/fe/nota-credito/sugerencias-nro/",
        NotaCreditoSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_fe_nota_credito_sugerencias_nro",
    ),
    path(
        "api/mayoristapp/fe/factura-electronica/listado/",
        FacturaElectronicaListadoRelayAPIView.as_view(),
        name="mayoristapp_fe_factura_electronica_listado",
    ),
    path(
        "api/mayoristapp/fe/factura-electronica/sugerencias-nro/",
        FacturaElectronicaSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_fe_factura_electronica_sugerencias_nro",
    ),
    path(
        "api/mayoristapp/fe/facturas-imputar/listado/",
        FacturasImputarListadoRelayAPIView.as_view(),
        name="mayoristapp_fe_facturas_imputar_listado",
    ),
    path(
        "api/mayoristapp/fe/facturas-imputar/sugerencias-nro/",
        FacturasImputarSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_fe_facturas_imputar_sugerencias_nro",
    ),
    path(
        "api/mayoristapp/fe/facturas-imputar/accion/",
        FacturasImputarAccionRelayAPIView.as_view(),
        name="mayoristapp_fe_facturas_imputar_accion",
    ),
    path(
        "api/mayoristapp/recibos/alta/accion/",
        ReciboAltaRelayAPIView.as_view(),
        name="mayoristapp_recibos_alta_accion",
    ),
    path(
        "api/mayoristapp/recibos/alta/catalogos/",
        ReciboAltaCatalogosRelayAPIView.as_view(),
        name="mayoristapp_recibos_alta_catalogos",
    ),
    path(
        "api/mayoristapp/estadisticas/filtros/",
        FiltrosEstadisticasRelayAPIView.as_view(),
        name="mayoristapp_estadisticas_filtros",
    ),
    path(
        "api/mayoristapp/estadisticas/devoluciones/",
        DevolucionesRelayAPIView.as_view(),
        name="mayoristapp_estadisticas_devoluciones",
    ),
    path(
        "api/mayoristapp/estadisticas/devoluciones/sugerencias-nro/",
        DevolucionesSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_estadisticas_devoluciones_sugerencias_nro",
    ),
    # --- Carrito mayorista (Fase P1) ---
    path(
        "api/mayoristapp/carrito/",
        CarritoRelayAPIView.as_view(),
        name="mayoristapp_carrito",
    ),
    path(
        "api/mayoristapp/carrito/items/<int:item_id>/",
        CarritoItemRelayAPIView.as_view(),
        name="mayoristapp_carrito_item",
    ),
    path(
        "api/mayoristapp/carrito/vaciar/",
        CarritoVaciarRelayAPIView.as_view(),
        name="mayoristapp_carrito_vaciar",
    ),
    path(
        "api/mayoristapp/carrito/tipo-comprobante/",
        CarritoTipoComprobanteRelayAPIView.as_view(),
        name="mayoristapp_carrito_tipo_comprobante",
    ),
    path(
        "api/mayoristapp/carrito/lista-precio/",
        CarritoListaPrecioRelayAPIView.as_view(),
        name="mayoristapp_carrito_lista_precio",
    ),
    path(
        "api/mayoristapp/carrito/descuento-pie/",
        CarritoDescuentoPieRelayAPIView.as_view(),
        name="mayoristapp_carrito_descuento_pie",
    ),
    path(
        "api/mayoristapp/carrito/desde-pedido/<int:cod_mov>/preview/",
        CarritoDesdePedidoPreviewAPIView.as_view(),
        name="mayoristapp_carrito_desde_pedido_preview",
    ),
    path(
        "api/mayoristapp/carrito/desde-pedido/",
        CarritoDesdePedidoAPIView.as_view(),
        name="mayoristapp_carrito_desde_pedido",
    ),
    path(
        "api/mayoristapp/comprobantes/<int:cod_mov>/cabecera/",
        ComprobanteComercialCabeceraAPIView.as_view(),
        name="mayoristapp_comprobante_cabecera",
    ),
    path(
        "api/mayoristapp/comprobantes/<int:cod_mov>/detalle/",
        ComprobanteComercialDetalleAPIView.as_view(),
        name="mayoristapp_comprobante_detalle_api",
    ),
    path(
        "api/mayoristapp/pedidos/recientes/",
        PedidosRecientesAPIView.as_view(),
        name="mayoristapp_pedidos_recientes",
    ),
    path(
        "api/mayoristapp/pedidos/kpis/",
        PedidosKpisAPIView.as_view(),
        name="mayoristapp_pedidos_kpis",
    ),
    path(
        "api/mayoristapp/comprobantes/pedidos/<int:cod_mov>/pdf/",
        PedidoComprobantePDFAPIView.as_view(),
        name="mayoristapp_pedido_pdf",
    ),
    path(
        "api/mayoristapp/venta/contexto/",
        CompraMayoristaContextoAPIView.as_view(),
        name="mayoristapp_venta_contexto",
    ),
    # Alias deprecado de contexto (misma vista)
    path(
        "api/mayoristapp/compra/contexto/",
        CompraMayoristaContextoAPIView.as_view(),
        name="mayoristapp_compra_contexto",
    ),
    path(
        "api/mayoristapp/presupuestos/<int:cod_mov>/convertir-pedido/",
        PresupuestoConvertirPedidoAPIView.as_view(),
        name="mayoristapp_presupuesto_convertir_pedido",
    ),
    path(
        "api/mayoristapp/vendedores-cartera/",
        VendedoresCarteraRelayAPIView.as_view(),
        name="mayoristapp_vendedores_cartera",
    ),
    path(
        "api/mayoristapp/vendedor-operativo/",
        VendedorOperativoRelayAPIView.as_view(),
        name="mayoristapp_vendedor_operativo",
    ),
    # --- Checkout mayorista (Fase P2) ---
    path(
        "api/mayoristapp/checkout/confirmar/",
        CheckoutConfirmarRelayAPIView.as_view(),
        name="mayoristapp_checkout_confirmar",
    ),
    # --- Export lista de precios PDF (Fase P3) ---
    path(
        "api/mayoristapp/catalogo/lista-precios.pdf",
        ExportarListaPreciosPDFRelayAPIView.as_view(),
        name="mayoristapp_lista_precios_pdf",
    ),
] + mayoristapp_listado_urlpatterns()
