from django.urls import path
from django.views.generic import RedirectView

from ecom import views
from ecom.logistica_legacy_redirects import redirect_api_remito_legacy
from ecom.mayoristapp_web_views import (
    AltaReciboMayoristappView,
    CompraMayoristaView,
    HubMayoristappView,
    PedidosVendedorView,
    PresupuestosVendedorView,
)
from ecom.logistica_estado_pedidos_views import (
    EstadoPedidosKanbanAPIView,
    EstadoPedidosPreparacionView,
)
from ecom.cliente_relay_views import (
    ClienteBuscarRelayAPIView,
    ClienteComprobanteFormularioRelayAPIView,
    ClienteContactoRelayAPIView,
    ClienteDomicilioOpcionesVisitaRelayAPIView,
    ClienteDomicilioRelayAPIView,
    ClienteRapidoRelayAPIView,
    ClienteSeleccionadoRelayAPIView,
    ClienteSeleccionarRelayAPIView,
)
from ecom.precio_relay_views import ListaPrecioRelayAPIView, PromocionesRelayAPIView
from ecom.comprobantes_relay_views import (
    ComprobantesAnularPedidoRelayAPIView,
    ComprobanteAMailRelayAPIView,
    ComprobanteAMailEnqueueRelayAPIView,
    ComprobanteAMailQueueStatusRelayAPIView,
    ComprobantesNoCanceladosRelayAPIView,
    ComprobantesNoCanceladosResumenRelayAPIView,
    ComprobantesPedidosRelayAPIView,
    ComprobantesPresupuestosRelayAPIView,
    ComprobantesRemitosRelayAPIView,
    ComprobantesSugerenciasNroRelayAPIView,
)
from ecom.ctacte_relay_views import (
    ConsumosResumenRelayAPIView,
    CuentaCorrientePedidosRelayAPIView,
    CuentaCorrientePedidosSugerenciasNroRelayAPIView,
    CtacteMovimientosRelayAPIView,
    CtacteSugerenciasNroRelayAPIView,
)
from ecom.recibos_relay_views import RecibosListadoRelayAPIView
from ecom.nota_credito_relay_views import (
    NotaCreditoListadoRelayAPIView,
    NotaCreditoSugerenciasNroRelayAPIView,
)
from ecom.factura_electronica_relay_views import (
    FacturaElectronicaListadoRelayAPIView,
    FacturaElectronicaSugerenciasNroRelayAPIView,
)
from ecom.facturas_imputar_relay_views import (
    FacturasImputarAccionRelayAPIView,
    FacturasImputarListadoRelayAPIView,
    FacturasImputarSugerenciasNroRelayAPIView,
)
from ecom.filtros_estadisticas_relay_views import FiltrosEstadisticasRelayAPIView
from ecom.devoluciones_relay_views import (
    DevolucionesRelayAPIView,
    DevolucionesSugerenciasNroRelayAPIView,
)
from ecom.catalogo_relay_views import (
    CatalogoArticulosAutocompleteAPIView,
    CatalogoFiltroRubroCatalogoAPIView,
    CatalogoLaboratoriosRelayAPIView,
    CatalogoLotesRelayAPIView,
    CatalogoMarcasRelayAPIView,
    CatalogoMasVendidosRelayAPIView,
    CatalogoProveedoresRelayAPIView,
    CatalogoRubrosRelayAPIView,
    CatalogoSubrubrosRelayAPIView,
    CatalogoSubrubrosTipoClienteRelayAPIView,
    CatalogoTaccRelayAPIView,
)
from ecom.catalogo_producto_relay_views import (
    CatalogoArticulosListadoRelayAPIView,
    CatalogoArticuloDetalleRelayAPIView,
)
from ecom.carrito_relay_views import (
    CarritoDescuentoPieRelayAPIView,
    CarritoItemRelayAPIView,
    CarritoRelayAPIView,
    CarritoVaciarRelayAPIView,
)
from ecom.checkout_relay_views import CheckoutConfirmarRelayAPIView
from ecom.lista_precio_pdf_relay_views import ExportarListaPreciosPDFRelayAPIView
from ecom.api.v1.comprobantes.pedidos import (
    PedidosDetalleV1APIView,
    PedidosListV1APIView,
    PedidosSugerenciasNumeroV1APIView,
)
from ecom.recibo_alta_relay_views import ReciboAltaRelayAPIView
from ecom.recibo_alta_catalogos_views import ReciboAltaCatalogosRelayAPIView
from ecom.articulo_remito_relay_views import ArticuloRemitoListadoRelayAPIView
from ecom.mayoristapp_listado_urls import mayoristapp_listado_urlpatterns

app_name = "ecom"

urlpatterns = [
    path(
        "mayoristapp/",
        HubMayoristappView.as_view(),
        name="mayoristapp_hub",
    ),
    path(
        "mayoristapp/presupuestos-vendedor/",
        PresupuestosVendedorView.as_view(),
        name="mayoristapp_presupuestos_vendedor",
    ),
    path(
        "mayoristapp/pedidos-vendedor/",
        PedidosVendedorView.as_view(),
        name="mayoristapp_pedidos_vendedor",
    ),
    path(
        "mayoristapp/recibos/alta/",
        AltaReciboMayoristappView.as_view(),
        name="mayoristapp_alta_recibo",
    ),
    path(
        "mayoristapp/compra/",
        CompraMayoristaView.as_view(),
        name="mayoristapp_compra",
    ),
    # Logística operativa vive en la app ``logistica`` (/logistica/…). Redirecciones 301 por bookmarks.
    path(
        "logistica/entregas/",
        RedirectView.as_view(
            pattern_name="logistica:entregas", permanent=True, query_string=True
        ),
        name="logistica_entregas",
    ),
    path(
        "api/logistica/entregas/lista/",
        RedirectView.as_view(
            pattern_name="logistica:api_entregas_lista", permanent=True, query_string=True
        ),
        name="logistica_entregas_api_lista",
    ),
    path(
        "api/logistica/entregas/catalogos/",
        RedirectView.as_view(
            pattern_name="logistica:api_entregas_catalogos", permanent=True, query_string=True
        ),
        name="logistica_entregas_api_catalogos",
    ),
    path(
        "api/logistica/entregas/remito/<int:cod_mov>/",
        redirect_api_remito_legacy,
        name="logistica_entregas_api_remito",
    ),
    path(
        "api/logistica/entregas/entrega/",
        RedirectView.as_view(
            pattern_name="logistica:api_entregas_entrega", permanent=True, query_string=True
        ),
        name="logistica_entregas_api_entrega",
    ),
    path(
        "api/logistica/entregas/motivos-no-entrega/",
        RedirectView.as_view(
            pattern_name="logistica:api_entregas_motivos", permanent=True, query_string=True
        ),
        name="logistica_entregas_api_motivos",
    ),
    path(
        "api/logistica/entregas/clientes/autocomplete/",
        RedirectView.as_view(
            pattern_name="logistica:api_entregas_clientes_autocomplete",
            permanent=True,
            query_string=True,
        ),
        name="logistica_entregas_api_clientes_autocomplete",
    ),
    path(
        "mayoristapp/logistica/estado-pedidos/",
        EstadoPedidosPreparacionView.as_view(),
        name="mayoristapp_estado_pedidos_preparacion",
    ),
    path(
        "api/mayoristapp/logistica/estado-pedidos/",
        EstadoPedidosKanbanAPIView.as_view(),
        name="mayoristapp_logistica_estado_pedidos",
    ),
    path("api/health/", views.health, name="health"),
    path("api/migration-info/", views.migration_info, name="migration_info"),
    # --- API REST v1 (contrato canónico Synap) ---
    path(
        "api/v1/mayoristapp/comprobantes/pedidos/",
        PedidosListV1APIView.as_view(),
        name="v1_comprobantes_pedidos",
    ),
    path(
        "api/v1/mayoristapp/comprobantes/pedidos/sugerencias-numero/",
        PedidosSugerenciasNumeroV1APIView.as_view(),
        name="v1_comprobantes_pedidos_sugerencias",
    ),
    path(
        "api/v1/mayoristapp/comprobantes/pedidos/<int:cod_mov>/detalle/",
        PedidosDetalleV1APIView.as_view(),
        name="v1_comprobantes_pedidos_detalle",
    ),
    path(
        "api/mayoristapp/articulo-remito/listado/",
        ArticuloRemitoListadoRelayAPIView.as_view(),
        name="mayoristapp_articulo_remito_listado",
    ),
    path(
        "api/mayoristapp/relay-inventory/",
        views.mayoristapp_relay_inventory,
        name="mayoristapp_relay_inventory",
    ),
    path(
        "api/mayoristapp/catalogo/rubros/",
        CatalogoRubrosRelayAPIView.as_view(),
        name="mayoristapp_catalogo_rubros",
    ),
    path(
        "api/mayoristapp/catalogo/subrubros/",
        CatalogoSubrubrosRelayAPIView.as_view(),
        name="mayoristapp_catalogo_subrubros",
    ),
    path(
        "api/mayoristapp/catalogo/filtro-rubro-catalogo/",
        CatalogoFiltroRubroCatalogoAPIView.as_view(),
        name="mayoristapp_catalogo_filtro_rubro",
    ),
    path(
        "api/mayoristapp/catalogo/articulos/autocomplete/",
        CatalogoArticulosAutocompleteAPIView.as_view(),
        name="mayoristapp_catalogo_articulos_autocomplete",
    ),
    path(
        "api/mayoristapp/catalogo/subrubros-tipo-cliente/",
        CatalogoSubrubrosTipoClienteRelayAPIView.as_view(),
        name="mayoristapp_catalogo_subrubros_tipo_cliente",
    ),
    path(
        "api/mayoristapp/catalogo/marcas/",
        CatalogoMarcasRelayAPIView.as_view(),
        name="mayoristapp_catalogo_marcas",
    ),
    path(
        "api/mayoristapp/catalogo/laboratorios/",
        CatalogoLaboratoriosRelayAPIView.as_view(),
        name="mayoristapp_catalogo_laboratorios",
    ),
    path(
        "api/mayoristapp/catalogo/proveedores/",
        CatalogoProveedoresRelayAPIView.as_view(),
        name="mayoristapp_catalogo_proveedores",
    ),
    path(
        "api/mayoristapp/catalogo/lotes/",
        CatalogoLotesRelayAPIView.as_view(),
        name="mayoristapp_catalogo_lotes",
    ),
    path(
        "api/mayoristapp/catalogo/tacc-opciones/",
        CatalogoTaccRelayAPIView.as_view(),
        name="mayoristapp_catalogo_tacc_opciones",
    ),
    path(
        "api/mayoristapp/catalogo/mas-vendidos/",
        CatalogoMasVendidosRelayAPIView.as_view(),
        name="mayoristapp_catalogo_mas_vendidos",
    ),
    path(
        "api/mayoristapp/catalogo/articulos/listado/",
        CatalogoArticulosListadoRelayAPIView.as_view(),
        name="mayoristapp_catalogo_articulos_listado",
    ),
    path(
        "api/mayoristapp/catalogo/articulos/<int:idart>/detalle/",
        CatalogoArticuloDetalleRelayAPIView.as_view(),
        name="mayoristapp_catalogo_articulo_detalle",
    ),
    path(
        "api/mayoristapp/precios/lista-precio/",
        ListaPrecioRelayAPIView.as_view(),
        name="mayoristapp_precios_lista_precio",
    ),
    path(
        "api/mayoristapp/precios/promociones/",
        PromocionesRelayAPIView.as_view(),
        name="mayoristapp_precios_promociones",
    ),
    path(
        "api/mayoristapp/clientes/buscar/",
        ClienteBuscarRelayAPIView.as_view(),
        name="mayoristapp_clientes_buscar",
    ),
    path(
        "api/mayoristapp/clientes/seleccionado/",
        ClienteSeleccionadoRelayAPIView.as_view(),
        name="mayoristapp_clientes_seleccionado",
    ),
    path(
        "api/mayoristapp/clientes/comprobante-formulario/",
        ClienteComprobanteFormularioRelayAPIView.as_view(),
        name="mayoristapp_clientes_comprobante_formulario",
    ),
    path(
        "api/mayoristapp/clientes/seleccionar/",
        ClienteSeleccionarRelayAPIView.as_view(),
        name="mayoristapp_clientes_seleccionar",
    ),
    path(
        "api/mayoristapp/clientes/domicilio/",
        ClienteDomicilioRelayAPIView.as_view(),
        name="mayoristapp_clientes_domicilio",
    ),
    path(
        "api/mayoristapp/clientes/domicilio-opciones-visita/",
        ClienteDomicilioOpcionesVisitaRelayAPIView.as_view(),
        name="mayoristapp_clientes_domicilio_opciones_visita",
    ),
    path(
        "api/mayoristapp/clientes/contacto/",
        ClienteContactoRelayAPIView.as_view(),
        name="mayoristapp_clientes_contacto",
    ),
    path(
        "api/mayoristapp/clientes/rapido/",
        ClienteRapidoRelayAPIView.as_view(),
        name="mayoristapp_clientes_rapido",
    ),
    path(
        "api/mayoristapp/comprobantes/pedidos/",
        ComprobantesPedidosRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_pedidos",
    ),
    path(
        "api/mayoristapp/comprobantes/presupuestos/",
        ComprobantesPresupuestosRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_presupuestos",
    ),
    path(
        "api/mayoristapp/comprobantes/remitos/",
        ComprobantesRemitosRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_remitos",
    ),
    path(
        "api/mayoristapp/comprobantes/sugerencias-nro/",
        ComprobantesSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_sugerencias_nro",
    ),
    path(
        "api/mayoristapp/comprobantes/comprobante-a-mail/",
        ComprobanteAMailRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_comprobante_a_mail",
    ),
    path(
        "api/mayoristapp/comprobantes/comprobante-a-mail/enqueue/",
        ComprobanteAMailEnqueueRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_comprobante_a_mail_enqueue",
    ),
    path(
        "api/mayoristapp/comprobantes/comprobante-a-mail/queue-status/",
        ComprobanteAMailQueueStatusRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_comprobante_a_mail_queue_status",
    ),
    path(
        "api/mayoristapp/comprobantes/no-cancelados/",
        ComprobantesNoCanceladosRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_no_cancelados",
    ),
    path(
        "api/mayoristapp/comprobantes/no-cancelados-resumen/",
        ComprobantesNoCanceladosResumenRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_no_cancelados_resumen",
    ),
    path(
        "api/mayoristapp/comprobantes/anular-pedido/",
        ComprobantesAnularPedidoRelayAPIView.as_view(),
        name="mayoristapp_comprobantes_anular_pedido",
    ),
    path(
        "api/mayoristapp/ctacte/consumos-resumen/",
        ConsumosResumenRelayAPIView.as_view(),
        name="mayoristapp_ctacte_consumos_resumen",
    ),
    path(
        "api/mayoristapp/ctacte/movimientos/",
        CtacteMovimientosRelayAPIView.as_view(),
        name="mayoristapp_ctacte_movimientos",
    ),
    path(
        "api/mayoristapp/ctacte/sugerencias-nro/",
        CtacteSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_ctacte_sugerencias_nro",
    ),
    path(
        "api/mayoristapp/ctacte/pedidos/sugerencias-nro/",
        CuentaCorrientePedidosSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_ctacte_pedidos_sugerencias_nro",
    ),
    path(
        "api/mayoristapp/ctacte/pedidos/",
        CuentaCorrientePedidosRelayAPIView.as_view(),
        name="mayoristapp_ctacte_pedidos",
    ),
    path(
        "api/mayoristapp/recibos/listado/",
        RecibosListadoRelayAPIView.as_view(),
        name="mayoristapp_recibos_listado",
    ),
    path(
        "api/mayoristapp/fe/nota-credito/listado/",
        NotaCreditoListadoRelayAPIView.as_view(),
        name="mayoristapp_fe_nota_credito_listado",
    ),
    path(
        "api/mayoristapp/fe/nota-credito/sugerencias-nro/",
        NotaCreditoSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_fe_nota_credito_sugerencias_nro",
    ),
    path(
        "api/mayoristapp/fe/factura-electronica/listado/",
        FacturaElectronicaListadoRelayAPIView.as_view(),
        name="mayoristapp_fe_factura_electronica_listado",
    ),
    path(
        "api/mayoristapp/fe/factura-electronica/sugerencias-nro/",
        FacturaElectronicaSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_fe_factura_electronica_sugerencias_nro",
    ),
    path(
        "api/mayoristapp/fe/facturas-imputar/listado/",
        FacturasImputarListadoRelayAPIView.as_view(),
        name="mayoristapp_fe_facturas_imputar_listado",
    ),
    path(
        "api/mayoristapp/fe/facturas-imputar/sugerencias-nro/",
        FacturasImputarSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_fe_facturas_imputar_sugerencias_nro",
    ),
    path(
        "api/mayoristapp/fe/facturas-imputar/accion/",
        FacturasImputarAccionRelayAPIView.as_view(),
        name="mayoristapp_fe_facturas_imputar_accion",
    ),
    path(
        "api/mayoristapp/recibos/alta/accion/",
        ReciboAltaRelayAPIView.as_view(),
        name="mayoristapp_recibos_alta_accion",
    ),
    path(
        "api/mayoristapp/recibos/alta/catalogos/",
        ReciboAltaCatalogosRelayAPIView.as_view(),
        name="mayoristapp_recibos_alta_catalogos",
    ),
    path(
        "api/mayoristapp/estadisticas/filtros/",
        FiltrosEstadisticasRelayAPIView.as_view(),
        name="mayoristapp_estadisticas_filtros",
    ),
    path(
        "api/mayoristapp/estadisticas/devoluciones/",
        DevolucionesRelayAPIView.as_view(),
        name="mayoristapp_estadisticas_devoluciones",
    ),
    path(
        "api/mayoristapp/estadisticas/devoluciones/sugerencias-nro/",
        DevolucionesSugerenciasNroRelayAPIView.as_view(),
        name="mayoristapp_estadisticas_devoluciones_sugerencias_nro",
    ),
    # --- Carrito mayorista (Fase P1) ---
    path(
        "api/mayoristapp/carrito/",
        CarritoRelayAPIView.as_view(),
        name="mayoristapp_carrito",
    ),
    path(
        "api/mayoristapp/carrito/items/<int:item_id>/",
        CarritoItemRelayAPIView.as_view(),
        name="mayoristapp_carrito_item",
    ),
    path(
        "api/mayoristapp/carrito/vaciar/",
        CarritoVaciarRelayAPIView.as_view(),
        name="mayoristapp_carrito_vaciar",
    ),
    path(
        "api/mayoristapp/carrito/descuento-pie/",
        CarritoDescuentoPieRelayAPIView.as_view(),
        name="mayoristapp_carrito_descuento_pie",
    ),
    # --- Checkout mayorista (Fase P2) ---
    path(
        "api/mayoristapp/checkout/confirmar/",
        CheckoutConfirmarRelayAPIView.as_view(),
        name="mayoristapp_checkout_confirmar",
    ),
    # --- Export lista de precios PDF (Fase P3) ---
    path(
        "api/mayoristapp/catalogo/lista-precios.pdf",
        ExportarListaPreciosPDFRelayAPIView.as_view(),
        name="mayoristapp_lista_precios_pdf",
    ),
] + mayoristapp_listado_urlpatterns()
