# Generated by Django 4.2 on 2026-02-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "language",
                    models.CharField(
                        default="es", max_length=10, verbose_name="Idioma"
                    ),
                ),
                (
                    "is_authorized",
                    models.BooleanField(default=True, verbose_name="Autorizado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_users",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario de soporte",
                "verbose_name_plural": "Usuarios de soporte",
                "db_table": "support_support_user",
            },
        ),
        migrations.CreateModel(
            name="ChannelIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                        verbose_name="Tipo canal",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=255,
                        verbose_name="ID externo (telegram_id, E.164, email)",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "support_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_identities",
                        to="support_users.supportuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identidad de canal",
                "verbose_name_plural": "Identidades de canal",
                "db_table": "support_channel_identity",
            },
        ),
        migrations.AddIndex(
            model_name="channelidentity",
            index=models.Index(
                fields=["support_user"], name="support_cha_support_1349db_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="channelidentity",
            constraint=models.UniqueConstraint(
                fields=("channel_type", "external_id"),
                name="support_channel_identity_unique",
            ),
        ),
    ]
