# Generated by Django 4.2 on 2025-12-09 13:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_increase_permiso_codigo_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the organizational department/area', max_length=255, verbose_name='Department Name')),
                ('code', models.CharField(blank=True, help_text='Optional internal code for the department', max_length=50, null=True, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, help_text='Optional description of the department', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is currently active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('empresa', models.ForeignKey(help_text='Company to which this department belongs', on_delete=django.db.models.deletion.CASCADE, related_name='sia_departments', to='core.empresa', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['empresa', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the evaluation cycle (e.g., "Q1 2024", "Annual 2024")', max_length=255, verbose_name='Cycle Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of the evaluation cycle', null=True, verbose_name='Description')),
                ('start_date', models.DateField(help_text='Start date of the evaluation cycle', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='End date of the evaluation cycle', verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this cycle is currently active and accepting responses', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this evaluation cycle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluation_cycles', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('empresa', models.ForeignKey(help_text='Company for which this evaluation cycle is conducted', on_delete=django.db.models.deletion.CASCADE, related_name='sia_evaluation_cycles', to='core.empresa', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Evaluation Cycle',
                'verbose_name_plural': 'Evaluation Cycles',
                'ordering': ['-start_date', 'empresa', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StrategicSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', help_text='Current status of the survey response', max_length=20, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Date and time when the survey was submitted', null=True, verbose_name='Submitted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('department', models.ForeignKey(blank=True, help_text='Department/area of the executive', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='sia.department', verbose_name='Department')),
                ('evaluation_cycle', models.ForeignKey(help_text='Evaluation cycle to which this response belongs', on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='sia.evaluationcycle', verbose_name='Evaluation Cycle')),
                ('user', models.ForeignKey(help_text='Executive user who completed this survey', on_delete=django.db.models.deletion.CASCADE, related_name='sia_survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Strategic Survey Response',
                'verbose_name_plural': 'Strategic Survey Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('area_health', 'Area Health'), ('team_performance', 'Team Performance'), ('strategy_alignment', 'Strategy Alignment'), ('process_maturity', 'Process Maturity'), ('tech_maturity', 'Technology Maturity')], help_text='Dimension being rated', max_length=50, verbose_name='Dimension')),
                ('value', models.PositiveIntegerField(help_text='Rating value from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating Value')),
                ('notes', models.TextField(blank=True, help_text='Optional notes explaining the rating', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('survey_response', models.ForeignKey(help_text='Survey response to which this rating belongs', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sia.strategicsurveyresponse', verbose_name='Survey Response')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['survey_response', 'dimension'],
            },
        ),
        migrations.CreateModel(
            name='OpenAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('critical_priorities', 'Critical Priorities'), ('main_risks', 'Main Risks'), ('unexploited_opportunities', 'Unexploited Opportunities'), ('other', 'Other')], help_text='Type of open question being answered', max_length=50, verbose_name='Question Type')),
                ('question_text', models.CharField(help_text='Text of the question (can be customized per cycle)', max_length=500, verbose_name='Question Text')),
                ('answer', models.TextField(help_text='Answer to the open question', verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('survey_response', models.ForeignKey(help_text='Survey response to which this answer belongs', on_delete=django.db.models.deletion.CASCADE, related_name='open_answers', to='sia.strategicsurveyresponse', verbose_name='Survey Response')),
            ],
            options={
                'verbose_name': 'Open Answer',
                'verbose_name_plural': 'Open Answers',
                'ordering': ['survey_response', 'question_type'],
            },
        ),
        migrations.CreateModel(
            name='FodaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadrant', models.CharField(choices=[('strength', 'Strength'), ('weakness', 'Weakness'), ('opportunity', 'Opportunity'), ('threat', 'Threat')], help_text='FODA quadrant to which this item belongs', max_length=20, verbose_name='Quadrant')),
                ('description', models.TextField(help_text='Description of the FODA item', verbose_name='Description')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority within the quadrant (1-3, where 1 is highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('survey_response', models.ForeignKey(help_text='Survey response to which this FODA item belongs', on_delete=django.db.models.deletion.CASCADE, related_name='foda_items', to='sia.strategicsurveyresponse', verbose_name='Survey Response')),
            ],
            options={
                'verbose_name': 'FODA Item',
                'verbose_name_plural': 'FODA Items',
                'ordering': ['survey_response', 'quadrant', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='CameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('correct', 'Correct'), ('address', 'Address'), ('maintain', 'Maintain'), ('exploit', 'Exploit')], help_text='Type of CAME action', max_length=20, verbose_name='Action Type')),
                ('title', models.CharField(help_text='Title of the action', max_length=255, verbose_name='Action Title')),
                ('description', models.TextField(help_text='Detailed description of the action', verbose_name='Description')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority of the action (1-5, where 1 is highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Priority')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', help_text='Current status of the action', max_length=20, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, help_text='Expected completion date', null=True, verbose_name='Due Date')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and time when the action was completed', null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User responsible for executing this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_came_actions', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_came_actions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('evaluation_cycle', models.ForeignKey(help_text='Evaluation cycle to which this action belongs', on_delete=django.db.models.deletion.CASCADE, related_name='came_actions', to='sia.evaluationcycle', verbose_name='Evaluation Cycle')),
                ('related_foda_item', models.ForeignKey(blank=True, help_text='FODA item that originated this action (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='came_actions', to='sia.fodaitem', verbose_name='Related FODA Item')),
            ],
            options={
                'verbose_name': 'CAME Action',
                'verbose_name_plural': 'CAME Actions',
                'ordering': ['evaluation_cycle', 'action_type', 'priority'],
            },
        ),
        migrations.AddIndex(
            model_name='strategicsurveyresponse',
            index=models.Index(fields=['evaluation_cycle', 'user'], name='sia_strateg_evaluat_626363_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicsurveyresponse',
            index=models.Index(fields=['status'], name='sia_strateg_status_46249c_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicsurveyresponse',
            index=models.Index(fields=['department'], name='sia_strateg_departm_abf7fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategicsurveyresponse',
            unique_together={('evaluation_cycle', 'user')},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['survey_response', 'dimension'], name='sia_rating_survey__0a451d_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['dimension'], name='sia_rating_dimensi_3f48bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('survey_response', 'dimension')},
        ),
        migrations.AddIndex(
            model_name='openanswer',
            index=models.Index(fields=['survey_response', 'question_type'], name='sia_openans_survey__ff5b33_idx'),
        ),
        migrations.AddIndex(
            model_name='openanswer',
            index=models.Index(fields=['question_type'], name='sia_openans_questio_101663_idx'),
        ),
        migrations.AddIndex(
            model_name='fodaitem',
            index=models.Index(fields=['survey_response', 'quadrant'], name='sia_fodaite_survey__39785a_idx'),
        ),
        migrations.AddIndex(
            model_name='fodaitem',
            index=models.Index(fields=['quadrant'], name='sia_fodaite_quadran_a244f8_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcycle',
            index=models.Index(fields=['empresa', 'start_date'], name='sia_evaluat_empresa_244f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcycle',
            index=models.Index(fields=['is_active'], name='sia_evaluat_is_acti_a2bd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['empresa', 'name'], name='sia_departm_empresa_3c2613_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='sia_departm_is_acti_1e26e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('empresa', 'name')},
        ),
        migrations.AddIndex(
            model_name='cameaction',
            index=models.Index(fields=['evaluation_cycle', 'action_type'], name='sia_cameact_evaluat_2015e5_idx'),
        ),
        migrations.AddIndex(
            model_name='cameaction',
            index=models.Index(fields=['status'], name='sia_cameact_status_98421d_idx'),
        ),
        migrations.AddIndex(
            model_name='cameaction',
            index=models.Index(fields=['assigned_to'], name='sia_cameact_assigne_098920_idx'),
        ),
    ]
