# Generated by Django 4.2 on 2025-12-17 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0002_auto_create_sia_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fodaitem',
            name='description',
            field=models.TextField(help_text='Descripción del elemento FODA', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='fodaitem',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Prioridad dentro del cuadrante (1-3, donde 1 es la más alta)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='fodaitem',
            name='quadrant',
            field=models.CharField(choices=[('strength', 'Fortaleza'), ('weakness', 'Debilidad'), ('opportunity', 'Oportunidad'), ('threat', 'Amenaza')], help_text='Cuadrante FODA al que pertenece este elemento', max_length=20, verbose_name='Cuadrante'),
        ),
        migrations.AlterField(
            model_name='openanswer',
            name='answer',
            field=models.TextField(help_text='Respuesta a la pregunta abierta', verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='openanswer',
            name='question_text',
            field=models.CharField(help_text='Texto de la pregunta (puede personalizarse por ciclo)', max_length=500, verbose_name='Texto de la Pregunta'),
        ),
        migrations.AlterField(
            model_name='openanswer',
            name='question_type',
            field=models.CharField(choices=[('critical_priorities', 'Prioridades Críticas'), ('main_risks', 'Riesgos Principales'), ('unexploited_opportunities', 'Oportunidades No Aprovechadas'), ('other', 'Otro')], help_text='Tipo de pregunta abierta que se está respondiendo', max_length=50, verbose_name='Tipo de Pregunta'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='dimension',
            field=models.CharField(choices=[('area_health', 'Salud del Área'), ('team_performance', 'Rendimiento del Equipo'), ('strategy_alignment', 'Alineación Estratégica'), ('process_maturity', 'Madurez del Proceso'), ('tech_maturity', 'Madurez Tecnológica')], help_text='Dimensión que se está evaluando', max_length=50, verbose_name='Dimensión'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas opcionales que explican el rating', null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.PositiveIntegerField(help_text='Valor del rating de 1 a 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Valor del Rating'),
        ),
    ]
