# Generated by Django 4.2 on 2026-02-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0001_opt_optlinea'),
    ]

    operations = [
        migrations.AddField(
            model_name='opt',
            name='codigo_movimiento',
            field=models.IntegerField(blank=True, help_text='CodigoMovimiento del comprobante MSTOCK (OPT) cuando se liberó; para imprimir comprobante.', null=True),
        ),
    ]
