# Generated by Django 4.2 on 2026-03-23 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0005_optlinea_id_operario_opt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opt',
            options={'managed': False, 'ordering': ['-fecha_creacion'], 'verbose_name': 'OPT (Pedido de producción)', 'verbose_name_plural': 'OPT (Pedidos de producción)'},
        ),
        migrations.AlterModelOptions(
            name='optlinea',
            options={'managed': False, 'ordering': ['id'], 'verbose_name': 'Línea OPT', 'verbose_name_plural': 'Líneas OPT'},
        ),
    ]
