# Generated by Django 4.2 on 2026-06-29 18:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0008_armado_surtido'),
    ]

    operations = [
        migrations.CreateModel(
            name='MprArmadoLote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_empresa', models.CharField(db_index=True, max_length=64)),
                ('modo', models.CharField(choices=[('1ra', 'Armado 1ra'), ('2da', 'Armado 2da')], help_text='Modo de armado: 1ra (Semi → Terminado 1ra) o 2da (2da selección → Terminado 2da)', max_length=3)),
                ('id_operario', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField(help_text='Usuario que ejecutó el lote de armado')),
                ('deposito_origen', models.IntegerField()),
                ('deposito_destino', models.IntegerField()),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True)),
                ('cantidad_items', models.IntegerField(default=0, help_text='Cantidad total de ítems en el lote')),
                ('cantidad_exitosos', models.IntegerField(default=0, help_text='Cantidad de ítems exitosos')),
                ('cantidad_fallidos', models.IntegerField(default=0, help_text='Cantidad de ítems fallidos')),
            ],
            options={
                'verbose_name': 'Lote de armado',
                'verbose_name_plural': 'Lotes de armado',
                'ordering': ['-ejecutado_en'],
            },
        ),
        migrations.CreateModel(
            name='MprImputacionArmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_empresa', models.CharField(db_index=True, max_length=64)),
                ('codigo_movimiento', models.IntegerField(db_index=True, help_text='CodigoMovimiento del MSTOCK de armado 1ra')),
                ('id_articulo_pack', models.IntegerField(help_text='IDArt del pack armado')),
                ('cantidad', models.IntegerField(help_text='Unidades imputadas en esta línea')),
                ('codigo_movimiento_pedido', models.IntegerField(help_text='CodigoMovimiento del comprobante de pedido (comp_ped)')),
                ('id_lista_detalle', models.IntegerField(blank=True, help_text='ID de lista_produccion_detalle si aplica', null=True)),
                ('origen_regla', models.CharField(choices=[('FIFO', 'FIFO'), ('MANUAL', 'Manual')], help_text='Origen de la regla de imputación: FIFO o Manual', max_length=10)),
                ('id_usuario_supervisor', models.IntegerField(help_text='Usuario supervisor que confirmó la imputación')),
                ('imputado_en', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, default='', help_text='Notas opcionales de ajuste manual', max_length=500)),
            ],
            options={
                'verbose_name': 'Imputación de armado 1ra',
                'verbose_name_plural': 'Imputaciones de armado 1ra',
                'ordering': ['-imputado_en'],
            },
        ),
        migrations.RenameIndex(
            model_name='mprarmadosurtidomovimiento',
            new_name='mpr_mprarma_base_em_b83ab9_idx',
            old_name='mpr_as_mov_be_cod',
        ),
        migrations.AddField(
            model_name='mprarmadosurtidomovimiento',
            name='estado_imputacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('completo', 'Completo'), ('na', 'No aplica')], default='na', help_text='Estado de imputación a pedidos (solo para modo 1ra)', max_length=10),
        ),
        migrations.AddField(
            model_name='mprarmadosurtidomovimiento',
            name='modo',
            field=models.CharField(choices=[('1ra', 'Armado 1ra'), ('2da', 'Armado 2da')], default='2da', help_text='Modo de armado: 1ra o 2da', max_length=3),
        ),
        migrations.AddIndex(
            model_name='mprarmadosurtidomovimiento',
            index=models.Index(fields=['modo', 'estado_imputacion'], name='mpr_mprarma_modo_0712bb_idx'),
        ),
        migrations.AddIndex(
            model_name='mprimputacionarmado',
            index=models.Index(fields=['base_empresa', 'codigo_movimiento'], name='mpr_mprimpu_base_em_063e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='mprimputacionarmado',
            index=models.Index(fields=['codigo_movimiento_pedido'], name='mpr_mprimpu_codigo__d92276_idx'),
        ),
        migrations.AddIndex(
            model_name='mprimputacionarmado',
            index=models.Index(fields=['imputado_en'], name='mpr_mprimpu_imputad_818074_idx'),
        ),
        migrations.AddIndex(
            model_name='mprarmadolote',
            index=models.Index(fields=['base_empresa', 'modo'], name='mpr_mprarma_base_em_7704b4_idx'),
        ),
        migrations.AddIndex(
            model_name='mprarmadolote',
            index=models.Index(fields=['ejecutado_en'], name='mpr_mprarma_ejecuta_f36a69_idx'),
        ),
        migrations.AddField(
            model_name='mprarmadosurtidomovimiento',
            name='id_lote_armado',
            field=models.ForeignKey(blank=True, help_text='Lote de armado al que pertenece este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='mpr.mprarmadolote'),
        ),
    ]
