# Generated by Django 4.2 on 2026-07-03 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0009_armado_unificado_lote_imputacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MprRosterDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_empresa', models.CharField(db_index=True, help_text='Scope por empresa.', max_length=64)),
                ('fecha', models.DateField(help_text='Fecha de la asignación (YYYY-MM-DD).')),
                ('id_operario', models.IntegerField(help_text='FK lógico a sue_abm_empleado.id_sue_abm_empleado.')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación.')),
            ],
            options={
                'verbose_name': 'Asignación de turno (roster)',
                'verbose_name_plural': 'Asignaciones de turno (roster)',
                'ordering': ['base_empresa', 'fecha', 'id_operario'],
            },
        ),
        migrations.CreateModel(
            name='MprTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_empresa', models.CharField(db_index=True, help_text='Scope por empresa (ej. Empresa1).', max_length=64)),
                ('nombre', models.CharField(help_text='Nombre del turno (ej. Mañana, Tarde, Noche).', max_length=100)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del turno (formato HH:MM).')),
                ('hora_fin', models.TimeField(help_text='Hora de finalización del turno. Si < hora_inicio, cruza medianoche.')),
                ('activo', models.BooleanField(default=True, help_text='Flag de activación. Turnos inactivos no se ofrecen en nuevas asignaciones.')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación.')),
            ],
            options={
                'verbose_name': 'Turno de producción',
                'verbose_name_plural': 'Turnos de producción',
                'ordering': ['base_empresa', 'nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='mprturno',
            index=models.Index(fields=['base_empresa', 'activo'], name='mpr_turno_empresa_activo_idx'),
        ),
        migrations.AddConstraint(
            model_name='mprturno',
            constraint=models.UniqueConstraint(fields=('base_empresa', 'nombre'), name='mpr_turno_nombre_unico_empresa'),
        ),
        migrations.AddField(
            model_name='mprrosterdia',
            name='turno',
            field=models.ForeignKey(help_text='Turno asignado. PROTECT: no permitir eliminar turno si tiene asignaciones.', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_roster', to='mpr.mprturno'),
        ),
        migrations.AddIndex(
            model_name='mprrosterdia',
            index=models.Index(fields=['base_empresa', 'fecha'], name='mpr_roster_emp_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='mprrosterdia',
            constraint=models.UniqueConstraint(fields=('base_empresa', 'fecha', 'id_operario'), name='mpr_roster_dia_unico_operario_fecha'),
        ),
    ]
