# Generated by Django 4.2 on 2026-07-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0011_mprparte_mprpartelinea_mprparteajuste'),
    ]

    operations = [
        migrations.CreateModel(
            name='MprTransicionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_empresa', models.CharField(db_index=True, help_text='Scope por empresa (base_empresa de AdministraNET).', max_length=64)),
                ('id_articulo', models.IntegerField(help_text='ID componente (nivel al que opera la transición, ya explotado).')),
                ('tipo_origen', models.CharField(help_text="Etapa de origen (constante TIPO_MPR_*, ej. 'Produccion').", max_length=64)),
                ('tipo_destino', models.CharField(help_text="Etapa de destino (constante TIPO_MPR_*, ej. 'Planchado').", max_length=64)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad transferida en unidades del componente.', max_digits=15)),
                ('codigo_movimiento', models.IntegerField(blank=True, help_text='CodigoMovimiento MSTOCK de la transición en MySQL legacy.', null=True)),
                ('id_usuario', models.IntegerField(help_text='ID usuario de AdministraNET que realizó la transición.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transición de lote MPR',
                'verbose_name_plural': 'Transiciones de lote MPR',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='mprparte',
            name='movimiento_fisico_ok',
            field=models.BooleanField(default=False, help_text='True si el asiento físico MySQL (MSTOCK OPP + stock_deposito) fue confirmado.'),
        ),
        migrations.AddField(
            model_name='mprparteajuste',
            name='ajuste_fisico_ok',
            field=models.BooleanField(default=False, help_text='True si el delta físico MySQL (stock_deposito) fue confirmado.'),
        ),
        migrations.AddIndex(
            model_name='mprtransicionlote',
            index=models.Index(fields=['base_empresa', 'id_articulo'], name='mpr_tl_emp_art_idx'),
        ),
        migrations.AddIndex(
            model_name='mprtransicionlote',
            index=models.Index(fields=['base_empresa', 'creado_en'], name='mpr_tl_emp_fecha_idx'),
        ),
    ]
