# Generated by Django 4.2 on 2026-07-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0012_etapa5_transiciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='mprparte',
            name='id_lista_produccion',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID de la OPT activa (lista_produccion_agrupada.id_lista_produccion) al momento de registrar el parte. Capturado best-effort para trazabilidad E6.', null=True),
        ),
    ]
