# Generated by Django 4.2 on 2025-05-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuarioextendido_activo_alter_usuarioextendido_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioextendido',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuarioextendido',
            name='roles',
            field=models.ManyToManyField(blank=True, to='core.rol'),
        ),
    ]
