# Generated by Django 4.2 on 2025-05-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_usuarioextendido_rol_usuarioextendido_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioextendido',
            name='activo',
        ),
        migrations.AlterField(
            model_name='usuarioextendido',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
