# Generated by Django 4.2 on 2025-06-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_currency_systemconfiguration_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(help_text='Ej: cantidad, peso, volumen, longitud, etc.', max_length=50)),
                ('ratio', models.DecimalField(decimal_places=6, help_text='Factor multiplicador respecto a la unidad de referencia de la categoría.', max_digits=18)),
                ('is_reference', models.BooleanField(default=False, help_text='Marca si esta es la unidad base de su categoría.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
    ]
