# Generated by Django 4.2 on 2025-06-23 02:51

from django.db import migrations

def asignar_permisos_almacen(apps, schema_editor):
    Rol = apps.get_model('core', 'Rol')
    Permiso = apps.get_model('core', 'Permiso')

    try:
        rol_almacen = Rol.objects.get(nombre__iexact='Almacén')
    except Rol.DoesNotExist:
        # Si el rol no existe, no hacemos nada.
        # En un escenario real, podríamos querer crearlo aquí.
        return

    permisos_almacen = [
        "inventario.ver_dashboard",
        "inventario.ver_stock",
        "inventario.ver_producto",
        "inventario.crear_producto",
        "inventario.editar_producto",
        "inventario.ver_almacen",
        "inventario.ver_ubicacion",
        "inventario.realizar_ajuste",
        "inventario.ver_movimientos",
    ]

    permisos_a_asignar = Permiso.objects.filter(codigo__in=permisos_almacen)
    rol_almacen.permisos.add(*permisos_a_asignar)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_permiso_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.RunPython(asignar_permisos_almacen),
    ]
