# Generated by Django 4.2 on 2025-06-23 04:47

from django.db import migrations

def seed_currencies(apps, schema_editor):
    Currency = apps.get_model('core', 'Currency')
    Currency.objects.get_or_create(
        code='ARS',
        defaults={'name': 'Peso Argentino', 'symbol': '$'}
    )
    Currency.objects.get_or_create(
        code='USD',
        defaults={'name': 'Dólar Estadounidense', 'symbol': 'U$S'}
    )

def seed_uom(apps, schema_editor):
    UnitOfMeasure = apps.get_model('core', 'UnitOfMeasure')
    
    # Cantidad
    UnitOfMeasure.objects.get_or_create(code='un', defaults={
        'name': 'Unidad', 'category': 'Cantidad', 'ratio': 1.0, 'is_reference': True
    })
    UnitOfMeasure.objects.get_or_create(code='par', defaults={
        'name': 'Par', 'category': 'Cantidad', 'ratio': 2.0
    })
    UnitOfMeasure.objects.get_or_create(code='doc', defaults={
        'name': 'Docena', 'category': 'Cantidad', 'ratio': 12.0
    })

    # Peso
    UnitOfMeasure.objects.get_or_create(code='kg', defaults={
        'name': 'Kilogramo', 'category': 'Peso', 'ratio': 1.0, 'is_reference': True
    })
    UnitOfMeasure.objects.get_or_create(code='g', defaults={
        'name': 'Gramo', 'category': 'Peso', 'ratio': 0.001
    })
    UnitOfMeasure.objects.get_or_create(code='t', defaults={
        'name': 'Tonelada', 'category': 'Peso', 'ratio': 1000.0
    })

    # Volumen
    UnitOfMeasure.objects.get_or_create(code='l', defaults={
        'name': 'Litro', 'category': 'Volumen', 'ratio': 1.0, 'is_reference': True
    })
    UnitOfMeasure.objects.get_or_create(code='ml', defaults={
        'name': 'Mililitro', 'category': 'Volumen', 'ratio': 0.001
    })
    
    # Longitud
    UnitOfMeasure.objects.get_or_create(code='m', defaults={
        'name': 'Metro', 'category': 'Longitud', 'ratio': 1.0, 'is_reference': True
    })
    UnitOfMeasure.objects.get_or_create(code='cm', defaults={
        'name': 'Centímetro', 'category': 'Longitud', 'ratio': 0.01
    })

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_systemconfiguration_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_currencies),
        migrations.RunPython(seed_uom),
    ]
