# Generated by Django 4.2 on 2025-07-05 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_add_sales_order_workflow'),
        ('core', '0022_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('account_type', models.CharField(choices=[('assets', 'Assets'), ('liabilities', 'Liabilities'), ('equity', 'Equity'), ('income', 'Income'), ('expenses', 'Expenses')], max_length=20, verbose_name='Account Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_reconcilable', models.BooleanField(default=False, verbose_name='Reconcilable')),
                ('allow_reconciliation', models.BooleanField(default=False, verbose_name='Allow Reconciliation')),
                ('deprecated', models.BooleanField(default=False, verbose_name='Deprecated')),
                ('is_tax_account', models.BooleanField(default=False, verbose_name='Tax Account')),
                ('tax_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='core.empresa')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('country_id', models.CharField(blank=True, max_length=2, verbose_name='Country')),
                ('state_id', models.CharField(blank=True, max_length=64, verbose_name='State/Province')),
                ('zip_from', models.CharField(blank=True, max_length=24, verbose_name='Zip From')),
                ('zip_to', models.CharField(blank=True, max_length=24, verbose_name='Zip To')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_positions', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Fiscal Position',
                'verbose_name_plural': 'Fiscal Positions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('journal_type', models.CharField(choices=[('sale', 'Sales'), ('purchase', 'Purchase'), ('cash', 'Cash'), ('bank', 'Bank'), ('misc', 'Miscellaneous')], max_length=10, verbose_name='Journal Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sequence_id', models.IntegerField(default=1, verbose_name='Sequence ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccounts')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='core.empresa')),
                ('tax_account', models.ForeignKey(blank=True, limit_choices_to={'is_tax_account': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_journals', to='accounting.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Entry Number')),
                ('date', models.DateField(verbose_name='Entry Date')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Reference')),
                ('narration', models.TextField(blank=True, verbose_name='Narration')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='State')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('origin_model', models.CharField(blank=True, max_length=50, verbose_name='Origin Model')),
                ('origin_id', models.IntegerField(blank=True, null=True, verbose_name='Origin ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.empresa')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.journal')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Amount')),
                ('amount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount'), ('group', 'Group of Taxes'), ('code', 'Python Code')], default='percent', max_length=20, verbose_name='Amount Type')),
                ('price_include', models.BooleanField(default=False, verbose_name='Included in Price')),
                ('include_base_amount', models.BooleanField(default=True, verbose_name='Include Base Amount')),
                ('is_base_affected', models.BooleanField(default=True, verbose_name='Base Affected')),
                ('sequence', models.IntegerField(default=10, verbose_name='Sequence')),
                ('python_compute', models.TextField(blank=True, verbose_name='Python Compute Code')),
                ('python_applicable', models.TextField(blank=True, verbose_name='Python Applicable Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxes_sales', to='accounting.chartofaccounts', verbose_name='Sales Account')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='core.empresa')),
                ('refund_account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxes_purchases', to='accounting.chartofaccounts', verbose_name='Purchase Account')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
                'ordering': ['tax_group', 'sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Base Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Amount')),
                ('origin_model', models.CharField(max_length=50, verbose_name='Origin Model')),
                ('origin_id', models.IntegerField(verbose_name='Origin ID')),
                ('origin_line_id', models.IntegerField(blank=True, null=True, verbose_name='Origin Line ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_lines', to='accounting.tax')),
            ],
            options={
                'verbose_name': 'Tax Line',
                'verbose_name_plural': 'Tax Lines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_groups_sales', to='accounting.chartofaccounts', verbose_name='Sales Account')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_groups', to='core.empresa')),
                ('refund_account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_groups_purchases', to='accounting.chartofaccounts', verbose_name='Purchase Account')),
            ],
            options={
                'verbose_name': 'Tax Group',
                'verbose_name_plural': 'Tax Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxes', to='accounting.taxgroup'),
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Credit')),
                ('amount_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Amount Currency')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_lines', to='accounting.chartofaccounts')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.client')),
                ('tax_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_lines', to='accounting.taxline')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPositionTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_mappings', to='accounting.fiscalposition')),
                ('tax_dest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_position_dest', to='accounting.tax', verbose_name='Destination Tax')),
                ('tax_src_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_position_src', to='accounting.tax', verbose_name='Source Tax')),
            ],
            options={
                'verbose_name': 'Fiscal Position Tax',
                'verbose_name_plural': 'Fiscal Position Taxes',
                'unique_together': {('fiscal_position', 'tax_src_id')},
            },
        ),
        migrations.AddField(
            model_name='fiscalposition',
            name='tax_ids',
            field=models.ManyToManyField(related_name='fiscal_positions', through='accounting.FiscalPositionTax', to='accounting.tax'),
        ),
    ]
