# Generated by Django 4.2 on 2025-07-11 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_usuarioextendido_branches_and_more'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_from', models.DateField(verbose_name='Start Date')),
                ('date_to', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('period_length', models.IntegerField(default=1, verbose_name='Period Length (months)')),
                ('auto_create_periods', models.BooleanField(default=True, verbose_name='Auto Create Periods')),
                ('allow_negative_cash', models.BooleanField(default=False, verbose_name='Allow Negative Cash')),
                ('allow_negative_equity', models.BooleanField(default=False, verbose_name='Allow Negative Equity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_years', to=settings.AUTH_USER_MODEL, verbose_name='Closed By')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fiscal_years', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'ordering': ['-date_from'],
                'unique_together': {('empresa', 'date_from', 'date_to')},
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_from', models.DateField(verbose_name='Start Date')),
                ('date_to', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('is_adjustment', models.BooleanField(default=False, verbose_name='Adjustment Period')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('sequence', models.IntegerField(default=1, verbose_name='Sequence')),
                ('allow_entries', models.BooleanField(default=True, verbose_name='Allow Entries')),
                ('allow_adjustments', models.BooleanField(default=True, verbose_name='Allow Adjustments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL, verbose_name='Closed By')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periods', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_periods', to='core.empresa')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear')),
            ],
            options={
                'verbose_name': 'Accounting Period',
                'verbose_name_plural': 'Accounting Periods',
                'ordering': ['fiscal_year', 'sequence'],
                'unique_together': {('empresa', 'fiscal_year', 'date_from', 'date_to')},
            },
        ),
    ]
