# Generated by Django 4.2 on 2025-07-15 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('sales', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='taxgroup',
        #     name='empresa',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_groups', to='core.empresa'),
        # ),
        migrations.AddField(
            model_name='taxgroup',
            name='refund_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_groups_purchases', to='accounting.chartofaccounts', verbose_name='Purchase Account'),
        ),
        migrations.AddField(
            model_name='tax',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxes_sales', to='accounting.chartofaccounts', verbose_name='Sales Account'),
        ),
        migrations.AddField(
            model_name='tax',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='tax',
            name='refund_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxes_purchases', to='accounting.chartofaccounts', verbose_name='Purchase Account'),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxes', to='accounting.taxgroup'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_lines', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.client'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='tax_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_lines', to='accounting.taxline'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='default_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='journal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='journal',
            name='tax_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_tax_account': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_journals', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='fiscalpositiontax',
            name='fiscal_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_mappings', to='accounting.fiscalposition'),
        ),
        migrations.AddField(
            model_name='fiscalpositiontax',
            name='tax_dest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_position_dest', to='accounting.tax', verbose_name='Destination Tax'),
        ),
        migrations.AddField(
            model_name='fiscalpositiontax',
            name='tax_src_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_position_src', to='accounting.tax', verbose_name='Source Tax'),
        ),
        migrations.AddField(
            model_name='fiscalposition',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_positions', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='fiscalposition',
            name='tax_ids',
            field=models.ManyToManyField(related_name='fiscal_positions', through='accounting.FiscalPositionTax', to='accounting.tax'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalpositiontax',
            unique_together={('fiscal_position', 'tax_src_id')},
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('fiscal_year', 'code')},
        ),
    ]
