# Generated by Django 4.2 on 2025-07-11 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_fiscalyear_accountingperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['fiscal_year', 'sequence', 'date_from'], 'verbose_name': 'Accounting Period', 'verbose_name_plural': 'Accounting Periods'},
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fiscalpositiontax',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='Sequence'),
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('fiscal_year', 'code')},
        ),
        migrations.RemoveField(
            model_name='accountingperiod',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='accountingperiod',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='accountingperiod',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='accountingperiod',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='accountingperiod',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='is_closed',
        ),
    ]
