# Generated by Django 4.2 on 2025-07-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresa_country_alter_empresa_logo_and_more'),
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxgroup',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_groups', to='core.empresa'),
        ),
    ]
