# Generated by Django 4.2 on 2025-07-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_accountingperiod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
    ]
