# Generated by Django 4.2 on 2025-07-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_fiscalyear_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
    ]
