# Generated by Django 4.2 on 2026-02-18 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_sequential",
                    models.PositiveIntegerField(verbose_name="Número secuencial"),
                ),
                (
                    "number_display",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Número display (SUP-...)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("iniciado", "Iniciado"),
                            ("en_analisis_ia", "En análisis IA"),
                            (
                                "esperando_respuesta_usuario",
                                "Esperando respuesta del usuario",
                            ),
                            ("derivado_a_humano", "Derivado a humano"),
                            ("asignado_a_agente_humano", "Asignado a agente humano"),
                            ("en_proceso_humano", "En proceso (humano)"),
                            ("resuelto", "Resuelto"),
                            ("cerrado", "Cerrado"),
                            ("reabierto", "Reabierto"),
                        ],
                        db_index=True,
                        default="iniciado",
                        max_length=32,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "sla_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="SLA inicio"
                    ),
                ),
                (
                    "sla_due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="SLA límite"
                    ),
                ),
                (
                    "sla_paused_since",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="SLA pausado desde"
                    ),
                ),
                (
                    "sla_warning_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="SLA warning enviado"
                    ),
                ),
                (
                    "sla_breached_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="SLA vencido"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso",
                "verbose_name_plural": "Casos",
                "db_table": "support_case",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Tipo canal"
                    ),
                ),
                (
                    "external_channel_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID externo canal"
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("user", "Usuario"),
                            ("system", "Sistema"),
                            ("agent", "Agente"),
                            ("ai", "IA"),
                            ("sla", "SLA"),
                        ],
                        max_length=20,
                        verbose_name="Remitente",
                    ),
                ),
                (
                    "sender_user_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="User ID si remitente=agent"
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Entrante"), ("outbound", "Saliente")],
                        max_length=10,
                        verbose_name="Dirección",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje",
                "verbose_name_plural": "Mensajes",
                "db_table": "support_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_text", models.TextField(verbose_name="Texto del resumen")),
                (
                    "model_version",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Modelo/versión"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="cases.case",
                    ),
                ),
                (
                    "from_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cases.message",
                    ),
                ),
                (
                    "to_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cases.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumen IA",
                "verbose_name_plural": "Resúmenes IA",
                "db_table": "support_case_summary",
            },
        ),
        migrations.CreateModel(
            name="CaseCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Último número"
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_counter",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contador de casos",
                "db_table": "support_case_counter",
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["case", "created_at"], name="support_mes_case_id_c1ad8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casesummary",
            index=models.Index(fields=["case"], name="support_cas_case_id_e1d39a_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["company", "status"], name="support_cas_company_a1759d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["assigned_to", "status"], name="support_cas_assigne_be6af2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["created_at"], name="support_cas_created_9d4b08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["sla_due_at"], name="support_cas_sla_due_4a6aef_idx"
            ),
        ),
    ]
