# Generated by Django 4.2 on 2025-07-12 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_usuarioextendido_branches_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloverDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True, verbose_name='Device ID')),
                ('serial_number', models.CharField(blank=True, max_length=255, verbose_name='Serial Number')),
                ('device_type', models.CharField(choices=[('station', 'Clover Station'), ('mini', 'Clover Mini'), ('flex', 'Clover Flex'), ('go', 'Clover Go'), ('mobile', 'Clover Mobile'), ('virtual', 'Virtual Terminal')], max_length=20, verbose_name='Device Type')),
                ('merchant_id', models.CharField(max_length=255, verbose_name='Merchant ID')),
                ('api_token', models.CharField(max_length=500, verbose_name='API Token')),
                ('app_id', models.CharField(blank=True, max_length=255, verbose_name='App ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='active', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Device')),
                ('supports_contactless', models.BooleanField(default=True, verbose_name='Supports Contactless')),
                ('supports_chip', models.BooleanField(default=True, verbose_name='Supports Chip')),
                ('supports_magnetic_stripe', models.BooleanField(default=True, verbose_name='Supports Magnetic Stripe')),
                ('supports_manual_entry', models.BooleanField(default=True, verbose_name='Supports Manual Entry')),
                ('supports_receipt_printing', models.BooleanField(default=True, verbose_name='Supports Receipt Printing')),
                ('supports_signature_capture', models.BooleanField(default=True, verbose_name='Supports Signature Capture')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clover_devices_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Company')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clover_devices_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clover Device',
                'verbose_name_plural': 'Clover Devices',
                'ordering': ['-created_at'],
                'unique_together': {('empresa', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='CloverWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=255, unique=True, verbose_name='Webhook ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='Event Type')),
                ('event_data', models.JSONField(default=dict, verbose_name='Event Data')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('processing_error', models.TextField(blank=True, verbose_name='Processing Error')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clover Webhook',
                'verbose_name_plural': 'Clover Webhooks',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='CloverTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='Transaction ID')),
                ('clover_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Clover Transaction ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('refund', 'Refund'), ('void', 'Void'), ('preauth', 'Pre-authorization'), ('capture', 'Capture')], max_length=20, verbose_name='Transaction Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error'), ('cancelled', 'Cancelled'), ('voided', 'Voided')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tip Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment Method')),
                ('card_type', models.CharField(blank=True, max_length=50, verbose_name='Card Type')),
                ('last_four_digits', models.CharField(blank=True, max_length=4, verbose_name='Last Four Digits')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Customer Email')),
                ('clover_response', models.JSONField(blank=True, default=dict, verbose_name='Clover Response')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('external_reference', models.CharField(blank=True, max_length=255, verbose_name='External Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clover.cloverdevice', verbose_name='Device')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Company')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Clover Transaction',
                'verbose_name_plural': 'Clover Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CloverConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_base_url', models.URLField(default='https://api.clover.com', verbose_name='API Base URL')),
                ('api_version', models.CharField(default='v3', max_length=10, verbose_name='API Version')),
                ('default_currency', models.CharField(default='ARS', max_length=3, verbose_name='Default Currency')),
                ('supported_currencies', models.JSONField(default=list, verbose_name='Supported Currencies')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook Secret')),
                ('webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
                ('send_email_notifications', models.BooleanField(default=True, verbose_name='Send Email Notifications')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Notification Email')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Additional Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Clover Configuration',
                'verbose_name_plural': 'Clover Configurations',
            },
        ),
    ]
