# Generated by Django 4.2 on 2025-07-15 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clover', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clovertransaction',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='clovertransaction',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clover.cloverdevice', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='clovertransaction',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='clovertransaction',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AddField(
            model_name='cloverdevice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='cloverdevice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clover_devices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cloverdevice',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cloverdevice',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clover_devices_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cloverconfiguration',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Company'),
        ),
        migrations.AlterUniqueTogether(
            name='cloverdevice',
            unique_together={('empresa', 'device_id')},
        ),
    ]
