# Generated by Django 4.2 on 2026-07-18 15:57

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionREI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry_run_id', models.UUIDField()),
                ('id_pc', models.IntegerField()),
                ('id_ejercicio', models.IntegerField()),
                ('rei_teorico', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rei_actual', models.DecimalField(decimal_places=4, max_digits=18)),
                ('estado', models.CharField(default='pendiente', max_length=16)),
                ('aprobado_por', models.CharField(blank=True, default='', max_length=64)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aprobación REI',
                'verbose_name_plural': 'Aprobaciones REI',
            },
        ),
        migrations.CreateModel(
            name='CorridaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrida_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('base_empresa', models.CharField(max_length=64)),
                ('filtros', models.JSONField(default=dict)),
                ('config_hash', models.CharField(max_length=80)),
                ('resumen', models.JSONField(default=dict)),
                ('ejecutada_por', models.CharField(default='', max_length=64)),
                ('fecha_corrida', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Corrida de auditoría contable',
                'verbose_name_plural': 'Corridas de auditoría contable',
                'ordering': ('-fecha_corrida',),
            },
        ),
        migrations.CreateModel(
            name='PlanCorreccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry_run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('base_empresa', models.CharField(max_length=64)),
                ('alcance', models.JSONField(default=dict)),
                ('config_hash', models.CharField(max_length=80)),
                ('data_fingerprint', models.CharField(default='', max_length=80)),
                ('plan', models.JSONField(default=dict)),
                ('estado', models.CharField(default='propuesto', max_length=24)),
                ('creado_por', models.CharField(default='', max_length=64)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plan de corrección contable',
                'verbose_name_plural': 'Planes de corrección contable',
            },
        ),
        migrations.CreateModel(
            name='PoliticaAuditoriaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_empresa', models.CharField(max_length=64, unique=True)),
                ('tratamiento_anulados', models.CharField(choices=[('excluir', 'Excluir anulados'), ('incluir_neutralizado', 'Incluir neutralizados')], default='excluir', max_length=32)),
                ('politica_centavo', models.CharField(choices=[('diario_manda', 'Diario manda'), ('conservar_compensacion', 'Conservar compensación VB6')], default='diario_manda', max_length=32)),
                ('prefijos_cuenta', models.JSONField(default=dict)),
                ('ejercicios_cerrados', models.CharField(choices=[('no_tocar', 'No tocar ejercicios cerrados'), ('permitir_con_reapertura', 'Permitir con reapertura')], default='no_tocar', max_length=32)),
                ('alcance_recompute', models.CharField(choices=[('ejercicio_activo', 'Ejercicio activo'), ('ejercicio_seleccionado', 'Ejercicio seleccionado'), ('historico', 'Histórico')], default='ejercicio_seleccionado', max_length=32)),
                ('tolerancia_decimal', models.DecimalField(decimal_places=4, default=Decimal('0.005'), max_digits=8)),
                ('actualizado_por', models.CharField(default='sistema', max_length=64)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Política de auditoría contable',
                'verbose_name_plural': 'Políticas de auditoría contable',
            },
        ),
    ]
