# Generated by Django 4.2 on 2026-07-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_audit', '0002_politica_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPoliticaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_empresa', models.CharField(db_index=True, max_length=64)),
                ('snapshot_anterior', models.JSONField(blank=True, null=True)),
                ('snapshot_nuevo', models.JSONField()),
                ('config_hash_anterior', models.CharField(blank=True, max_length=80, null=True)),
                ('config_hash_nuevo', models.CharField(max_length=80)),
                ('cambiado_por', models.CharField(max_length=64)),
                ('cambiado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de política de auditoría',
                'verbose_name_plural': 'Historial de políticas de auditoría',
                'ordering': ('-cambiado_en',),
            },
        ),
    ]
