# Generated by Django 4.2 on 2026-02-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLAConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        default="default", max_length=64, verbose_name="Tipo de caso"
                    ),
                ),
                (
                    "response_time_minutes",
                    models.PositiveIntegerField(verbose_name="Tiempo respuesta (min)"),
                ),
                (
                    "warning_pct",
                    models.PositiveSmallIntegerField(
                        default=80, verbose_name="Porcentaje warning (70 u 80)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_configs",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración SLA",
                "verbose_name_plural": "Configuraciones SLA",
                "db_table": "support_sla_config",
            },
        ),
        migrations.AddConstraint(
            model_name="slaconfig",
            constraint=models.UniqueConstraint(
                fields=("company", "case_type"),
                name="support_sla_config_company_case_type_unique",
            ),
        ),
    ]
