# Generated by Django 4.2 on 2025-07-05 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_branch'),
        ('inventory', '0014_productattribute_alter_productvariant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vat', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(choices=[('company', 'Company'), ('person', 'Person')], max_length=16)),
                ('origin', models.CharField(blank=True, max_length=32, null=True)),
                ('tiendanube_customer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('from_ecommerce', models.BooleanField(default=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(max_length=32)),
                ('delivery_date', models.DateField()),
                ('origin', models.CharField(blank=True, max_length=32, null=True)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(max_length=32)),
                ('invoice_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=8)),
                ('origin', models.CharField(blank=True, max_length=32, null=True)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('invoice_type', models.CharField(max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.client')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('currency', models.CharField(max_length=8)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(max_length=32)),
                ('order_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(max_length=8)),
                ('origin', models.CharField(blank=True, max_length=32, null=True)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('manual_credit_override', models.BooleanField(default=False)),
                ('credit_override_reason', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.client')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.paymentterm')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.pricelist')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=32)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(max_length=32)),
                ('return_date', models.DateField()),
                ('return_type', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('origin', models.CharField(blank=True, max_length=32, null=True)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.deliveryorder')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_qty', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('max_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('promo_code', models.CharField(blank=True, max_length=32, null=True)),
                ('rule_type', models.CharField(blank=True, max_length=32, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.pricelist')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTermLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('days', models.IntegerField()),
                ('sequence', models.IntegerField(default=1)),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.paymentterm')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(max_length=32)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=8)),
                ('payment_method', models.CharField(max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('origin', models.CharField(blank=True, max_length=32, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.invoice')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.invoice')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.paymentterm'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder'),
        ),
        migrations.CreateModel(
            name='DeliveryOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(max_length=32)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.deliveryorder')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(max_length=32)),
                ('credit_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=8)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('origin', models.CharField(blank=True, max_length=32, null=True)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.client')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.invoice')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sales.client')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
