# Generated by Django 4.2 on 2025-07-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('sales', '0002_add_sales_order_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='fiscal_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.fiscalposition', verbose_name='Fiscal Position'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='tax_lines',
            field=models.ManyToManyField(blank=True, related_name='sales_order_lines', to='accounting.taxline', verbose_name='Tax Lines'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='sales_order_lines', to='accounting.tax', verbose_name='Taxes'),
        ),
    ]
