# Generated by Django 4.2 on 2025-07-07 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_salesorderline_fiscal_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Country Code')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('name_es', models.CharField(blank=True, max_length=100, verbose_name='Country Name (Spanish)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Country Name (English)')),
                ('name_pt', models.CharField(blank=True, max_length=100, verbose_name='Country Name (Portuguese)')),
                ('phone_code', models.CharField(blank=True, max_length=10, verbose_name='Phone Code')),
                ('currency_code', models.CharField(blank=True, max_length=3, verbose_name='Currency Code')),
                ('timezone', models.CharField(blank=True, max_length=50, verbose_name='Timezone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Language Code')),
                ('name', models.CharField(max_length=50, verbose_name='Language Name')),
                ('name_native', models.CharField(max_length=50, verbose_name='Native Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Language')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='State Code')),
                ('name', models.CharField(max_length=100, verbose_name='State Name')),
                ('name_es', models.CharField(blank=True, max_length=100, verbose_name='State Name (Spanish)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='State Name (English)')),
                ('name_pt', models.CharField(blank=True, max_length=100, verbose_name='State Name (Portuguese)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'State/Province',
                'verbose_name_plural': 'States/Provinces',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['client', 'name'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Seller'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='client',
            name='fiscal_conditions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fiscal Conditions'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='Is Customer'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='Is Supplier'),
        ),
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/logos/', verbose_name='Logo/Photo'),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='client',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Timezone'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position/Job Title'),
        ),
        migrations.AddField(
            model_name='contact',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='contact',
            name='related_contacts',
            field=models.ManyToManyField(blank=True, to='sales.contact', verbose_name='Related Contacts'),
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('person', 'Person'), ('company', 'Company')], default='person', max_length=16, verbose_name='Contact Type'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Credit Limit'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='from_ecommerce',
            field=models.BooleanField(default=False, verbose_name='From E-commerce'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='origin',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tiendanube_customer_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='TiendaNube Customer ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('company', 'Company'), ('person', 'Person')], max_length=16, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vat',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='VAT/Tax ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sales.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary Contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['type'], name='sales_clien_type_0bc815_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_customer'], name='sales_clien_is_cust_76dd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_supplier'], name='sales_clien_is_supp_b33436_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='sales_clien_is_acti_73eb92_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['client', 'is_primary'], name='sales_conta_client__8fb7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['type'], name='sales_conta_type_d94b1b_idx'),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='sales.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_languages',
            field=models.ManyToManyField(blank=True, to='sales.language', verbose_name='Preferred Languages'),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.state', verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.state', verbose_name='State/Province'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['country', 'state'], name='sales_clien_country_cea9ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'code')},
        ),
    ]
