# Generated by Django 4.2 on 2025-07-07 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_contact_address_alter_contact_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_update_client_contact_models_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='client',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='related_contacts',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='sales_clien_type_0bc815_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='sales_clien_is_supp_b33436_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='sales_clien_is_acti_73eb92_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='sales_clien_country_cea9ca_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='assigned_seller',
        ),
        migrations.RemoveField(
            model_name='client',
            name='from_ecommerce',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_supplier',
        ),
        migrations.RemoveField(
            model_name='client',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='client',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='client',
            name='preferred_languages',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tiendanube_customer_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='vat',
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, help_text='Internal business entity code', max_length=20, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='client',
            name='default_delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliverylocation', verbose_name='Default Delivery Location'),
        ),
        migrations.AddField(
            model_name='client',
            name='default_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default discount percentage', max_digits=5, null=True, verbose_name='Default Discount'),
        ),
        migrations.AddField(
            model_name='client',
            name='default_price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.pricelist', verbose_name='Default Price List'),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_delivery_method',
            field=models.CharField(choices=[('email', 'Email'), ('postal', 'Postal Mail'), ('digital', 'Digital Portal')], default='email', max_length=20, verbose_name='Invoice Delivery Method'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_prospect',
            field=models.BooleanField(default=False, verbose_name='Is Prospect'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP Customer'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='bank_transfer', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='client',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sales Person'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, help_text='VAT number or tax identification', max_length=50, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, default='Argentina', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Credit Limit'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['customer_category'], name='sales_clien_custome_095d23_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_vip'], name='sales_clien_is_vip_402afc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['sales_person'], name='sales_clien_sales_p_900f73_idx'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
