# Generated by Django 4.2 on 2025-07-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_contact_empresa'),
        ('sales', '0005_remove_contact_client_remove_contact_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document_number',
            field=models.CharField(blank=True, help_text='DNI, CUIT, or other identification document', max_length=50, verbose_name='Document Number'),
        ),
        migrations.AddField(
            model_name='client',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_entities', to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=16, verbose_name='Client Type'),
        ),
    ]
