# Generated by Django 4.2 on 2025-07-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_usuarioextendido_branches_and_more'),
        ('sales', '0007_add_pos_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='pospayment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='pospromotion',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='pospromotion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='possale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='possale',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='possaleline',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='possaleline',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Company'),
        ),
        migrations.AddIndex(
            model_name='pospayment',
            index=models.Index(fields=['empresa', 'branch'], name='sales_pospa_empresa_a2db32_idx'),
        ),
        migrations.AddIndex(
            model_name='pospayment',
            index=models.Index(fields=['sale'], name='sales_pospa_sale_id_43c0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='pospayment',
            index=models.Index(fields=['payment_method'], name='sales_pospa_payment_2f0a54_idx'),
        ),
        migrations.AddIndex(
            model_name='pospromotion',
            index=models.Index(fields=['empresa', 'branch'], name='sales_pospr_empresa_ac65cc_idx'),
        ),
        migrations.AddIndex(
            model_name='pospromotion',
            index=models.Index(fields=['is_active'], name='sales_pospr_is_acti_ae6cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='pospromotion',
            index=models.Index(fields=['code'], name='sales_pospr_code_befec1_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['empresa', 'branch'], name='sales_possa_empresa_97a942_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['session'], name='sales_possa_session_db7244_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['state'], name='sales_possa_state_8e5dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='possaleline',
            index=models.Index(fields=['empresa', 'branch'], name='sales_possa_empresa_689279_idx'),
        ),
        migrations.AddIndex(
            model_name='possaleline',
            index=models.Index(fields=['sale'], name='sales_possa_sale_id_e657d0_idx'),
        ),
    ]
