# Generated by Django 4.2 on 2025-07-12 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_usuarioextendido_branches_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0008_pospayment_branch_pospayment_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the payment method', max_length=100, verbose_name='Name')),
                ('code', models.CharField(help_text='Unique identifier for the payment method', max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the payment method', verbose_name='Description')),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet'), ('check', 'Check'), ('crypto', 'Cryptocurrency'), ('buy_now_pay_later', 'Buy Now Pay Later'), ('other', 'Other')], max_length=20, verbose_name='Payment Type')),
                ('card_type', models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('diners', 'Diners Club'), ('jcb', 'JCB'), ('unionpay', 'UnionPay'), ('other', 'Other')], max_length=20, null=True, verbose_name='Card Type')),
                ('icon', models.CharField(default='credit_card', help_text='Material Design icon name', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color for UI display', max_length=7, verbose_name='Color')),
                ('logo_url', models.URLField(blank=True, help_text='URL to payment method logo', verbose_name='Logo URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, help_text='Default payment method for new transactions', verbose_name='Default')),
                ('order', models.IntegerField(default=0, help_text='Order in which to display this payment method', verbose_name='Display Order')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage charged by the payment processor', max_digits=5, verbose_name='Commission %')),
                ('fixed_commission', models.DecimalField(decimal_places=2, default=0, help_text='Fixed commission amount', max_digits=10, verbose_name='Fixed Commission')),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum transaction amount', max_digits=12, verbose_name='Minimum Amount')),
                ('maximum_amount', models.DecimalField(decimal_places=2, default=0, help_text='Maximum transaction amount (0 = no limit)', max_digits=12, verbose_name='Maximum Amount')),
                ('requires_reference', models.BooleanField(default=False, verbose_name='Requires Reference')),
                ('requires_card_number', models.BooleanField(default=False, verbose_name='Requires Card Number')),
                ('requires_expiry', models.BooleanField(default=False, verbose_name='Requires Expiry Date')),
                ('requires_cvv', models.BooleanField(default=False, verbose_name='Requires CVV')),
                ('requires_installments', models.BooleanField(default=False, verbose_name='Supports Installments')),
                ('max_installments', models.IntegerField(default=1, verbose_name='Max Installments')),
                ('processing_time_hours', models.IntegerField(default=0, help_text='Time to process payment in hours', verbose_name='Processing Time (Hours)')),
                ('supports_refunds', models.BooleanField(default=True, verbose_name='Supports Refunds')),
                ('supports_partial_refunds', models.BooleanField(default=True, verbose_name='Supports Partial Refunds')),
                ('processor_name', models.CharField(blank=True, help_text='Payment processor name (e.g., Stripe, PayPal, MercadoPago)', max_length=50, verbose_name='Processor Name')),
                ('processor_config', models.JSONField(blank=True, default=dict, help_text='Configuration for payment processor', verbose_name='Processor Configuration')),
                ('requires_3d_secure', models.BooleanField(default=False, verbose_name='Requires 3D Secure')),
                ('supports_tokenization', models.BooleanField(default=False, verbose_name='Supports Tokenization')),
                ('supported_currencies', models.JSONField(blank=True, default=list, help_text='List of supported currency codes', verbose_name='Supported Currencies')),
                ('supported_countries', models.JSONField(blank=True, default=list, help_text='List of supported country codes', verbose_name='Supported Countries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, help_text='Branches where this payment method is available', to='core.branch', verbose_name='Branches')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_methods', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('processor_type', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mercadopago', 'MercadoPago'), ('modo', 'Modo'), ('clover', 'Clover'), ('square', 'Square'), ('adyen', 'Adyen'), ('braintree', 'Braintree'), ('custom', 'Custom')], max_length=20, verbose_name='Processor Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='API Secret')),
                ('webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook Secret')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Payment Processor',
                'verbose_name_plural': 'Payment Processors',
                'ordering': ['name'],
                'unique_together': {('empresa', 'processor_type')},
            },
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['empresa', 'is_active'], name='sales_payme_empresa_9437d7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['payment_type'], name='sales_payme_payment_c168eb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['code'], name='sales_payme_code_f70cd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('empresa', 'code')},
        ),
    ]
