# Generated by Django 4.2 on 2025-07-22 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresa_country_alter_empresa_logo_and_more'),
        ('sales', '0011_add_sync_timestamp_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_synced_with_adminet',
        ),
        migrations.CreateModel(
            name='ClientTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Tag Name')),
                ('color', models.CharField(blank=True, default='#f97316', help_text='Color for visual badge', max_length=16, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tags', to='core.empresa', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Client Tag',
                'verbose_name_plural': 'Client Tags',
                'ordering': ['name'],
                'unique_together': {('empresa', 'name')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clients', to='sales.clienttag', verbose_name='Tags'),
        ),
    ]
