# Generated by Django 4.2 on 2025-07-23 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_empresa_country_alter_empresa_logo_and_more'),
        ('sales', '0012_remove_client_last_synced_with_adminet_clienttag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='clients/attachments/', verbose_name='File')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sales.client', verbose_name='Client')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_attachments', to='core.empresa', verbose_name='Company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Client Attachment',
                'verbose_name_plural': 'Client Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientattachment',
            index=models.Index(fields=['empresa', 'client', 'is_active'], name='sales_clien_empresa_d5dd50_idx'),
        ),
    ]
