# Generated by Django 4.2 on 2025-07-28 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresa_country_alter_empresa_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0013_clientattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_cancelled', 'Order Cancelled'), ('invoice_created', 'Invoice Created'), ('payment_received', 'Payment Received'), ('contact_added', 'Contact Added'), ('contact_updated', 'Contact Updated'), ('attachment_uploaded', 'Attachment Uploaded'), ('note_added', 'Note Added'), ('status_changed', 'Status Changed'), ('credit_limit_updated', 'Credit Limit Updated'), ('discount_updated', 'Discount Updated'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('visit_scheduled', 'Visit Scheduled'), ('call_logged', 'Call Logged'), ('email_sent', 'Email Sent'), ('quote_sent', 'Quote Sent'), ('complaint_logged', 'Complaint Logged'), ('other', 'Other')], max_length=32, verbose_name='Activity Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('related_data', models.JSONField(blank=True, default=dict, verbose_name='Related Data')),
                ('activity_date', models.DateTimeField(auto_now_add=True, verbose_name='Activity Date')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=16, verbose_name='Priority')),
                ('is_private', models.BooleanField(default=False, help_text='Only visible to assigned user', verbose_name='Private')),
                ('is_completed', models.BooleanField(default=True, verbose_name='Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sales.client', verbose_name='Client')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_activities', to='core.empresa', verbose_name='Company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Client Activity',
                'verbose_name_plural': 'Client Activities',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.AddIndex(
            model_name='clientactivity',
            index=models.Index(fields=['empresa', 'client'], name='sales_clien_empresa_9b842e_idx'),
        ),
        migrations.AddIndex(
            model_name='clientactivity',
            index=models.Index(fields=['activity_type'], name='sales_clien_activit_934d60_idx'),
        ),
        migrations.AddIndex(
            model_name='clientactivity',
            index=models.Index(fields=['activity_date'], name='sales_clien_activit_24d9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='clientactivity',
            index=models.Index(fields=['user'], name='sales_clien_user_id_947f55_idx'),
        ),
    ]
